/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.Dunkl.FreeParticlePathIntegral

/-!
# The Wigner–Dunkl path integral: effective action and the harmonic oscillator (Junker Eqs. 29–66)

Completes the formalization of Junker §3–§4 (arXiv:2312.12895), covering the equations of the
path-integral derivation not yet in the arc: the free Hamiltonian eigenvalue (Eq. 29–31), the dispersing
Gaussian density (Eq. 41–42), the **effective action with its singular repulsive potential** (Eq. 59–61),
the harmonic-oscillator propagator (Eq. 62), and the asymptotic-recombination relations (Eq. 65).

* **§A — the free Hamiltonian eigenvalue (Eq. 29–31).** `H_ν = P²/2m` on the Dunkl plane wave has
  eigenvalue `E_k = (ℏk)²/2m = ℏ²k²/2m` (`freeHamiltonian_eigenvalue`), from the Dunkl-momentum eigenvalue
  `ℏk` (Eq. 21).
* **§B — the dispersing Gaussian density (Eq. 41–42).** `|Ψ(x,t)|²` (`psiSqDensity`) is strictly positive
  (`psiSqDensity_pos`) and reduces at `t = 0` to the initial Gaussian (`psiSqDensity_t_zero`) — the same
  spreading as standard QM.
* **§C — the effective action (Eq. 59–61).** The path integral has action `S = ∫₀^t [½mẋ² − V_eff]`
  (`effectiveLagrangian`) with the **effective potential** `V_eff = ν²/(mx²) + V` (`effectivePotential`) —
  Junker's surprising result: WDQM is the *ordinary* Feynman path integral with an extra singular repulsive
  `ν²/mx²` term, which vanishes at `ν = 0` (`effectivePotential_zero_param`).
* **§D — the harmonic-oscillator propagator (Eq. 62).** `realHOPropagator` is the real-time Mehler–Dunkl
  kernel `(1/c_ν)(mω/iℏ sin ωt)^{ν+½} e^{imω(x²+y²)cot ωt/2ℏ} E_ν(mωxy/iℏ sin ωt)` — the Lorentzian
  counterpart of the Euclidean `mehlerDunklKernel` (Eq. 80, `Dunkl.HarmonicOscillatorFeynmanKac`).
* **§E — the recombination relations (Eq. 65).** `ε = sin(ωε)/ω·[1+O(ε²)]` and `1 − ω²ε²/2 =
  cos(ωε)·[1+O(ε²)]`: the leading recombination coefficients `d/dε sin(ωε)|₀ = ω` (`recombination_sin`)
  and `cos 0 = 1` (`recombination_cos_zero`).

No new axioms.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.Dunkl.EffectiveActionPathIntegral

open Physlib.QuantumMechanics.ComplexAction.Dunkl.FreeParticlePathIntegral

/-! ## §A — the free Hamiltonian eigenvalue (Junker Eq. 29–31) -/

/-- **[Junker Eq. 29–31] The free Hamiltonian eigenvalue** `E_k = (ℏk)²/2m = ℏ²k²/2m`. The free
Wigner–Dunkl Hamiltonian `H_ν = P²/2m` acts on the Dunkl plane wave `ψ_k ∝ E_ν(ikx)`, an eigenfunction of
the Dunkl momentum `P` with eigenvalue `ℏk` (Eq. 21); squaring gives the dispersion `dunklFreeDispersion`. -/
theorem freeHamiltonian_eigenvalue (ℏ m k : ℝ) :
    (ℏ * k) ^ 2 / (2 * m) = dunklFreeDispersion ℏ m k := by
  unfold dunklFreeDispersion; ring

/-! ## §B — the dispersing Gaussian density (Junker Eq. 41–42) -/

/-- **[Junker Eq. 42] The probability density of the spreading Gaussian wave packet**
`|Ψ(x,t)|² = (1/Γ(ν+½))(β/(1+ℏ²β²t²/m²))^{ν+½} exp(−βx²/(1+ℏ²β²t²/m²))` — identical in form to standard
quantum mechanics (only the `Γ(ν+½)` normalisation and the `^{ν+½}` power include the deformation). -/
noncomputable def psiSqDensity (ν β ℏ m t x : ℝ) : ℝ :=
  (1 / Real.Gamma (ν + 1 / 2)) * (β / (1 + ℏ ^ 2 * β ^ 2 * t ^ 2 / m ^ 2)) ^ (ν + 1 / 2)
    * Real.exp (-(β * x ^ 2) / (1 + ℏ ^ 2 * β ^ 2 * t ^ 2 / m ^ 2))

/-- **The density is strictly positive** for `ν > −½`, `β > 0` (a genuine probability density). -/
theorem psiSqDensity_pos (ν β ℏ m t x : ℝ) (hν : -(1 / 2) < ν) (hβ : 0 < β) :
    0 < psiSqDensity ν β ℏ m t x := by
  unfold psiSqDensity
  have hΓ : 0 < Real.Gamma (ν + 1 / 2) := Real.Gamma_pos_of_pos (by linarith)
  have hden : 0 < 1 + ℏ ^ 2 * β ^ 2 * t ^ 2 / m ^ 2 := by positivity
  have hbase : 0 < β / (1 + ℏ ^ 2 * β ^ 2 * t ^ 2 / m ^ 2) := div_pos hβ hden
  positivity

/-- **[Junker Eq. 38] At `t = 0` the density is the initial Gaussian** `(1/Γ(ν+½)) β^{ν+½} e^{−βx²}`. -/
theorem psiSqDensity_t_zero (ν β ℏ m x : ℝ) :
    psiSqDensity ν β ℏ m 0 x
      = (1 / Real.Gamma (ν + 1 / 2)) * β ^ (ν + 1 / 2) * Real.exp (-(β * x ^ 2)) := by
  unfold psiSqDensity; norm_num

/-! ## §C — the effective action and the singular potential (Junker Eq. 59–61) -/

/-- **[Junker Eq. 61] The effective potential** `V_eff(x) = ν²/(mx²) + V(x)` — the ordinary potential plus
the **singular repulsive** `ν²/mx²` term generated by the Dunkl reflection in the weighted Hilbert space.
This is the only difference between the WDQM path integral and the standard Feynman path integral. -/
noncomputable def effectivePotential (ν m : ℝ) (V : ℝ → ℝ) (x : ℝ) : ℝ := ν ^ 2 / (m * x ^ 2) + V x

/-- **At `ν = 0` the effective potential is the bare potential** — the singular term `ν²/mx²` disappears in
the undeformed limit (Junker's remark after Eq. 61). -/
theorem effectivePotential_zero_param (m : ℝ) (V : ℝ → ℝ) (x : ℝ) :
    effectivePotential 0 m V x = V x := by simp [effectivePotential]

/-- **[Junker Eq. 60] The effective Lagrangian** `L = ½mẋ² − V_eff` — the integrand of the path-integral
action `S = ∫₀^t L ds` (Eq. 59–60), with the effective potential of Eq. 61. -/
noncomputable def effectiveLagrangian (ν m : ℝ) (V : ℝ → ℝ) (xdot x : ℝ) : ℝ :=
  (1 / 2) * m * xdot ^ 2 - effectivePotential ν m V x

/-- **At `ν = 0` the effective Lagrangian is the ordinary `½mẋ² − V`** — the WDQM path integral becomes the
standard Feynman path integral. -/
theorem effectiveLagrangian_zero_param (m : ℝ) (V : ℝ → ℝ) (xdot x : ℝ) :
    effectiveLagrangian 0 m V xdot x = (1 / 2) * m * xdot ^ 2 - V x := by
  simp [effectiveLagrangian, effectivePotential_zero_param]

/-! ## §D — the harmonic-oscillator propagator (Junker Eq. 62) -/

/-- **[Junker Eq. 62] The real-time harmonic-oscillator propagator** `K^{HO}(x,y;t) = (1/c_ν)(mω/iℏ
sin ωt)^{ν+½} e^{imω(x²+y²)cot ωt/2ℏ} E_ν(mωxy/iℏ sin ωt)` — the closed-form Wigner–Dunkl oscillator
propagator (with `prefactor = (1/c_ν)(mω/iℏ sin ωt)^{ν+½}` and `E_ν` the Dunkl kernel). This is the
Lorentzian (real-time) counterpart of the Euclidean Mehler–Dunkl kernel `mehlerDunklKernel` (Eq. 80,
`Dunkl.HarmonicOscillatorFeynmanKac`), related by the Wick rotation `t = −iτ`
(`sin ωt → −i sinh ωτ`, `cot ωt → i coth ωτ`). -/
noncomputable def realHOPropagator (m ω ℏ t x y : ℝ) (prefactor : ℂ) (Eν : ℂ → ℂ) : ℂ :=
  prefactor
    * Complex.exp (Complex.I * m * ω * ((x : ℂ) ^ 2 + y ^ 2) * (Real.cos (ω * t) / Real.sin (ω * t))
        / (2 * ℏ))
    * Eν (m * ω * x * y / (Complex.I * ℏ * Real.sin (ω * t)))

/-- **The harmonic propagator is symmetric** `K^{HO}(x,y) = K^{HO}(y,x)` (detailed balance). -/
theorem realHOPropagator_symm (m ω ℏ t x y : ℝ) (prefactor : ℂ) (Eν : ℂ → ℂ) :
    realHOPropagator m ω ℏ t x y prefactor Eν = realHOPropagator m ω ℏ t y x prefactor Eν := by
  unfold realHOPropagator
  rw [show ((x : ℂ) ^ 2 + y ^ 2) = ((y : ℂ) ^ 2 + x ^ 2) by ring,
    show (m * ω * x * y : ℂ) = (m * ω * y * x : ℂ) by ring]

/-! ## §E — the asymptotic-recombination relations (Junker Eq. 65) -/

/-- **[Junker Eq. 65] The leading sin-recombination** `ε = sin(ωε)/ω·[1+O(ε²)]`: the derivative
`d/dε sin(ωε)|₀ = ω`, so `sin(ωε) ≈ ωε` and the short-time substitution `ε ↦ sin(ωε)/ω` is correct to
leading order — the asymptotic-recombination technique that keeps the Dunkl kernel intact. -/
theorem recombination_sin (ω : ℝ) : HasDerivAt (fun ε => Real.sin (ω * ε)) ω 0 := by
  have h := (Real.hasDerivAt_sin (ω * 0)).comp 0 ((hasDerivAt_id 0).const_mul ω)
  exact h.congr_deriv (by simp)

/-- **[Junker Eq. 65] The leading cos-recombination value** `cos(ω·0) = 1` — the constant term of
`1 − ω²ε²/2 = cos(ωε)·[1+O(ε²)]`. -/
theorem recombination_cos_zero (ω : ℝ) : Real.cos (ω * 0) = 1 := by simp

end Physlib.QuantumMechanics.ComplexAction.Dunkl.EffectiveActionPathIntegral

end
