/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.BoseFermiOperatorAlgebra.BoseObservablesII
public import Physlib.QuantumMechanics.ComplexAction.Fermion.NetObservableLocality
public import Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.LindbladSuperoperator
public import Physlib.QuantumMechanics.Lindblad.FullLindbladODE

/-!
# Kalnay finite fermions as Lindblad and Liouville superoperators

This file connects the finite Kálnay/Jordan-Wigner infrastructure to the repo's superoperator layer.

The existing Kalnay files provide:

* concrete two-mode fermion matrices `kalnayJW0`, `kalnayJW1`;
* their number projectors `fermionNumber kalnayJW0`, `fermionNumber kalnayJW1`;
* the diagonal paper-II observable `kalnayFermionDiagonalObservable w0 w1` and its Bose representative.

The existing superoperator files provide:

* Heisenberg generators `heisenbergGenerator H = -i[H, ·]`;
* Heisenberg Lindblad dissipators `lindbladDissipator L`;
* Schrödinger-picture finite-matrix Lindblad/GKLS generators with trace-preservation theorems.

This module adds the bridge operators that are natural for the Kálnay finite structure:

* `kalnayOccupationHamiltonian` and `kalnayOccupationLiouvillian` for the diagonal occupation observable;
* loss jumps (`kalnayJW0`, `kalnayJW1`), pump jumps (`star kalnayJW0`, `star kalnayJW1`), and number-dephasing
  jumps (`kalnayN0`, `kalnayN1`);
* Heisenberg unitality and `*`-compatibility inherited from `PTSymmetricQFT.LindbladSuperoperator`;
* Schrödinger-picture trace preservation inherited from `Lindblad.FullLindbladODE`.

No new axioms.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.BoseFermiOperatorAlgebra.LindbladSuperoperators

open Physlib.QuantumMechanics.ComplexAction.BoseFermiOperatorAlgebra.CompositeFermionCAR
open Physlib.QuantumMechanics.ComplexAction.BoseFermiOperatorAlgebra.FermionNetLocality
open Physlib.QuantumMechanics.ComplexAction.BoseFermiOperatorAlgebra.JordanWignerTwoMode
open Physlib.QuantumMechanics.ComplexAction.BoseFermiOperatorAlgebra.BoseObservablesII
open Physlib.QuantumMechanics.ComplexAction.Fermion.SpinStatisticsFermionParity
open Physlib.QuantumMechanics.ComplexAction.Fermion.NetObservableLocality
open Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.LindbladSuperoperator

/-- The concrete two-mode Kálnay/Jordan-Wigner matrix algebra. -/
abbrev Mat4 := Matrix (Fin 4) (Fin 4) ℂ

/-! ## Occupation observables and their Heisenberg generator -/

/-- First occupation projector `n0 = f0† f0`. -/
noncomputable def kalnayN0 : Mat4 := fermionNumber kalnayJW0

/-- Second occupation projector `n1 = f1† f1`. -/
noncomputable def kalnayN1 : Mat4 := fermionNumber kalnayJW1

/-- First parity operator `P0 = (-1)^n0`. -/
noncomputable def kalnayParity0 : Mat4 := fermionParity kalnayJW0

/-- Second parity operator `P1 = (-1)^n1`. -/
noncomputable def kalnayParity1 : Mat4 := fermionParity kalnayJW1

/-- The Kálnay paper-II diagonal occupation Hamiltonian `w0 n0 + w1 n1`. -/
noncomputable def kalnayOccupationHamiltonian (w0 w1 : ℝ) : Mat4 :=
  kalnayFermionDiagonalObservable w0 w1

/-- The Heisenberg/Liouville superoperator generated by the Kálnay occupation Hamiltonian. -/
noncomputable def kalnayOccupationLiouvillian (w0 w1 : ℝ) : Mat4 →ₗ[ℂ] Mat4 :=
  heisenbergGenerator (kalnayOccupationHamiltonian w0 w1)

/-- The occupation Hamiltonian is exactly the Bose-bilinear representative from Kalnay-Mac Cotrina II. -/
theorem kalnayOccupationHamiltonian_eq_bose (w0 w1 : ℝ) :
    kalnayOccupationHamiltonian w0 w1 = kalnayBoseDiagonalObservable w0 w1 :=
  kalnay_ii_theorem_2_5_two_mode w0 w1

/-- The occupation Hamiltonian fixes the first number projector. -/
theorem kalnayOccupationLiouvillian_n0 (w0 w1 : ℝ) :
    kalnayOccupationLiouvillian w0 w1 kalnayN0 = 0 := by
  unfold kalnayOccupationLiouvillian kalnayOccupationHamiltonian kalnayFermionDiagonalObservable kalnayN0
  rw [heisenbergGenerator_apply, fermionNumber_kalnayJW0, fermionNumber_kalnayJW1]
  ext i j
  fin_cases i <;> fin_cases j <;> simp

/-- The occupation Hamiltonian fixes the second number projector. -/
theorem kalnayOccupationLiouvillian_n1 (w0 w1 : ℝ) :
    kalnayOccupationLiouvillian w0 w1 kalnayN1 = 0 := by
  unfold kalnayOccupationLiouvillian kalnayOccupationHamiltonian kalnayFermionDiagonalObservable kalnayN1
  rw [heisenbergGenerator_apply, fermionNumber_kalnayJW0, fermionNumber_kalnayJW1]
  ext i j
  fin_cases i <;> fin_cases j <;> simp

/-- The diagonal Kálnay Liouvillian fixes the even occupation observables. -/
theorem kalnayOccupationLiouvillian_even_observables_fixed (w0 w1 : ℝ) :
    kalnayOccupationLiouvillian w0 w1 kalnayN0 = 0
      ∧ kalnayOccupationLiouvillian w0 w1 kalnayN1 = 0 :=
  ⟨kalnayOccupationLiouvillian_n0 w0 w1, kalnayOccupationLiouvillian_n1 w0 w1⟩

/-! ## Heisenberg-picture Kalnay Lindblad dissipators -/

/-- Heisenberg dissipator for loss of mode `0`. -/
noncomputable def kalnayLoss0 : Mat4 →ₗ[ℂ] Mat4 := lindbladDissipator kalnayJW0

/-- Heisenberg dissipator for loss of mode `1`. -/
noncomputable def kalnayLoss1 : Mat4 →ₗ[ℂ] Mat4 := lindbladDissipator kalnayJW1

/-- Heisenberg dissipator for pumping mode `0`. -/
noncomputable def kalnayPump0 : Mat4 →ₗ[ℂ] Mat4 := lindbladDissipator (star kalnayJW0)

/-- Heisenberg dissipator for pumping mode `1`. -/
noncomputable def kalnayPump1 : Mat4 →ₗ[ℂ] Mat4 := lindbladDissipator (star kalnayJW1)

/-- Number-dephasing dissipator for mode `0`. -/
noncomputable def kalnayDephase0 : Mat4 →ₗ[ℂ] Mat4 := lindbladDissipator kalnayN0

/-- Number-dephasing dissipator for mode `1`. -/
noncomputable def kalnayDephase1 : Mat4 →ₗ[ℂ] Mat4 := lindbladDissipator kalnayN1

@[simp] theorem kalnayLoss0_unital : kalnayLoss0 1 = 0 := lindbladDissipator_one kalnayJW0

@[simp] theorem kalnayLoss1_unital : kalnayLoss1 1 = 0 := lindbladDissipator_one kalnayJW1

@[simp] theorem kalnayPump0_unital : kalnayPump0 1 = 0 := lindbladDissipator_one (star kalnayJW0)

@[simp] theorem kalnayPump1_unital : kalnayPump1 1 = 0 := lindbladDissipator_one (star kalnayJW1)

@[simp] theorem kalnayDephase0_unital : kalnayDephase0 1 = 0 := lindbladDissipator_one kalnayN0

@[simp] theorem kalnayDephase1_unital : kalnayDephase1 1 = 0 := lindbladDissipator_one kalnayN1

/-- Loss of mode `0` preserves adjoints in the Heisenberg picture. -/
theorem kalnayLoss0_star (Y : Mat4) : star (kalnayLoss0 Y) = kalnayLoss0 (star Y) :=
  lindbladDissipator_star kalnayJW0 Y

/-- Loss of mode `1` preserves adjoints in the Heisenberg picture. -/
theorem kalnayLoss1_star (Y : Mat4) : star (kalnayLoss1 Y) = kalnayLoss1 (star Y) :=
  lindbladDissipator_star kalnayJW1 Y

/-- Pumping mode `0` preserves adjoints in the Heisenberg picture. -/
theorem kalnayPump0_star (Y : Mat4) : star (kalnayPump0 Y) = kalnayPump0 (star Y) :=
  lindbladDissipator_star (star kalnayJW0) Y

/-- Pumping mode `1` preserves adjoints in the Heisenberg picture. -/
theorem kalnayPump1_star (Y : Mat4) : star (kalnayPump1 Y) = kalnayPump1 (star Y) :=
  lindbladDissipator_star (star kalnayJW1) Y

/-- Dephasing mode `0` preserves adjoints in the Heisenberg picture. -/
theorem kalnayDephase0_star (Y : Mat4) : star (kalnayDephase0 Y) = kalnayDephase0 (star Y) :=
  lindbladDissipator_star kalnayN0 Y

/-- Dephasing mode `1` preserves adjoints in the Heisenberg picture. -/
theorem kalnayDephase1_star (Y : Mat4) : star (kalnayDephase1 Y) = kalnayDephase1 (star Y) :=
  lindbladDissipator_star kalnayN1 Y

/-- Number dephasing by `n0` fixes `n0`, since `n0` is a self-adjoint projection. -/
theorem kalnayDephase0_n0_fixed : kalnayDephase0 kalnayN0 = 0 := by
  have hs : star kalnayN0 = kalnayN0 := by
    unfold kalnayN0
    exact fermionNumber_selfAdjoint kalnayJW0
  have hp : kalnayN0 * kalnayN0 = kalnayN0 := by
    unfold kalnayN0
    exact fermionNumber_idempotent kalnayJW0 kalnayJW0_isFermionMode
  unfold kalnayDephase0
  rw [lindbladDissipator_apply, hs]
  calc kalnayN0 * kalnayN0 * kalnayN0 -
        (1 / 2 : ℂ) • (kalnayN0 * kalnayN0 * kalnayN0 + kalnayN0 * (kalnayN0 * kalnayN0))
      = kalnayN0 - (1 / 2 : ℂ) • (kalnayN0 + kalnayN0) := by
        simp [hp]
    _ = 0 := by module

/-- Number dephasing by `n1` fixes `n1`, since `n1` is a self-adjoint projection. -/
theorem kalnayDephase1_n1_fixed : kalnayDephase1 kalnayN1 = 0 := by
  have hs : star kalnayN1 = kalnayN1 := by
    unfold kalnayN1
    exact fermionNumber_selfAdjoint kalnayJW1
  have hp : kalnayN1 * kalnayN1 = kalnayN1 := by
    unfold kalnayN1
    exact fermionNumber_idempotent kalnayJW1 kalnayJW1_isFermionMode
  unfold kalnayDephase1
  rw [lindbladDissipator_apply, hs]
  calc kalnayN1 * kalnayN1 * kalnayN1 -
        (1 / 2 : ℂ) • (kalnayN1 * kalnayN1 * kalnayN1 + kalnayN1 * (kalnayN1 * kalnayN1))
      = kalnayN1 - (1 / 2 : ℂ) • (kalnayN1 + kalnayN1) := by
        simp [hp]
    _ = 0 := by module

/-! ## Schrödinger-picture finite-matrix dissipators -/

/-- The two loss jumps used by the Schrödinger-picture finite-matrix Lindblad API. -/
def kalnayLossJump : Fin 2 → Mat4
  | 0 => kalnayJW0
  | 1 => kalnayJW1

/-- The two pump jumps used by the Schrödinger-picture finite-matrix Lindblad API. -/
noncomputable def kalnayPumpJump : Fin 2 → Mat4
  | 0 => star kalnayJW0
  | 1 => star kalnayJW1

/-- The two number-dephasing jumps used by the Schrödinger-picture finite-matrix Lindblad API. -/
noncomputable def kalnayDephasingJump : Fin 2 → Mat4
  | 0 => kalnayN0
  | 1 => kalnayN1

/-- Schrödinger-picture two-mode loss dissipator. -/
noncomputable def kalnaySchrodingerLossDissipator (ρ : Mat4) : Mat4 :=
  Physlib.QuantumMechanics.Lindblad.lindbladDissipator kalnayLossJump ρ

/-- Schrödinger-picture two-mode pump dissipator. -/
noncomputable def kalnaySchrodingerPumpDissipator (ρ : Mat4) : Mat4 :=
  Physlib.QuantumMechanics.Lindblad.lindbladDissipator kalnayPumpJump ρ

/-- Schrödinger-picture two-mode number-dephasing dissipator. -/
noncomputable def kalnaySchrodingerDephasingDissipator (ρ : Mat4) : Mat4 :=
  Physlib.QuantumMechanics.Lindblad.lindbladDissipator kalnayDephasingJump ρ

/-- The two-mode loss dissipator is trace-preserving in Schrödinger picture. -/
theorem trace_kalnaySchrodingerLossDissipator_eq_zero (ρ : Mat4) :
    (kalnaySchrodingerLossDissipator ρ).trace = 0 :=
  Physlib.QuantumMechanics.Lindblad.trace_lindbladDissipator_eq_zero kalnayLossJump ρ

/-- The two-mode pump dissipator is trace-preserving in Schrödinger picture. -/
theorem trace_kalnaySchrodingerPumpDissipator_eq_zero (ρ : Mat4) :
    (kalnaySchrodingerPumpDissipator ρ).trace = 0 :=
  Physlib.QuantumMechanics.Lindblad.trace_lindbladDissipator_eq_zero kalnayPumpJump ρ

/-- The two-mode number-dephasing dissipator is trace-preserving in Schrödinger picture. -/
theorem trace_kalnaySchrodingerDephasingDissipator_eq_zero (ρ : Mat4) :
    (kalnaySchrodingerDephasingDissipator ρ).trace = 0 :=
  Physlib.QuantumMechanics.Lindblad.trace_lindbladDissipator_eq_zero kalnayDephasingJump ρ

/-- Full finite-matrix GKLS generator with the Kálnay occupation Hamiltonian and two loss jumps. -/
noncomputable def kalnayLossGKLSGenerator (w0 w1 : ℝ) (ℏ : ℝ) (ρ : Mat4) : Mat4 :=
  Physlib.QuantumMechanics.Lindblad.gklsGenerator
    (kalnayOccupationHamiltonian w0 w1) kalnayLossJump ℏ ρ

/-- The Kálnay loss GKLS generator is trace-preserving. -/
theorem trace_kalnayLossGKLSGenerator_eq_zero (w0 w1 ℏ : ℝ) (ρ : Mat4) :
    (kalnayLossGKLSGenerator w0 w1 ℏ ρ).trace = 0 :=
  Physlib.QuantumMechanics.Lindblad.trace_gklsGenerator_eq_zero
    (kalnayOccupationHamiltonian w0 w1) kalnayLossJump ℏ ρ

end Physlib.QuantumMechanics.ComplexAction.BoseFermiOperatorAlgebra.LindbladSuperoperators

end
