/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Physlib.QuantumMechanics.NonHermitian.WickRotation
public import Mathlib.Analysis.SpecialFunctions.Exponential

/-!
# Operator-level non-Hermitian Schrödinger propagator

`Physlib.QuantumMechanics.NonHermitian.WickRotation` proves the non-Hermitian Schrödinger
equation only at the **eigen/scalar** level (`evolutionFactor`, a scalar `ℂ`).
This module formalizes the **operator-level** propagator that underlies it, using
Mathlib's Banach-algebra exponential `NormedSpace.exp` on the operator algebra
`H →L[ℂ] H`:

  `U(t) = exp(t · G)`,  `G = −i H_C/ℏ`  (the Schrödinger generator).

We prove the genuine one-parameter-semigroup structure and the operator ODE:

* `propagator_zero` — `U(0) = 1`;
* `propagator_add` — `U(s+t) = U(s) U(t)` (time-translation semigroup), via
  `exp_add_of_commute`;
* `hasDerivAt_propagator` — `dU/dt = G U(t)` (the operator Schrödinger ODE, a real
  Fréchet/operator derivative from `hasDerivAt_exp_smul_const'`);
* `nonHermitian_schrodinger_operator` — `iℏ ∂_t U = H_C U`, the operator-level
  non-Hermitian Schrödinger equation, from `iHbar_smul_schrodingerGenerator`.

## Grounding the scalar evolution factor

On an `H_C`-eigenvector (`H_C ψ = E_C ψ`), the generator acts as the scalar
coefficient `−i E_C/ℏ` (`schrodingerGenerator_eigen`) — exactly the coefficient of
the scalar `evolutionFactor`'s ODE. So the operator equation restricts on each
eigenline to the scalar non-Hermitian Schrödinger equation already proven, and the
operator propagator is the genuine object the scalar factor is the matrix element
of. At `H_I = 0` the generator is `−i H_R/ℏ` (Hermitian sector),
`propagator_complexHamiltonian_at_H_I_zero`.

-/

set_option autoImplicit false

@[expose] public section

noncomputable section


open Physlib.QuantumMechanics.NonHermitian.WickRotation
namespace Physlib.QuantumMechanics.NonHermitian.Propagator

open NormedSpace QuantumMechanics.FiniteTarget

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H] [FiniteDimensional ℂ H]

/-! ## §1 — Generator and propagator -/

/-- The **Schrödinger generator** `G = −i H_C/ℏ` of the non-Hermitian Hamiltonian
`H_C`, as an operator on `H`. -/
def schrodingerGenerator (H_C : H →L[ℂ] H) (hbar : ℝ) : H →L[ℂ] H :=
  (-Complex.I / (hbar : ℂ)) • H_C

/-- The **non-Hermitian propagator** `U(t) = exp(t · G) = exp(−i H_C t/ℏ)`, the
operator exponential of the Schrödinger generator. -/
def propagator (H_C : H →L[ℂ] H) (hbar : ℝ) (t : ℝ) : H →L[ℂ] H :=
  exp (t • schrodingerGenerator H_C hbar)

/-- `U(0) = 1` (the identity operator). -/
theorem propagator_zero (H_C : H →L[ℂ] H) (hbar : ℝ) :
    propagator H_C hbar 0 = 1 := by
  unfold propagator; rw [zero_smul, exp_zero]

/-- **Time-translation semigroup**: `U(s + t) = U(s) U(t)`. -/
theorem propagator_add (H_C : H →L[ℂ] H) (hbar : ℝ) (s t : ℝ) :
    propagator H_C hbar (s + t) = propagator H_C hbar s * propagator H_C hbar t := by
  haveI : NormedAlgebra ℚ (H →L[ℂ] H) := NormedAlgebra.restrictScalars ℚ ℂ _
  unfold propagator
  rw [add_smul,
    exp_add_of_commute (((Commute.refl (schrodingerGenerator H_C hbar)).smul_left s).smul_right t)]

/-- **Operator Schrödinger ODE**: `dU/dt = G · U(t)` — a genuine operator-valued
derivative. -/
theorem hasDerivAt_propagator (H_C : H →L[ℂ] H) (hbar : ℝ) (t : ℝ) :
    HasDerivAt (propagator H_C hbar)
      (schrodingerGenerator H_C hbar * propagator H_C hbar t) t :=
  hasDerivAt_exp_smul_const' (schrodingerGenerator H_C hbar) t

/-- `iℏ · G = H_C`: the generator is `−i H_C/ℏ`, so `iℏ` times it recovers `H_C`. -/
theorem iHbar_smul_schrodingerGenerator (H_C : H →L[ℂ] H) (hbar : ℝ) (hbar0 : hbar ≠ 0) :
    (Complex.I * (hbar : ℂ)) • schrodingerGenerator H_C hbar = H_C := by
  unfold schrodingerGenerator
  have hc : (hbar : ℂ) ≠ 0 := by exact_mod_cast hbar0
  have key : Complex.I * (hbar : ℂ) * (-Complex.I / (hbar : ℂ)) = 1 := by
    rw [show Complex.I * (hbar : ℂ) * (-Complex.I / (hbar : ℂ))
          = -(Complex.I * Complex.I) * ((hbar : ℂ) / (hbar : ℂ)) from by ring,
        Complex.I_mul_I, div_self hc]; ring
  rw [smul_smul, key, one_smul]

/-- **Operator-level non-Hermitian Schrödinger equation** `iℏ ∂_t U = H_C U`.
Combines the operator ODE `∂_t U = G U` with `iℏ · G = H_C`. -/
theorem nonHermitian_schrodinger_operator (H_C : H →L[ℂ] H) (hbar : ℝ) (hbar0 : hbar ≠ 0)
    (t : ℝ) :
    (Complex.I * (hbar : ℂ)) • (schrodingerGenerator H_C hbar * propagator H_C hbar t)
      = H_C * propagator H_C hbar t := by
  rw [← smul_mul_assoc, iHbar_smul_schrodingerGenerator H_C hbar hbar0]

/-! ## §2 — Reduction and the scalar-eigenfactor connection -/

/-- At `H_I = 0` the propagator is generated by the Hermitian `H_R`
(`H_C = H_R`): the unitary Schrödinger sector. -/
theorem propagator_complexHamiltonian_at_H_I_zero (H_R : H →L[ℂ] H) (hbar t : ℝ) :
    propagator (complexHamiltonian H_R 0) hbar t = propagator H_R hbar t := by
  rw [complexHamiltonian_at_H_I_zero]

/-- **Generator acts as the scalar coefficient on an eigenvector.** If
`H_C ψ = E_C ψ` then `G ψ = (−i E_C/ℏ) ψ` — exactly the coefficient of the scalar
`evolutionFactor`'s ODE. Thus the operator Schrödinger equation restricts on each
`H_C`-eigenline to the scalar non-Hermitian equation of
`Physlib.QuantumMechanics.NonHermitian.WickRotation`. -/
theorem schrodingerGenerator_eigen (H_C : H →L[ℂ] H) (hbar : ℝ) (ψ : H) (E_C : ℂ)
    (h : H_C ψ = E_C • ψ) :
    schrodingerGenerator H_C hbar ψ = (-Complex.I / (hbar : ℂ) * E_C) • ψ := by
  unfold schrodingerGenerator
  rw [ContinuousLinearMap.smul_apply, h, smul_smul]

/-! ## §3 — Unitarity and the dynamics-side reversibility characterisation

The propagator is unitary at every time exactly when its generator is
skew-adjoint, and for the non-Hermitian `H_C = H_R − i·H_I` (self-adjoint
`H_R`, `H_I`) that happens precisely when the irreversible part `H_I` vanishes.
This is the dynamics-side companion of the entropy-side reversibility iff in
`Physlib.Thermodynamics.SecondLaw` (`ofPositiveGeneratorArrow_isReversible_forall_iff`):
no anti-Hermitian generator ⇔ genuinely unitary evolution ⇔ no entropic-time
production. -/

/-- **Unitarity criterion (Stone-type).** The non-Hermitian propagator
`U(t) = exp(t·G)` is unitary for *every* real time iff its Schrödinger generator
`G = −i H_C/ℏ` is skew-adjoint. Forward: differentiate `U(t)⋆ U(t) = 1` at
`t = 0`, giving `G⋆ + G = 0`. Converse: a real multiple of a skew-adjoint
operator is skew-adjoint, and the exponential of a skew-adjoint operator is
unitary (`NormedSpace.exp_mem_unitary_of_mem_skewAdjoint`). -/
theorem propagator_mem_unitary_forall_iff_skewAdjoint (H_C : H →L[ℂ] H) (hbar : ℝ) :
    (∀ t : ℝ, propagator H_C hbar t ∈ unitary (H →L[ℂ] H))
      ↔ schrodingerGenerator H_C hbar ∈ skewAdjoint (H →L[ℂ] H) := by
  constructor
  · intro hU
    have hU0 : HasDerivAt (propagator H_C hbar) (schrodingerGenerator H_C hbar) 0 := by
      have h := hasDerivAt_propagator H_C hbar 0
      rwa [propagator_zero, mul_one] at h
    have hmul := hU0.star.mul hU0
    have hconst : HasDerivAt
        ((fun t => star (propagator H_C hbar t)) * propagator H_C hbar) 0 0 := by
      have hf : ((fun t => star (propagator H_C hbar t)) * propagator H_C hbar)
          = (fun _ => (1 : H →L[ℂ] H)) := by
        funext t
        simpa using Unitary.star_mul_self_of_mem (hU t)
      rw [hf]; exact hasDerivAt_const 0 1
    have hsum := hmul.unique hconst
    rw [propagator_zero, mul_one, star_one, one_mul] at hsum
    rw [skewAdjoint.mem_iff]
    exact add_eq_zero_iff_eq_neg.mp hsum
  · intro hG t
    haveI : NormedAlgebra ℚ (H →L[ℂ] H) := NormedAlgebra.restrictScalars ℚ ℂ _
    unfold propagator
    refine exp_mem_unitary_of_mem_skewAdjoint (skewAdjoint.mem_iff.mpr ?_)
    rw [star_smul, star_trivial, skewAdjoint.mem_iff.mp hG, smul_neg]

omit [FiniteDimensional ℂ H] in
/-- A purely imaginary nonzero real multiple `−i H_C/ℏ` (`ℏ ≠ 0`) of `H_C` is
skew-adjoint iff `H_C` is self-adjoint: the scalar `i/ℏ ≠ 0` cancels. -/
theorem schrodingerGenerator_mem_skewAdjoint_iff_isSelfAdjoint
    (H_C : H →L[ℂ] H) (hbar : ℝ) (hbar0 : hbar ≠ 0) :
    schrodingerGenerator H_C hbar ∈ skewAdjoint (H →L[ℂ] H) ↔ IsSelfAdjoint H_C := by
  have hc : (hbar : ℂ) ≠ 0 := by exact_mod_cast hbar0
  have hcoeff : (Complex.I / (hbar : ℂ)) ≠ 0 := div_ne_zero Complex.I_ne_zero hc
  have hstar : star (-Complex.I / (hbar : ℂ)) = Complex.I / (hbar : ℂ) := by
    simp [Complex.conj_I, Complex.conj_ofReal]
  have hneg : -((-Complex.I / (hbar : ℂ)) • H_C) = (Complex.I / (hbar : ℂ)) • H_C := by
    rw [← neg_smul, neg_div, neg_neg]
  rw [skewAdjoint.mem_iff, schrodingerGenerator, star_smul, hstar, hneg]
  exact (smul_right_injective (H →L[ℂ] H) hcoeff).eq_iff

omit [FiniteDimensional ℂ H] in
/-- **The complex Hamiltonian `H_C = H_R − i·H_I` is self-adjoint iff `H_I = 0`**
(self-adjoint `H_R`, `H_I`): its anti-Hermitian part is exactly `−i·H_I`. -/
theorem complexHamiltonian_isSelfAdjoint_iff
    (H_R H_I : H →L[ℂ] H) (hR : IsSelfAdjoint H_R) (hI : IsSelfAdjoint H_I) :
    IsSelfAdjoint (complexHamiltonian H_R H_I) ↔ H_I = 0 := by
  have hRe : star H_R = H_R := hR
  have hIe : star H_I = H_I := hI
  unfold IsSelfAdjoint complexHamiltonian
  rw [star_sub, star_smul, hRe, hIe]
  simp only [Complex.star_def, Complex.conj_I]
  constructor
  · intro h
    rw [sub_eq_add_neg, sub_eq_add_neg] at h
    have h2 := add_left_cancel h
    rw [neg_inj] at h2
    have hz : ((-Complex.I) - Complex.I) • H_I = 0 := by rw [sub_smul, h2, sub_self]
    rcases smul_eq_zero.mp hz with hc0 | hψ
    · exact absurd hc0 (by norm_num [Complex.ext_iff])
    · exact hψ
  · rintro rfl; simp

/-- **Dynamics-side reversibility iff.** The propagator of the non-Hermitian
`H_C = H_R − i·H_I` (self-adjoint `H_R`, `H_I`; `ℏ ≠ 0`) is unitary at every time
iff the irreversible generator `H_I` vanishes. Composes the Stone-type criterion
with the skew-adjoint/self-adjoint computation: `H_I = 0` is exactly the
condition for the evolution to be genuinely unitary. -/
theorem propagator_complexHamiltonian_mem_unitary_forall_iff
    (H_R H_I : H →L[ℂ] H) (hbar : ℝ) (hbar0 : hbar ≠ 0)
    (hR : IsSelfAdjoint H_R) (hI : IsSelfAdjoint H_I) :
    (∀ t : ℝ, propagator (complexHamiltonian H_R H_I) hbar t ∈ unitary (H →L[ℂ] H))
      ↔ H_I = 0 :=
  (propagator_mem_unitary_forall_iff_skewAdjoint (complexHamiltonian H_R H_I) hbar).trans
    ((schrodingerGenerator_mem_skewAdjoint_iff_isSelfAdjoint (complexHamiltonian H_R H_I)
        hbar hbar0).trans (complexHamiltonian_isSelfAdjoint_iff H_R H_I hR hI))

end Physlib.QuantumMechanics.NonHermitian.Propagator

end
