/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.Dirac.FourSpinorDiracHamiltonian

/-!
# The exact (non-perturbative) free Foldy–Wouthuysen transformation (Acharya–Sudarshan 1960)

The free Foldy–Wouthuysen reduction of `Dirac.PauliEquationSpinOrbit` was framed as needing a perturbative
expansion. **It does not.** The spin–orbit/Darwin *perturbation* is Foldy–Wouthuysen **1950** (FW with
a potential); the actual content of Acharya–Sudarshan **1960** (Eqs. 13–15) is the **free** FW
transformation, which is **exact and closed-form**. The reason it is exact is the complex-oscillator
structure of this whole development: the FW generator squares to a *negative* multiple of the identity
— an `i`-like complex structure, the same rotation as the Nagao–Nielsen complex action and the
Bogoliubov diagonalization.

## The complex structure

With `α·p = p₁α₁+p₂α₂+p₃α₃` (`alphaDotP`) and `β` (the Dirac matrices of `Dirac.FourSpinorDiracHamiltonian`),
the FW generator is

 `J = β(α·p)`, `J² = −|p|²·1` (`diracComplexStructure_sq`).

`J` squares to *negative* `|p|²` — a complex structure (an imaginary unit scaled by `|p|`), exactly the
`i` of the Nagao–Nielsen complex action `e^{iS}` and the negative square of the inverted/complex
oscillator. The FW transformation is the rotation generated by `J`.

## The exact intertwining

With `E` the on-shell energy (`E² = p²+m²`) the **un-normalized FW operator**

 `W = (E+m)·1 + β(α·p)` (`fwOperator`)

exactly intertwines the Dirac Hamiltonian with the diagonal `E·β`:

 `W · H = (E·β) · W` (`fw_intertwine`),

i.e. `W H W⁻¹ = E β` — Acharya–Sudarshan Eq. 14, `i∂φ/∂t = β(p²+m²)^½ φ`, with **no perturbation
theory**: it follows from the Clifford algebra `β² = 1`, `(α·p)² = |p|²·1`, `{α·p, β} = 0`, and
`E² = p²+m²`. `W` is a "complex number" `(E+m) + J` in the algebra generated by `1` and `J`; its
modulus `W·W̄ = ((E+m)²+|p|²)·1` (`fwOperator_modulus`) is a positive scalar, so `W` is invertible — the
Bogoliubov/NN-complex-action rotation.

## Scope

The complex structure `J² = −|p|²·1`, the exact intertwining `W H = Eβ W`, and the modulus are proved
exactly from the Clifford algebra — **no perturbation, no matrix exponential**. The identification of
`W` with the *matrix exponential* `exp(βα·p̂·θ/2)` (Eq. 13) and the rotation angle `θ = arctan(|p|/m)`
is the `J² = −1` Euler relation `exp(Jθ) = cos θ + J sin θ`; the closed-form `W` here is that rotation,
stated algebraically rather than as an exponential series. The interacting (`V ≠ 0`) FW with spin–orbit
and Darwin (FW 1950) genuinely needs the `1/m` expansion and is in `Dirac.PauliEquationSpinOrbit`.

## References

* R. Acharya, E. C. G. Sudarshan, J. Math. Phys. **1** (1960) 532, Eqs. 12–15. This development:
 `Dirac.FourSpinorDiracHamiltonian`, and the complex-oscillator / Bogoliubov / Nagao–Nielsen arc.

No new axioms.
-/

set_option autoImplicit false
set_option maxHeartbeats 1000000

@[expose] public section

noncomputable section

open Matrix spaceTime Complex

namespace Physlib.QuantumMechanics.ComplexAction.Dirac.FourSpinorDiracHamiltonian

/-! ## §A — the spatial Dirac operator `α·p` and its square -/

/-- **The spatial Dirac operator** `α·p = p₁α₁ + p₂α₂ + p₃α₃` (the mass-zero Dirac Hamiltonian). -/
def alphaDotP (p1 p2 p3 : ℝ) : Matrix (Fin 4) (Fin 4) ℂ := diracHamiltonian4 p1 p2 p3 0

/-- **`(α·p)² = |p|²·1`** — the four-spinor Pauli identity for the spatial part. -/
theorem alphaDotP_sq (p1 p2 p3 : ℝ) :
    alphaDotP p1 p2 p3 * alphaDotP p1 p2 p3 = ((p1 ^ 2 + p2 ^ 2 + p3 ^ 2 : ℝ) : ℂ) • 1 := by
  rw [alphaDotP, diracHamiltonian4_sq]
  norm_num

/-- **`{α·p, β} = 0`** — the spatial Dirac operator anticommutes with `β`. -/
theorem alphaDotP_beta_anticomm (p1 p2 p3 : ℝ) :
    alphaDotP p1 p2 p3 * diracBeta + diracBeta * alphaDotP p1 p2 p3 = 0 := by
  rw [alphaDotP, diracHamiltonian4_concrete, diracBeta, γ0]
  ext a b
  fin_cases a <;> fin_cases b <;>
    simp [Matrix.mul_apply, Fin.sum_univ_four, Matrix.add_apply] <;> ring

/-! ## §B — the complex structure `J = β(α·p)`, `J² = −|p|²·1` -/

/-- **The Foldy–Wouthuysen complex structure** `J = β(α·p)`. -/
def diracComplexStructure (p1 p2 p3 : ℝ) : Matrix (Fin 4) (Fin 4) ℂ :=
  diracBeta * alphaDotP p1 p2 p3

/-- **`J² = −|p|²·1`** — the FW generator squares to a *negative* multiple of the identity: a complex
structure (the `i` of the Nagao–Nielsen complex action), the algebraic source of the exact rotation. -/
theorem diracComplexStructure_sq (p1 p2 p3 : ℝ) :
    diracComplexStructure p1 p2 p3 * diracComplexStructure p1 p2 p3
      = -(((p1 ^ 2 + p2 ^ 2 + p3 ^ 2 : ℝ) : ℂ) • 1) := by
  have hanti : alphaDotP p1 p2 p3 * diracBeta = -(diracBeta * alphaDotP p1 p2 p3) :=
    eq_neg_of_add_eq_zero_left (alphaDotP_beta_anticomm p1 p2 p3)
  rw [diracComplexStructure,
    show (diracBeta * alphaDotP p1 p2 p3) * (diracBeta * alphaDotP p1 p2 p3)
        = diracBeta * (alphaDotP p1 p2 p3 * diracBeta) * alphaDotP p1 p2 p3 from by noncomm_ring,
    hanti,
    show diracBeta * (-(diracBeta * alphaDotP p1 p2 p3)) * alphaDotP p1 p2 p3
        = -(diracBeta * diracBeta * (alphaDotP p1 p2 p3 * alphaDotP p1 p2 p3)) from by noncomm_ring,
    diracBeta_sq, alphaDotP_sq, one_mul]

/-! ## §C — the exact Foldy–Wouthuysen operator `W` and the intertwining `W H = Eβ W` -/

/-- **The un-normalized Foldy–Wouthuysen operator** `W = (E+m)·1 + β(α·p)`. -/
def fwOperator (p1 p2 p3 m E : ℝ) : Matrix (Fin 4) (Fin 4) ℂ :=
  ((E + m : ℝ) : ℂ) • 1 + diracComplexStructure p1 p2 p3

/-- **`W` in block form** `[[(E+m), σ·p],[−σ·p, (E+m)]]`. -/
theorem fwOperator_concrete (p1 p2 p3 m E : ℝ) :
    fwOperator p1 p2 p3 m E
      = !![((E + m : ℝ) : ℂ), 0, p3, p1 - p2 * I; 0, ((E + m : ℝ) : ℂ), p1 + p2 * I, -p3;
           -p3, -(p1 - p2 * I), ((E + m : ℝ) : ℂ), 0; -(p1 + p2 * I), p3, 0, ((E + m : ℝ) : ℂ)] := by
  rw [fwOperator, diracComplexStructure, alphaDotP, diracHamiltonian4_concrete, diracBeta, γ0]
  ext a b
  fin_cases a <;> fin_cases b <;>
    simp [Matrix.mul_apply, Fin.sum_univ_four, Matrix.add_apply, Matrix.one_apply] <;>
    push_cast <;> ring

/-- **The exact intertwining residual** (an identity, no on-shell constraint):
`W H − (Eβ) W = (p²+m²−E²)·β`. -/
theorem fw_intertwine_residual (p1 p2 p3 m E : ℝ) :
    fwOperator p1 p2 p3 m E * diracHamiltonian4 p1 p2 p3 m
        - ((E : ℂ) • diracBeta) * fwOperator p1 p2 p3 m E
      = ((p1 ^ 2 + p2 ^ 2 + p3 ^ 2 + m ^ 2 - E ^ 2 : ℝ) : ℂ) • diracBeta := by
  rw [fwOperator_concrete, diracHamiltonian4_concrete, diracBeta, γ0]
  ext a b
  fin_cases a <;> fin_cases b <;>
    simp [Matrix.mul_apply, Fin.sum_univ_four, Matrix.sub_apply, Matrix.smul_apply,
      Matrix.one_apply] <;>
    push_cast <;> ring_nf <;> simp only [Complex.I_sq] <;> ring

/-- **The exact free Foldy–Wouthuysen intertwining** `W H = (Eβ) W` (Acharya–Sudarshan Eq. 14), for
the on-shell energy `E² = p²+m²`. So `W H W⁻¹ = Eβ`: the Dirac Hamiltonian is *exactly* diagonalized to
`±√(p²+m²)·β` by the closed-form rotation `W` — **no perturbation theory**. -/
theorem fw_intertwine (p1 p2 p3 m E : ℝ) (hE : E ^ 2 = p1 ^ 2 + p2 ^ 2 + p3 ^ 2 + m ^ 2) :
    fwOperator p1 p2 p3 m E * diracHamiltonian4 p1 p2 p3 m
      = ((E : ℂ) • diracBeta) * fwOperator p1 p2 p3 m E := by
  have hz : (p1 ^ 2 + p2 ^ 2 + p3 ^ 2 + m ^ 2 - E ^ 2 : ℝ) = 0 := by linarith [hE]
  have hk := fw_intertwine_residual p1 p2 p3 m E
  rw [hz, Complex.ofReal_zero, zero_smul] at hk
  exact sub_eq_zero.mp hk

/-! ## §D — `W` is a "complex number": the modulus and invertibility -/

/-- **The modulus of `W`** `W·W̄ = ((E+m)² + |p|²)·1` with `W̄ = (E+m)·1 − β(α·p)` — a *positive scalar*
multiple of the identity, so `W` is invertible. `W = (E+m) + J` behaves as a complex number with `J`
the imaginary unit (`J² = −|p|²·1`): the Bogoliubov / Nagao–Nielsen complex-action rotation. -/
theorem fwOperator_modulus (p1 p2 p3 m E : ℝ) :
    fwOperator p1 p2 p3 m E * (((E + m : ℝ) : ℂ) • 1 - diracComplexStructure p1 p2 p3)
      = (((E + m) ^ 2 + (p1 ^ 2 + p2 ^ 2 + p3 ^ 2) : ℝ) : ℂ) • 1 := by
  rw [fwOperator_concrete, diracComplexStructure, alphaDotP, diracHamiltonian4_concrete,
    diracBeta, γ0]
  ext a b
  fin_cases a <;> fin_cases b <;>
    simp [Matrix.mul_apply, Fin.sum_univ_four, Matrix.sub_apply, Matrix.smul_apply,
      Matrix.one_apply] <;>
    push_cast <;> ring_nf <;> simp only [Complex.I_sq] <;> ring

/-! ## §E — the exact reduction, bundled -/

/-- **The exact free Foldy–Wouthuysen reduction (Acharya–Sudarshan 1960), no perturbation theory.**
For the on-shell energy `E² = p²+m²`:

* **(complex structure)** the FW generator `J = β(α·p)` squares to `−|p|²·1` — the `i` of the
  Nagao–Nielsen complex action / the negative square of the complex oscillator;
* **(exact intertwining)** `W H = (Eβ) W`, i.e. `W H W⁻¹ = Eβ` — the Dirac Hamiltonian is diagonalized
  to `±√(p²+m²)·β` by the closed-form rotation `W`, with no `1/m` expansion;
* **(invertibility)** `W·W̄ = ((E+m)²+|p|²)·1`, a positive scalar — `W` is the Bogoliubov rotation. -/
theorem foldyWouthuysen_exact (p1 p2 p3 m E : ℝ) (hE : E ^ 2 = p1 ^ 2 + p2 ^ 2 + p3 ^ 2 + m ^ 2) :
    diracComplexStructure p1 p2 p3 * diracComplexStructure p1 p2 p3
        = -(((p1 ^ 2 + p2 ^ 2 + p3 ^ 2 : ℝ) : ℂ) • 1)
      ∧ fwOperator p1 p2 p3 m E * diracHamiltonian4 p1 p2 p3 m
        = ((E : ℂ) • diracBeta) * fwOperator p1 p2 p3 m E
      ∧ fwOperator p1 p2 p3 m E * (((E + m : ℝ) : ℂ) • 1 - diracComplexStructure p1 p2 p3)
        = (((E + m) ^ 2 + (p1 ^ 2 + p2 ^ 2 + p3 ^ 2) : ℝ) : ℂ) • 1 :=
  ⟨diracComplexStructure_sq p1 p2 p3, fw_intertwine p1 p2 p3 m E hE,
   fwOperator_modulus p1 p2 p3 m E⟩

end Physlib.QuantumMechanics.ComplexAction.Dirac.FourSpinorDiracHamiltonian

end
