/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.StatisticalMechanics.VonNeumannCarnotComputability
public import Physlib.QuantumMechanics.RelationalTime.LiouvillianTimeOperator
public import Physlib.QuantumMechanics.ComplexAction.ThermoFieldDynamics.Basic
public import Physlib.QuantumMechanics.ComplexAction.PeriodicQHermitian.Ehrenfest
public import Mathlib.LinearAlgebra.Matrix.Trace

/-!
# Tomita-Takesaki modular theory, factors and the type classification (Kazama 2024, §2.2/§4)

Extends the von Neumann–algebra layer (`AlgebraicQFT.GNSVonNeumannHadamard` commutant, `StatisticalMechanics.VonNeumannCarnotComputability`
trace) with the algebraic kernel of **Tomita-Takesaki modular theory** and the **factor / type
classification**, following Y. Kazama, *von Neumann Algebra and Quantum Gravity* (YITP, 2024).

## The modular automorphism is generated by `ad` of the modular Hamiltonian

For a cyclic-separating vector `Ψ`, Tomita's operator `S_Ψ(aΨ) = a*Ψ` polar-decomposes as
`S_Ψ = J_Ψ Δ_Ψ^{1/2}` with modular operator `Δ_Ψ = S_Ψ* S_Ψ` and modular conjugation `J_Ψ` (Eqs 4.8–4.9).
Writing `Δ_Ψ = e^{−K}` with `K` the **modular Hamiltonian** (Eq 4.12, `K Ψ = 0`), the **modular automorphism**
`σ_s(a) = Δ_Ψ^{is} a Δ_Ψ^{−is}` (Eq 4.15) has, at `s = 0`, generator `i[K, a] = i·ad_K(a)`. So the
Tomita-Takesaki modular flow *is* the repo's `collisionStar = ad` Liouvillian with `K = log Δ` the generator —
the same operator as the TFD hat-Hamiltonian and `AlgebraicQFT.GNSVonNeumannHadamard`'s commutant kernel.

* **§A — the modular generator** (`modularGenerator`, `modularFixed`, `modularFixed_eq_commutant`,
  `modularHamiltonian_mem_fixed`, `modularGenerator_tracial_zero`). `δ_K = ad_K = collisionStar K`; its
  fixed-point algebra (the `σ`-invariant observables, = the centralizer of the state) is the commutant
  `{K}'` (consuming `mem_commutant_iff_collisionStar_zero`); `K` itself is fixed; and any tracial state is
  modular-invariant, `τ(δ_K a) = 0`.
* **§B — the tracial / type II₁ case** (`modularGenerator_zero`, `modularFixed_zero`). For a tracial state the
  maximally-entangled vector gives `Δ = 1`, `K = 0`: the modular flow is trivial (`σ_s = id`), *every*
  observable is fixed — the hallmark of a finite (type II₁) trace.
* **§C — the centre / factor** (`center_eq_iInter_modularFixed`, `center_subset_modularFixed`). The centre
  `Z(A) = A'` (commutant of everything) is exactly the common kernel of *all* modular generators; central
  observables are modular-invariant under every modular Hamiltonian. A **factor** is the case `Z(A) = ℂ·1`
  (`vnCentre` minimal).
* **§D — a concrete trace (type I_n / II₁ vs III)** (`normTrace`, `normTrace_cyclic`, `normTrace_one`). The
  normalized matrix trace `τ = Tr / dim` with `τ(ab) = τ(ba)` and `τ(1) = 1` — a finite trace defined on the
  *whole* algebra (type I_n, the `n → ∞` limit being II₁). Type III factors admit *no* such trace (hence no
  density matrix, no entropy), the Minkowski-QFT local algebras being type III₁.
* **§E — bridges to the repo's Liouvillian generators** (`modularGenerator_eq_liouvillian`,
  `modularGenerator_eq_hatHamiltonian`, `vonNeumannGen_eq_smul_modularGenerator`). The modular generator `δ_K`
  *is* the Misra-Prigogine `liouvillian` (`RelationalTime.LiouvillianTimeOperator`, the internal-time
  generator), the TFD `hatHamiltonian` (`ThermoFieldDynamics.Basic`, the KMS/thermal superoperator), and — up to
  `−(i/ℏ)` — the von Neumann state rate `vonNeumannGen` (`PeriodicQHermitian.Ehrenfest`). One commutator superoperator,
  four names: modular automorphism = Liouville flow = TFD hat-evolution = von Neumann equation.

## References

* Y. Kazama, *von Neumann Algebra and Quantum Gravity*, YITP workshop (2024).
* M. Takesaki, *Theory of Operator Algebras* I–III (Tomita-Takesaki theory).
* E. Witten, *Notes on some entanglement properties of quantum field theory*, RMP 90 (2018) 045003.
* Repo dependencies: `AlgebraicQFT.GNSVonNeumannHadamard` (`commutant`, `mem_commutant_iff_collisionStar_zero`, `vnCentre`),
  `CollisionOperatorSl2.CollisionModular` (`collisionStar`, `collisionStar_self`), `StatisticalMechanics.VonNeumannCarnotComputability`
  (`tracial_commutator_zero`), `RelationalTime.LiouvillianTimeOperator` (`liouvillian`), `ThermoFieldDynamics.Basic`
  (`hatHamiltonian`, `hatHamiltonian_eq_collisionStar`), `PeriodicQHermitian.Ehrenfest` (`vonNeumannGen`).

No new axioms.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.ThermoFieldDynamics.KazamaTomitaTakesakiModular

open Physlib.QuantumMechanics.ComplexAction.CollisionOperatorSl2.CollisionModular
open Physlib.QuantumMechanics.ComplexAction.AlgebraicQFT.GNSVonNeumannHadamard
open Physlib.QuantumMechanics.ComplexAction.StatisticalMechanics.VonNeumannCarnotComputability

/-! ## §A — the modular generator `δ_K = ad_K` -/

section Modular
variable {A : Type*} [Ring A]

/-- **[Tomita-Takesaki, generator of `σ_s`] The modular generator** `δ_K = ad_K = [K,·] = collisionStar K`,
where `K = log Δ_Ψ` is the modular Hamiltonian (`Δ_Ψ = e^{−K}`, Eq 4.12). The modular automorphism
`σ_s(a) = Δ^{is} a Δ^{−is}` (Eq 4.15) has this as its `s = 0` derivative (up to `i`); it is the repo's
`collisionStar` Liouvillian, the TFD hat-Hamiltonian / `AlgebraicQFT.GNSVonNeumannHadamard` commutant kernel. -/
def modularGenerator (K : A) : A → A := collisionStar K

/-- **The fixed-point algebra of the modular flow** — the observables annihilated by `δ_K`, i.e. the
`σ_s`-invariant elements (the centralizer of the state). -/
def modularFixed (K : A) : Set A := {a | modularGenerator K a = 0}

/-- **[Modular fixed points = commutant of the modular Hamiltonian] `Fix(σ) = {K}'`.** The observables
invariant under the modular automorphism are exactly those commuting with `K = log Δ` — the von Neumann
commutant of the modular Hamiltonian (`mem_commutant_iff_collisionStar_zero`). -/
theorem modularFixed_eq_commutant (K : A) : modularFixed K = commutant ({K} : Set A) := by
  ext a
  rw [modularFixed, Set.mem_setOf_eq, modularGenerator]
  exact (mem_commutant_iff_collisionStar_zero K a).symm

/-- **The modular Hamiltonian is modular-invariant** `K ∈ Fix(σ)` — `[K,K] = 0` (`collisionStar_self`); the
flow fixes its own generator, the algebraic form of `Δ Ψ = Ψ` (Eq 4.11). -/
theorem modularHamiltonian_mem_fixed (K : A) : K ∈ modularFixed K := collisionStar_self K

/-- **[KMS / modular invariance of the trace] `τ(δ_K a) = 0`.** Any tracial state is invariant under the
modular automorphism — its derivative is annihilated by the cyclic functional
(`tracial_commutator_zero`). The trace is the modular-invariant (KMS, `β = 0`) state. -/
theorem modularGenerator_tracial_zero (τ : A →+ ℂ) (htr : ∀ a b, τ (a * b) = τ (b * a)) (K a : A) :
    τ (modularGenerator K a) = 0 :=
  tracial_commutator_zero τ htr K a

end Modular

/-! ## §B — the tracial / type II₁ case: trivial modular flow -/

section TypeII
variable {A : Type*} [Ring A]

/-- **[Type II₁, `Δ = 1`] The tracial modular flow is trivial** — for the maximally-entangled vector the
modular operator is the identity, `K = log Δ = 0`, so `δ_0 a = 0` for every `a`. The trace is its own
modular-invariant state. -/
theorem modularGenerator_zero (a : A) : modularGenerator (0 : A) a = 0 := by
  rw [modularGenerator, collisionStar, zero_mul, mul_zero, sub_zero]

/-- **Every observable is modular-fixed in the tracial case** `Fix(σ_0) = A` — the defining trait of a finite
(type II₁) trace defined on the *whole* algebra. -/
theorem modularFixed_zero : modularFixed (0 : A) = Set.univ := by
  ext a; simp [modularFixed, modularGenerator_zero]

end TypeII

/-! ## §C — the centre and the factor condition -/

section Centre
variable {A : Type*} [Ring A]

/-- **[The centre = common kernel of all modular generators] `Z(A) = ⋂_a ker δ_a`.** The centre `Z(A) = A'`
(the commutant of the whole algebra) consists exactly of the observables annihilated by *every* modular
generator `δ_a = ad_a`. A **factor** is `Z(A) = ℂ·1`. -/
theorem center_eq_iInter_modularFixed :
    commutant (Set.univ : Set A) = {z | ∀ a, modularGenerator a z = 0} := by
  ext z
  rw [commutant, Set.mem_centralizer_iff, Set.mem_setOf_eq]
  constructor
  · intro h a
    rw [modularGenerator, collisionStar, sub_eq_zero]; exact h a (Set.mem_univ a)
  · intro h a _
    have hz := h a; rw [modularGenerator, collisionStar, sub_eq_zero] at hz; exact hz

/-- **Central observables are modular-invariant under every modular Hamiltonian** `Z(A) ⊆ Fix(σ_K)` — the
centre sits inside every modular fixed-point algebra. -/
theorem center_subset_modularFixed (K : A) :
    commutant (Set.univ : Set A) ⊆ modularFixed K := by
  intro z hz
  rw [center_eq_iInter_modularFixed, Set.mem_setOf_eq] at hz
  rw [modularFixed, Set.mem_setOf_eq, modularGenerator, collisionStar, sub_eq_zero]
  have hzK := hz K
  rw [modularGenerator, collisionStar, sub_eq_zero] at hzK
  exact hzK

end Centre

/-! ## §D — a concrete trace: type I_n / II₁ versus type III -/

section ConcreteTrace
variable {n : Type*} [Fintype n]

/-- **The normalized matrix trace** `τ(M) = Tr(M) / dim` — the canonical finite trace on `M_n(ℂ)`. (Type I_n;
its `n → ∞` hyperfinite limit is the type II₁ factor with `τ(1) = 1`.) -/
noncomputable def normTrace (M : Matrix n n ℂ) : ℂ := (Fintype.card n : ℂ)⁻¹ * Matrix.trace M

/-- **[Tracial property] `τ(ab) = τ(ba)`** — the cyclicity defining a trace (Kazama §2.2,
`Tr(ab) = Tr(ba)`), via `Matrix.trace_mul_comm`. -/
theorem normTrace_cyclic (a b : Matrix n n ℂ) : normTrace (a * b) = normTrace (b * a) := by
  rw [normTrace, normTrace, Matrix.trace_mul_comm]

/-- **[Normalization] `τ(1) = 1`** — the finite trace is normalized on the whole algebra, the trait of type
I_n / II₁ (a type III factor admits no such trace, hence no density matrix and no entropy). -/
theorem normTrace_one [DecidableEq n] [Nonempty n] : normTrace (1 : Matrix n n ℂ) = 1 := by
  rw [normTrace, Matrix.trace_one, mul_comm, mul_inv_cancel₀]
  simp [Fintype.card_ne_zero]

end ConcreteTrace

/-! ## §E — bridges to the repo's Liouvillian / von Neumann generators -/

section Bridges
open Physlib.QuantumMechanics.RelationalTime
open Physlib.QuantumMechanics.ComplexAction.ThermoFieldDynamics.Basic

/-- **[Modular generator = Misra-Prigogine Liouvillian] `δ_K = L`.** The Tomita-Takesaki modular generator is
the `RelationalTime.LiouvillianTimeOperator.liouvillian` `L X = [K,X]` — the generator of the time-translation
flow `ρ ↦ e^{−iKt}ρe^{iKt}` whose conjugate is the Misra-Prigogine internal-time operator (`i[L,T]=I`). The
modular flow and the Liouville/internal-time flow are one. -/
theorem modularGenerator_eq_liouvillian {d : Type*} [Fintype d] [DecidableEq d]
    (K X : Matrix d d ℂ) : modularGenerator K X = liouvillian K X := rfl

/-- **[Modular generator = TFD hat-Hamiltonian] `δ_H = ℋ̂`.** The modular generator is the
`ThermoFieldDynamics.Basic.hatHamiltonian` `ℋ̂ = mulLeft H − mulRight H` — the thermal/KMS superoperator driving
`iℏ∂_t|Ψ⟩ = ℋ̂|Ψ⟩`. Tomita-Takesaki's modular automorphism is the TFD hat-evolution, the algebraic statement
of the modular-KMS correspondence. -/
theorem modularGenerator_eq_hatHamiltonian {n : ℕ} (H ρ : Matrix (Fin n) (Fin n) ℂ) :
    modularGenerator H ρ = hatHamiltonian H ρ := by
  rw [modularGenerator]; exact (hatHamiltonian_eq_collisionStar H ρ).symm

/-- **[Modular generator drives the von Neumann equation] `dρ/dt = −(i/ℏ)·δ_H ρ`.** The
`PeriodicQHermitian.Ehrenfest.vonNeumannGen` state rate `−(i/ℏ)[H,ρ]` is the same commutator `δ_H = [H,·]`, scaled by
`−(i/ℏ)`: the von Neumann/Schrödinger generator and the modular generator differ only by that scalar. (For a
KMS state with `H` the modular Hamiltonian the modular automorphism `σ_s` is *real*-time evolution rescaled by
`β`, `t = ℏβs`; the imaginary-time content is the separate `β`-periodicity of the KMS condition, not the
modular parameter `s`.) -/
theorem vonNeumannGen_eq_smul_modularGenerator {n : Type*} [Fintype n] [DecidableEq n]
    (ℏ : ℂ) (H ρ : Matrix n n ℂ) :
    PeriodicQHermitian.Basic.vonNeumannGen ℏ H ρ = -(Complex.I / ℏ) • modularGenerator H ρ := by
  rw [PeriodicQHermitian.Basic.vonNeumannGen, PeriodicQHermitian.Basic.commutator, modularGenerator, collisionStar]

end Bridges

end Physlib.QuantumMechanics.ComplexAction.ThermoFieldDynamics.KazamaTomitaTakesakiModular

end
