/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.ThermoFieldDynamics.TFDImaginaryPart
public import Physlib.QuantumMechanics.ComplexAction.ComplexDelta.Contour

/-!
# The thermo-Bogoliubov one-parameter group and its su(1,1) generator (Celeghini et al. 1998)

Improves the static thermo-Bogoliubov matrix `thermoBogoliubov` (`ThermoFieldDynamics.TFDImaginaryPart`, the `U_B` of the thermal
propagator) with the **Hopf-algebra / one-parameter-group structure** of *E. Celeghini, S. De Martino, S. De
Siena, A. Iorio, M. Rasetti, G. Vitiello, "Thermo field dynamics and quantum algebras", Phys. Lett. A 244
(1998) 455–461*. There the Bogoliubov transformation `a(θ) = a·cosh√σθ − ã†·sinh√σθ` (Eq. 31) is shown to be
a one-parameter group `a(θ+θ̄) = e^{iθ̄𝒢}a(θ)e^{−iθ̄𝒢}` (Eq. 39) generated by `𝒢 = −i√σ(a†ã† − aã)` (Eq. 35),
satisfying the differential law `δ²/δθ² a(θ) = σ a(θ)` (Eq. 37). At the level of the `2×2` matrix `U_B(θ)`
(the boson `σ=1` case), this is:

* **one-parameter group** `U_B(θ₁)·U_B(θ₂) = U_B(θ₁+θ₂)` (cosh/sinh addition) — the inequivalent
  representations of TFD are labelled by the additive parameter `θ`;
* **su(1,1) generator** `U_B(θ) = cosh θ·1 + sinh θ·K = e^{θK}`, with `K = [[0,1],[1,0]]` involutive (`K² = 1`)
  — `K` is the `2×2` realization of `𝒢`, and `e^{θK}` the Bogoliubov boost;
* **the differential law** `δθ cosh = sinh`, `δθ sinh = cosh` (so `δ²/δθ² = 1`, the `σ=1` of Eq. 37).

The generator acts by commutator (`−iδθ a(θ) = [𝒢, a(θ)]`, Eq. 38) — the *same* adjoint/Liouville structure as
`ThermoFieldDynamics.Basic.hatHamiltonian` (`= collisionStar`).

* **§A — the one-parameter group** (`thermoBogoliubov_zero`, `thermoBogoliubov_group`,
  `thermoBogoliubov_neg`). Eq. 39.
* **§B — the su(1,1) generator** (`bogoliubovGenerator`, `bogoliubovGenerator_sq`, `thermoBogoliubov_eq_gen`).
  Eqs. 35/37: `U_B = e^{θK}`, `K²=1`.
* **§C — the differential law** (`bogoliubov_amplitude_deriv`). Eq. 37: `δθ cosh = sinh`, `δθ sinh = cosh`.
* **§D — the fermion (su(2)) Bogoliubov** (`fermiBogoliubov`, `fermiBogoliubov_det`, `fermiBogoliubov_group`,
  `fermiBogoliubovGenerator`, `fermiBogoliubovGenerator_sq`, `fermiBogoliubov_eq_gen`,
  `fermiBogoliubov_amplitude_deriv`). The `σ=−1` case (`√σ=i`, `cosh→cos`, `sinh→i·sin`): the **compact**
  rotation `R(θ)` with generator `J²=−1` (su(2)), dual to the boson **boost** `K²=+1` (su(1,1)) — the `σ=±1`
  of Eq. 37 distinguishing `h_q(1)` (bosons) from `h_q(1|1)` (fermions).
* **§E — integration with the Nagao–Nielsen contour** (`fermiBogoliubov_rayRotation`,
  `fermiBogoliubov_convergenceForm`). The fermion su(2) Bogoliubov `R(θ)` **is** the NN contour rotation —
  multiplication by the ray direction `e^{iθ}` on `ℂ ≅ ℝ²` (`ComplexDelta.Contour`); its NN convergence form is
  `cos 2θ`, positive exactly in the contour wedge `|θ|<π/4`. (The boson boost is the non-compact dual, the
  Wick rotation `θ↦iθ` of this rotation.)

## References

* E. Celeghini et al., Phys. Lett. A 244 (1998) 455–461 (Eqs. 31, 35, 37, 39; the `h_q(1)` Hopf algebra,
  su(1,1)/su(2) TFD algebras).
* Repo dependencies: `ThermoFieldDynamics.TFDImaginaryPart.thermoBogoliubov` (the `U_B` this gives group/generator structure to);
  `ThermoFieldDynamics.Basic.hatHamiltonian` (`= collisionStar`, the adjoint/Liouville structure of the generator).

No new axioms.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.ThermoFieldDynamics.TFDBogoliubovHopf

open Matrix
open Physlib.QuantumMechanics.ComplexAction.ThermoFieldDynamics.TFDImaginaryPart
open Physlib.QuantumMechanics.ComplexAction.ComplexDelta.Convergence
open Physlib.QuantumMechanics.ComplexAction.ComplexDelta.Contour

/-! ## §A — the one-parameter group (Eq. 39) -/

/-- **`U_B(0) = 1`** — the identity Bogoliubov transformation (`θ=0`, the trivial representation). -/
theorem thermoBogoliubov_zero : thermoBogoliubov 0 = 1 := by
  rw [thermoBogoliubov, Real.cosh_zero, Real.sinh_zero]
  ext i j; fin_cases i <;> fin_cases j <;> simp

/-- **[Eq. 39] The thermo-Bogoliubov is a one-parameter group** `U_B(θ₁)·U_B(θ₂) = U_B(θ₁+θ₂)` — the
inequivalent TFD representations are labelled by the additive parameter `θ` (cosh/sinh addition). -/
theorem thermoBogoliubov_group (θ₁ θ₂ : ℝ) :
    thermoBogoliubov θ₁ * thermoBogoliubov θ₂ = thermoBogoliubov (θ₁ + θ₂) := by
  simp only [thermoBogoliubov, Matrix.mul_fin_two, Real.cosh_add, Real.sinh_add]
  ext i j; fin_cases i <;> fin_cases j <;> simp <;> ring

/-- **The inverse is the reversed boost** `U_B(θ)·U_B(−θ) = 1` — `θ ↦ −θ` inverts the Bogoliubov
transformation. -/
theorem thermoBogoliubov_neg (θ : ℝ) : thermoBogoliubov θ * thermoBogoliubov (-θ) = 1 := by
  rw [thermoBogoliubov_group, add_neg_cancel, thermoBogoliubov_zero]

/-! ## §B — the su(1,1) generator `K` (Eqs. 35, 37) -/

/-- **The Bogoliubov generator** `K = [[0,1],[1,0]]` — the `2×2` realization of `𝒢 = −i√σ(a†ã† − aã)`
(Eq. 35), the off-diagonal su(1,1) boost generator. -/
def bogoliubovGenerator : Matrix (Fin 2) (Fin 2) ℝ := !![0, 1; 1, 0]

/-- **The generator is involutive** `K² = 1` — so `e^{θK}` truncates to `cosh θ·1 + sinh θ·K`. -/
theorem bogoliubovGenerator_sq : bogoliubovGenerator * bogoliubovGenerator = 1 := by
  rw [bogoliubovGenerator, Matrix.mul_fin_two]
  ext i j; fin_cases i <;> fin_cases j <;> simp

/-- **[Eq. 31 = `e^{θK}`] The Bogoliubov boost is the exponential of the generator** `U_B(θ) = cosh θ·1 +
sinh θ·K` — since `K² = 1`, the matrix exponential `e^{θK}` collapses to the `cosh`/`sinh` form, exhibiting
`K` as the infinitesimal su(1,1) generator of the Bogoliubov one-parameter group. -/
theorem thermoBogoliubov_eq_gen (θ : ℝ) :
    thermoBogoliubov θ = Real.cosh θ • (1 : Matrix (Fin 2) (Fin 2) ℝ)
      + Real.sinh θ • bogoliubovGenerator := by
  ext i j; fin_cases i <;> fin_cases j <;>
    simp [thermoBogoliubov, bogoliubovGenerator]

/-! ## §C — the differential law (Eq. 37) -/

/-- **[Eq. 37, `σ=1`] The Bogoliubov differential law** `δθ cosh θ = sinh θ`, `δθ sinh θ = cosh θ` — so each
amplitude obeys `δ²/δθ² = 1`; the `θ`-derivative rotates `cosh ↔ sinh`, the off-diagonal generation by `K`. -/
theorem bogoliubov_amplitude_deriv (θ : ℝ) :
    HasDerivAt Real.cosh (Real.sinh θ) θ ∧ HasDerivAt Real.sinh (Real.cosh θ) θ :=
  ⟨Real.hasDerivAt_cosh θ, Real.hasDerivAt_sinh θ⟩

/-! ## §D — the fermion (su(2)) Bogoliubov (σ = −1) -/

/-- **The fermion thermo-Bogoliubov** `R(θ) = [[cos θ, −sin θ],[sin θ, cos θ]]` — the `σ=−1` case of Eq. 31
(`√σ=i`, `cosh√σθ=cos θ`, `sinh√σθ=i·sin θ`): a *compact* `SO(2)`/su(2) rotation, dual to the boson boost. -/
noncomputable def fermiBogoliubov (θ : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  !![Real.cos θ, -Real.sin θ; Real.sin θ, Real.cos θ]

/-- **The fermion Bogoliubov is special-orthogonal** `det R = cos²θ + sin²θ = 1`. -/
theorem fermiBogoliubov_det (θ : ℝ) : (fermiBogoliubov θ).det = 1 := by
  rw [fermiBogoliubov, Matrix.det_fin_two_of]
  nlinarith [Real.sin_sq_add_cos_sq θ]

/-- **`R(0) = 1`**. -/
theorem fermiBogoliubov_zero : fermiBogoliubov 0 = 1 := by
  rw [fermiBogoliubov, Real.cos_zero, Real.sin_zero]
  ext i j; fin_cases i <;> fin_cases j <;> simp

/-- **[Eq. 39, fermions] The fermion Bogoliubov is a one-parameter group** `R(θ₁)·R(θ₂) = R(θ₁+θ₂)` — the
su(2) rotation group of the fermion inequivalent representations (cos/sin addition). -/
theorem fermiBogoliubov_group (θ₁ θ₂ : ℝ) :
    fermiBogoliubov θ₁ * fermiBogoliubov θ₂ = fermiBogoliubov (θ₁ + θ₂) := by
  simp only [fermiBogoliubov, Matrix.mul_fin_two, Real.cos_add, Real.sin_add]
  ext i j; fin_cases i <;> fin_cases j <;> simp <;> ring

/-- **The fermion (su(2)) generator** `J = [[0,−1],[1,0]]` — the compact rotation generator. -/
def fermiBogoliubovGenerator : Matrix (Fin 2) (Fin 2) ℝ := !![0, -1; 1, 0]

/-- **The fermion generator squares to `−1`** `J² = −1 = σ·1` (`σ=−1`) — the *compact* (su(2)) counterpart of
the boson `K² = +1` (su(1,1)); the sign is the `σ` of the Eq. 37 differential law `δ²/δθ² = σ`. -/
theorem fermiBogoliubovGenerator_sq : fermiBogoliubovGenerator * fermiBogoliubovGenerator = -1 := by
  rw [fermiBogoliubovGenerator, Matrix.mul_fin_two]
  ext i j; fin_cases i <;> fin_cases j <;> simp

/-- **[Eq. 31 = `e^{θJ}`, fermions] The fermion Bogoliubov is the exponential of `J`** `R(θ) = cos θ·1 +
sin θ·J` — since `J²=−1`, `e^{θJ}` collapses to the `cos`/`sin` rotation. -/
theorem fermiBogoliubov_eq_gen (θ : ℝ) :
    fermiBogoliubov θ = Real.cos θ • (1 : Matrix (Fin 2) (Fin 2) ℝ)
      + Real.sin θ • fermiBogoliubovGenerator := by
  ext i j; fin_cases i <;> fin_cases j <;> simp [fermiBogoliubov, fermiBogoliubovGenerator]

/-- **[Eq. 37, `σ=−1`] The fermion differential law** `δθ cos θ = −sin θ`, `δθ sin θ = cos θ` — so each
amplitude obeys `δ²/δθ² = −1 = σ`, the compact counterpart of the boson `δ²/δθ² = +1`. -/
theorem fermiBogoliubov_amplitude_deriv (θ : ℝ) :
    HasDerivAt Real.cos (-Real.sin θ) θ ∧ HasDerivAt Real.sin (Real.cos θ) θ :=
  ⟨Real.hasDerivAt_cos θ, Real.hasDerivAt_sin θ⟩

/-! ## §E — integration with the Nagao–Nielsen contour -/

/-- **[Bridge] The fermion su(2) Bogoliubov is the NN contour rotation.** Applying `R(θ)` to the components
`(Re z, Im z)` gives the components of `e^{iθ}·z` — i.e. `fermiBogoliubov θ` is the matrix of multiplication by
the Nagao–Nielsen ray direction `e^{iθ}` (`ComplexDelta.Contour`) on `ℂ ≅ ℝ²`. The compact su(2) Bogoliubov
*is* the contour rotation. -/
theorem fermiBogoliubov_rayRotation (θ : ℝ) (z : ℂ) :
    fermiBogoliubov θ *ᵥ ![z.re, z.im]
      = ![(Complex.exp (θ * Complex.I) * z).re, (Complex.exp (θ * Complex.I) * z).im] := by
  funext i
  fin_cases i <;>
    simp [fermiBogoliubov, Matrix.mulVec, Complex.mul_re, Complex.mul_im,
      Complex.exp_ofReal_mul_I_re, Complex.exp_ofReal_mul_I_im] <;> ring

/-- **The NN convergence form of the Bogoliubov rotation is `cos 2θ`** — the Lorentzian (convergence) form on
the ray direction `e^{iθ}` of the fermion rotation is `cos 2θ` (`ComplexDelta.Contour.lorentzianForm_rayDir`),
so the rotated NN Gaussian converges exactly on the permitted cone `|θ| < π/4`. -/
theorem fermiBogoliubov_convergenceForm (θ : ℝ) :
    lorentzianForm (Complex.exp (θ * Complex.I)) = Real.cos (2 * θ) :=
  lorentzianForm_rayDir θ

end Physlib.QuantumMechanics.ComplexAction.ThermoFieldDynamics.TFDBogoliubovHopf

end
