/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Mathlib.Tactic.NoncommRing
public import Mathlib.Tactic.FieldSimp
public import Mathlib.Data.Complex.Basic

/-!
# The `sl₂` Casimir is central, and quantum integers `[n]_q` (Sawin §3)

The link invariants of Sawin's account arise from the ribbon Hopf algebra `U_s(sl₂)`, the quantum deformation
of the universal enveloping algebra `U(sl₂)` (Sawin, *Links, Quantum Groups and TQFT's*, q-alg/9506002, §3).
This file formalizes two diagram-free algebraic cores of that section.

* **§A — the `sl₂` presentation and its Casimir (p. 15).** `U(sl₂)` is generated by `{x, y, h}` with the
  relations `[h, x] = 2x`, `[h, y] = −2y`, `[x, y] = h` (`[a, b] = ab − ba`, the ring commutator `commR`).
  From these alone the **Casimir element** `C = (h+1)² + 4yx` (`casimirElt`, the cleared-denominator form of
  the usual `(h+1)²/4 + yx`) is **central**: `casimir_central_h`, `casimir_central_x`, `casimir_central_y` give
  `[C, h] = [C, x] = [C, y] = 0`. Centrality of the Casimir is what makes it act as a scalar on each
  irreducible representation — the quantum number labelling the spin-`j` representations `V_n`.
* **§B — quantum integers `[n]_q` (p. 16).** `qInt s n = (s^{2n} − s^{−2n})/(s² − s^{−2})` with `q = s²`
  (Sawin's convention). `qInt_zero`, `qInt_one`, `qInt_two = s² + s^{−2}`. The quantum dimension of the
  two-dimensional fundamental representation `V₂` is `[2]_q = s² + s^{−2}`, and with `A = s` the Kauffman
  bracket **loop value** `−A² − A^{−2}` is exactly `−[2]_q` (`kauffmanLoopValue_eq_neg_qInt_two`) — the
  "annoying minus sign" of the self-dual fundamental representation noted on p. 17.

## References

* S. Sawin, *Links, Quantum Groups and TQFT's*, q-alg/9506002, §1 (Kauffman bracket loop value `−A²−A⁻²`),
  §3 (`U(sl₂)` relations p. 15, the algebra `U_s(sl₂)` and quantum integers `[n]_q` p. 16, the fundamental
  representation and the loop-value sign p. 17).

No new axioms.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.QuantumGroupSkein.QuantumGroupSl2Casimir

/-! ## §A — the ring commutator and its Leibniz calculus -/

variable {R : Type*} [Ring R]

/-- **The ring commutator** `[a, b] = ab − ba`. -/
def commR (a b : R) : R := a * b - b * a

@[simp] theorem commR_self (a : R) : commR a a = 0 := by unfold commR; noncomm_ring

theorem commR_one_left (a : R) : commR 1 a = 0 := by unfold commR; noncomm_ring

theorem commR_antisymm (a b : R) : commR a b = -commR b a := by unfold commR; noncomm_ring

/-- **Additivity in the left slot.** `[a + b, c] = [a, c] + [b, c]`. -/
theorem commR_add_left (a b c : R) : commR (a + b) c = commR a c + commR b c := by
  unfold commR; noncomm_ring

/-- **Leibniz rule in the left slot.** `[ab, c] = a[b, c] + [a, c]b`. -/
theorem commR_mul_left (a b c : R) : commR (a * b) c = a * commR b c + commR a c * b := by
  unfold commR; noncomm_ring

/-- **Central numeral scalars pull out of the commutator.** `[4z, w] = 4[z, w]`. -/
theorem commR_four_mul (z w : R) : commR (4 * z) w = 4 * commR z w := by
  unfold commR; noncomm_ring

/-! ## §B — the `sl₂` Casimir is central (Sawin p. 15) -/

/-- **The `sl₂` Casimir element** `C = (h+1)² + 4yx` (Sawin p. 15–16). This is `4` times the usual
`(h+1)²/4 + yx`; the cleared-denominator form is central over any ring, with no need to invert `4`. -/
def casimirElt (x y h : R) : R := (h + 1) ^ 2 + 4 * (y * x)

variable {x y h : R}

/-- **[The Casimir commutes with `h`]** `[C, h] = 0`, from `[h, x] = 2x` and `[h, y] = −2y`. -/
theorem casimir_central_h (hhx : h * x - x * h = 2 * x) (hhy : h * y - y * h = -(2 * y)) :
    commR (casimirElt x y h) h = 0 := by
  have hcx : commR h x = 2 * x := hhx
  have hcy : commR h y = -(2 * y) := hhy
  have hxh : commR x h = -(2 * x) := by rw [commR_antisymm, hcx]
  have hyh : commR y h = 2 * y := by rw [commR_antisymm, hcy]; exact neg_neg _
  have hh1h : commR (h + 1) h = 0 := by
    rw [commR_add_left, commR_self, zero_add, commR_one_left]
  unfold casimirElt
  rw [commR_add_left, pow_two, commR_mul_left, hh1h, commR_four_mul, commR_mul_left, hxh, hyh]
  noncomm_ring

/-- **[The Casimir commutes with `x`]** `[C, x] = 0`, from `[h, x] = 2x` and `[x, y] = h`. -/
theorem casimir_central_x (hhx : h * x - x * h = 2 * x) (hxy : x * y - y * x = h) :
    commR (casimirElt x y h) x = 0 := by
  have hcx : commR h x = 2 * x := hhx
  have hcxy : commR x y = h := hxy
  have hyx : commR y x = -h := by rw [commR_antisymm, hcxy]
  have hh1x : commR (h + 1) x = 2 * x := by
    rw [commR_add_left, hcx, commR_one_left, add_zero]
  have hhx' : h * x = x * h + 2 * x := by rw [sub_eq_iff_eq_add.mp hhx]; abel
  unfold casimirElt
  rw [commR_add_left, pow_two, commR_mul_left, hh1x, commR_four_mul, commR_mul_left,
    commR_self, hyx]
  have key : (h + 1) * (2 * x) + 2 * x * (h + 1) + 4 * (y * 0 + -h * x)
      = -2 * (h * x) + 2 * (x * h) + 4 * x := by noncomm_ring
  rw [key, hhx']
  noncomm_ring

/-- **[The Casimir commutes with `y`]** `[C, y] = 0`, from `[h, y] = −2y` and `[x, y] = h`. -/
theorem casimir_central_y (hhy : h * y - y * h = -(2 * y)) (hxy : x * y - y * x = h) :
    commR (casimirElt x y h) y = 0 := by
  have hcy : commR h y = -(2 * y) := hhy
  have hcxy : commR x y = h := hxy
  have hh1y : commR (h + 1) y = -(2 * y) := by
    rw [commR_add_left, hcy, commR_one_left, add_zero]
  have hhy' : h * y = y * h - 2 * y := by rw [sub_eq_iff_eq_add.mp hhy]; abel
  unfold casimirElt
  rw [commR_add_left, pow_two, commR_mul_left, hh1y, commR_four_mul, commR_mul_left,
    commR_self, hcxy]
  have key : (h + 1) * -(2 * y) + -(2 * y) * (h + 1) + 4 * (y * h + 0 * x)
      = -2 * (h * y) + 2 * (y * h) - 4 * y := by noncomm_ring
  rw [key, hhy']
  noncomm_ring

/-! ## §C — quantum integers `[n]_q` and the Kauffman loop value (Sawin p. 16–17) -/

/-- **The quantum integer** `[n]_q = (s^{2n} − s^{−2n})/(s² − s^{−2})` with `q = s²` (Sawin p. 16). -/
noncomputable def qInt (s : ℂ) (n : ℕ) : ℂ :=
  (s ^ (2 * n) - (s ^ (2 * n))⁻¹) / (s ^ 2 - (s ^ 2)⁻¹)

/-- **[`[0]_q = 0`]** -/
@[simp] theorem qInt_zero (s : ℂ) : qInt s 0 = 0 := by simp [qInt]

/-- **[`[1]_q = 1`]** (`s² − s^{−2} ≠ 0`). -/
theorem qInt_one (s : ℂ) (hd : s ^ 2 - (s ^ 2)⁻¹ ≠ 0) : qInt s 1 = 1 := by
  rw [qInt, show 2 * 1 = 2 from rfl]; exact div_self hd

/-- **[`[2]_q = s² + s^{−2}`]** — the quantum dimension of the two-dimensional fundamental representation
`V₂` of `U_s(sl₂)` (Sawin p. 17). -/
theorem qInt_two (s : ℂ) (hs : s ≠ 0) (hd : s ^ 2 - (s ^ 2)⁻¹ ≠ 0) :
    qInt s 2 = s ^ 2 + (s ^ 2)⁻¹ := by
  have h2 : s ^ 2 ≠ 0 := pow_ne_zero 2 hs
  rw [qInt, show 2 * 2 = 4 from rfl, div_eq_iff hd]
  field_simp
  ring

/-- **The Kauffman bracket loop value** `−A² − A^{−2}` with `A = s` (Sawin §1, Eq. 3): the value of a
disjoint unknot in the bracket skein relation. -/
noncomputable def kauffmanLoopValue (s : ℂ) : ℂ := -s ^ 2 - (s ^ 2)⁻¹

/-- **[Loop value = `−[2]_q`]** the Kauffman bracket loop value `−A² − A^{−2}` is minus the quantum
dimension `[2]_q` of the self-dual fundamental representation of `U_s(sl₂)` (with `A = s`) — the
characteristic minus sign of the unoriented `sl₂` tangle functor (Sawin p. 17). -/
theorem kauffmanLoopValue_eq_neg_qInt_two (s : ℂ) (hs : s ≠ 0) (hd : s ^ 2 - (s ^ 2)⁻¹ ≠ 0) :
    kauffmanLoopValue s = -qInt s 2 := by
  rw [qInt_two s hs hd, kauffmanLoopValue]; ring

end Physlib.QuantumMechanics.ComplexAction.QuantumGroupSkein.QuantumGroupSl2Casimir

end
