/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Physlib.StatisticalMechanics.EntropyProduction
public import Physlib.QuantumMechanics.Lindblad.GreensFunction
public import Physlib.Relativity.Special.ProperTime

/-!
# The Lindblad dissipator as the Noether entropy defect

The Noether balance law's dissipative defect is realised concretely by a Lindblad
jump operator `L`: the defect is `Γ = ⟨ψ, L†L ψ⟩ = ‖L ψ‖² ≥ 0`, positive
*structurally* (`L†L ⪰ 0`). This specialises the abstract Noether-defect chain to
the repo's open-system layer and packages the consequences:

  `defect = ‖L ψ‖² ≥ 0`
  ⇒ entropy-production rate `(2/ℏ) defect`
  ⇒ `S_I` (hence `τ_ent`) monotone
  ⇒ proper-time Green's kernel contractive for `σ ≥ 0`.


## References

- **Lindblad 1976** — *On the generators of quantum dynamical semigroups*
- **Gorini, Kossakowski, Sudarshan 1976** — *Completely positive dynamical semigroups of N-level systems*
- **Spohn 1978** — *Entropy production for quantum dynamical semigroups*
- **Gough, Ratiu, Smolyanov 2015** — *Noether's theorem for dissipative quantum semigroups*
- **Noether 1918** — *Invariante Variationsprobleme*
-/

set_option autoImplicit false

@[expose] public section

noncomputable section


open Physlib.StatisticalMechanics.EntropyProduction Physlib.QuantumMechanics.Lindblad.GreensFunction
open Physlib.Thermodynamics.SecondLaw
namespace Physlib.QuantumMechanics.Lindblad.NoetherDefect

open QuantumMechanics.FiniteTarget

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H] [FiniteDimensional ℂ H]

/-- The **Noether dissipative defect of a Lindblad jump** `L`: `Γ = ⟨ψ, L†L ψ⟩`. -/
def lindbladNoetherDefect (L : H →L[ℂ] H) (ψ : H) : ℝ := lindbladRate L ψ

/-- The Lindblad Noether defect is non-negative — structurally, from `L†L ⪰ 0`. -/
theorem lindbladNoetherDefect_nonneg (L : H →L[ℂ] H) (ψ : H) :
    0 ≤ lindbladNoetherDefect L ψ := lindbladRate_nonneg L ψ

/-- The defect is the squared jump amplitude `‖L ψ‖²`. -/
theorem lindbladNoetherDefect_eq_normSq (L : H →L[ℂ] H) (ψ : H) :
    lindbladNoetherDefect L ψ = ‖L ψ‖ ^ 2 := lindbladRate_eq_normSq L ψ

/-- The entropy-time arrow generated by the Lindblad Noether defect (its
monotonicity holds unconditionally — `L†L` positivity establishes it). -/
def ofLindbladNoetherDefect (H_R L : H →L[ℂ] H) (hbar : ℝ) (hbar_pos : 0 < hbar)
    (ψ : H) : EntropyArrowWorldline :=
  ofLindbladJump H_R L hbar hbar_pos ψ

/-- **Lindblad–Noether theorem.** A Lindblad jump's positive defect generates the
entropic-time arrow and the Green's-function contraction, packaging the chain
`defect = ‖Lψ‖² ≥ 0 ⇒ entropyRate = (2/ℏ)defect ⇒ S_I monotone ⇒ ‖G(σ)‖ ≤ 1`. -/
theorem lindblad_noether_generates_entropic_time
    (H_R L : H →L[ℂ] H) (hbar : ℝ) (hbar_pos : 0 < hbar) (ψ : H) (E_R : ℝ) :
    lindbladNoetherDefect L ψ = ‖L ψ‖ ^ 2
    ∧ 0 ≤ lindbladNoetherDefect L ψ
    ∧ (positiveGeneratorSystem H_R (lindbladDissipator L) hbar hbar_pos
        (lindbladDissipator_isPositive L)).entropyRate ψ
        = (2 / hbar) * lindbladNoetherDefect L ψ
    ∧ (∀ {t₁ t₂ : ℝ}, t₁ ≤ t₂ →
        (ofLindbladNoetherDefect H_R L hbar hbar_pos ψ).S_I_along t₁ ≤
          (ofLindbladNoetherDefect H_R L hbar hbar_pos ψ).S_I_along t₂)
    ∧ (∀ σ : ℝ, 0 ≤ σ → ‖properTimeGreenKernel E_R (lindbladNoetherDefect L ψ) σ‖ ≤ 1) :=
  ⟨lindbladRate_eq_normSq L ψ,
   lindbladRate_nonneg L ψ,
   lindblad_greenKernel_rate_eq_entropyRate H_R L hbar hbar_pos ψ,
   fun {_ _} h => (ofLindbladJump H_R L hbar hbar_pos ψ).S_I_monotone h,
   fun σ hσ => lindblad_greenKernel_contraction L ψ E_R σ hσ⟩

/-! ## Entropic chain bridge — quantum side -/

open QuantumInfo.Finite SpaceTime in
/-- **Quantum-side entropic chain bridge.**  A Lindblad jump simultaneously
establishes the dissipation/2nd-law direction *and* the geometric-recovery
direction of the entropic chain, packaged into one theorem:

* **(1)** positive Noether defect `‖Lψ‖² ≥ 0`,
* **(2)** the resulting `EntropyArrowWorldline` has monotone `S_I` (2nd law),
* **(3)** at the **Frozen-LRF** (`ρ = σ`), `SpaceTime.properTime` is exactly
  the total proper time `geometricInterval + entropicProperTimeMetric`.

This composes `lindbladNoetherDefect_nonneg`, the entropy-arrow generated by
`ofLindbladNoetherDefect`, and the frozen-LRF bridge
`properTime_eq_totalProperTimeMetric_at_frozen`.  No new axioms. -/
theorem lindblad_drives_entropic_time_at_frozen
    {sd : ℕ} {d : Type*} [Fintype d] [DecidableEq d]
    (H_R L : H →L[ℂ] H) (hbar : ℝ) (hbar_pos : 0 < hbar) (ψ : H)
    (U : EntropicTimeUnits) (q p : SpaceTime sd) (ρ : MState d) :
    0 ≤ lindbladNoetherDefect L ψ
    ∧ (∀ {t₁ t₂ : ℝ}, t₁ ≤ t₂ →
        (ofLindbladNoetherDefect H_R L hbar hbar_pos ψ).S_I_along t₁ ≤
          (ofLindbladNoetherDefect H_R L hbar hbar_pos ψ).S_I_along t₂)
    ∧ SpaceTime.properTime q p = totalProperTimeMetric U q p ρ ρ :=
  ⟨lindbladNoetherDefect_nonneg L ψ,
   fun {_ _} h => (ofLindbladNoetherDefect H_R L hbar hbar_pos ψ).S_I_monotone h,
   SpaceTime.properTime_eq_totalProperTimeMetric_at_frozen U q p ρ⟩

end Physlib.QuantumMechanics.Lindblad.NoetherDefect

end
