/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.PathIntegral.ComplexActionPathIntegralWeight

/-!
# Entropic Dynamics: the transition probability of QFT in curved spacetime (Ipek–Abedi–Caticha)

Formalizes §2 of Ipek–Abedi–Caticha (*Entropic Dynamics: Reconstructing Quantum Field Theory in Curved
Space-time*, arXiv:1803.07493): the field-theoretic entropic-dynamics transition probability, obtained by
maximizing the relative entropy `S[P,Q] = −∫ P log(P/Q)` subject to a drift-potential constraint. Per point the
result is a **Gaussian**

`P(Δχ) = (1/Z) exp(−½ α (Δχ − b)²)` (their Eq. 6),

with **expected drift** `b = ⟨Δχ⟩ = δφ/(g^{1/2}α)` (Eq. 8) and **fluctuation variance** `⟨Δw²⟩ = 1/(g^{1/2}α)`
(Eq. 9). This Gaussian is exactly the entropic weight `kuikenWeight = e^{−·/·}` of the arc — the entropic-dynamics
transition probability sits on the same hub as the quasi-free state, confinement, the sum-over-histories quantum
measure, the causal-set gravity path integral, and the complex-action weight.

* the **transition probability is `e^{−(entropic action)}`** (`edTransitionWeight`,
 `edTransitionWeight_eq_exp_neg_action`), peaked at the drift `Δχ = b` (`edTransitionWeight_peak_at_drift`) and
 bounded by `1` (`edTransitionWeight_le_one`) — a bona-fide entropic suppression;
* the **drift is the variance times the drift force** `b = ⟨Δw²⟩ · δφ` (`edDrift_eq_variance_mul_force`), the
 fluctuation–dissipation relation of the diffusion; the drift is `∼1/α`, the fluctuation `∼1/√α`, so
 `drift²/variance = δφ²/(g^{1/2}α) → 0` as `α → ∞` (`ed_drift_sq_over_variance`) — the fluctuations dominate and
 the trajectory is a continuous, non-differentiable **Brownian motion** (Eq. 9);
* the **transition probability is the entropic weight** `e^{−½α(Δχ−b)²} = kuikenWeight (2/α) ((Δχ−b)²)`
 (`edTransitionWeight_is_kuiken`) — entropic dynamics is on the arc's `kuikenWeight` hub.

So the reconstruction of QFT in curved spacetime from maximum entropy gives a Gaussian transition probability that
is the arc's entropic weight, with the drift potential `φ` (the phase of `ψ = √ρ e^{iφ}`) generating the guidance
drift — entropic dynamics unified with the von-Neumann-algebraic, path-integral, and causal-set structures on one
`e^{−·/·}` weight.

* **§A — the entropic action and transition probability** (`edEntropicAction`, `edTransitionWeight`).
* **§B — drift and fluctuation** (`edDrift`, `edFluctuationVariance`, `edDrift_eq_variance_mul_force`).
* **§C — the Brownian scaling** (`ed_drift_sq_over_variance`).
* **§D — the transition weight is an entropic suppression** (`edTransitionWeight_le_one`, `_peak_at_drift`).
* **§E — on the `kuikenWeight` hub** (`edTransitionWeight_is_kuiken`).

The Gaussian transition weight, the drift/variance relation, the Brownian scaling ratio, and
the `kuikenWeight` identification are exact `Real.exp`/field algebra. The maximum-entropy *derivation* of the
Gaussian (the variational calculation over field configurations), the functional Fokker–Planck evolution, and the
foliation-invariance constraint are *recorded*, not derived. No new axioms.

## References

* S. Ipek, M. Abedi, A. Caticha, arXiv:1803.07493, §2 (Eqs. 1–9, transition probability, drift, fluctuations).
 Repo structure: `PathIntegral.ComplexActionPathIntegralWeight` (`kuikenWeight`).

No new axioms.
-/

set_option autoImplicit false

open Physlib.QuantumMechanics.ComplexAction.PathIntegral.ComplexActionPathIntegralWeight

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.EntropicTime.EntropicDynamicsTransitionProbability

/-! ## §A — the entropic action and transition probability -/

/-- **The entropic-dynamics action** `½ α (Δχ − b)²` — the cost of a step `Δχ` against the expected drift `b`,
with `α` the (maximum-entropy) multiplier `∝ 1/variance` (Ipek–Abedi–Caticha Eq. 6). -/
noncomputable def edEntropicAction (α b Δχ : ℝ) : ℝ := α * (Δχ - b) ^ 2 / 2

/-- **The entropic-dynamics transition probability** (per point) `P(Δχ) ∝ e^{−½ α (Δχ − b)²}` (Eq. 6) — the
Gaussian obtained by maximizing the relative entropy subject to the drift-potential constraint. -/
noncomputable def edTransitionWeight (α b Δχ : ℝ) : ℝ := Real.exp (-(edEntropicAction α b Δχ))

/-- **[The transition probability is `e^{−(entropic action)}`].** The Gaussian transition weight is the
exponential of the entropic action, the maximum-entropy cost of a step. -/
theorem edTransitionWeight_eq_exp_neg_action (α b Δχ : ℝ) :
    edTransitionWeight α b Δχ = Real.exp (-(edEntropicAction α b Δχ)) := rfl

/-! ## §B — drift and fluctuation -/

/-- **The expected drift** `b = δφ/(g^{1/2}α)` (Ipek–Abedi–Caticha Eq. 8) — the guidance step generated by the
drift potential `φ` (the gradient `δφ/δχ`), with `g^{1/2}` the surface scalar density. -/
noncomputable def edDrift (root_g α δφ : ℝ) : ℝ := δφ / (root_g * α)

/-- **The fluctuation variance** `⟨Δw²⟩ = 1/(g^{1/2}α)` (Ipek–Abedi–Caticha Eq. 9) — the isotropic Gaussian
fluctuation of the entropic step. -/
noncomputable def edFluctuationVariance (root_g α : ℝ) : ℝ := 1 / (root_g * α)

/-- **[The drift is the variance times the drift force] `b = ⟨Δw²⟩ · δφ`.** The expected drift is the fluctuation
variance times the drift-potential gradient — the fluctuation–dissipation relation of the entropic diffusion. -/
theorem edDrift_eq_variance_mul_force (root_g α δφ : ℝ) :
    edDrift root_g α δφ = edFluctuationVariance root_g α * δφ := by
  unfold edDrift edFluctuationVariance; ring

/-! ## §C — the Brownian scaling -/

/-- **[The drift is negligible against fluctuations: Brownian scaling] `b²/⟨Δw²⟩ = δφ²/(g^{1/2}α)`.** Since the
drift is `∼1/α` and the fluctuation `∼1/√α`, the ratio `b²/⟨Δw²⟩ = δφ²/(g^{1/2}α) → 0` as `α → ∞`: for short
steps the fluctuations dominate the drift and the trajectory is a continuous, non-differentiable Brownian motion
(Eq. 9). -/
theorem ed_drift_sq_over_variance (root_g α δφ : ℝ) (hg : root_g ≠ 0) (hα : α ≠ 0) :
    (edDrift root_g α δφ) ^ 2 / edFluctuationVariance root_g α = δφ ^ 2 / (root_g * α) := by
  unfold edDrift edFluctuationVariance
  field_simp

/-! ## §D — the transition weight is an entropic suppression -/

/-- **[The transition probability is bounded by one] `P(Δχ) ≤ 1`.** For a non-negative multiplier `α`, the
Gaussian transition weight is a bona-fide entropic suppression — the entropic action is non-negative. -/
theorem edTransitionWeight_le_one (α b Δχ : ℝ) (hα : 0 ≤ α) : edTransitionWeight α b Δχ ≤ 1 := by
  unfold edTransitionWeight edEntropicAction
  rw [Real.exp_le_one_iff]
  have h : 0 ≤ α * (Δχ - b) ^ 2 := mul_nonneg hα (sq_nonneg _)
  linarith

/-- **[The transition probability peaks at the drift] `P(b) = 1`.** The most probable step is the expected drift
`Δχ = b`, where the entropic action vanishes — the deterministic guidance velocity of the diffusion. -/
theorem edTransitionWeight_peak_at_drift (α b : ℝ) : edTransitionWeight α b b = 1 := by
  unfold edTransitionWeight edEntropicAction; simp

/-! ## §E — on the `kuikenWeight` hub -/

/-- **[The entropic-dynamics transition probability is the entropic weight]
`e^{−½α(Δχ−b)²} = kuikenWeight (2/α) ((Δχ−b)²)`.** The maximum-entropy transition probability of QFT in curved
spacetime is the complex-action entropic weight `kuikenWeight c Π = e^{−Π/c}` with entropic action `Π = (Δχ−b)²`
and `c = 2/α`: entropic dynamics sits on the same `e^{−·/·}` hub as the quasi-free state, confinement, the
sum-over-histories quantum measure, and the causal-set gravity path integral. -/
theorem edTransitionWeight_is_kuiken (α b Δχ : ℝ) (hα : α ≠ 0) :
    edTransitionWeight α b Δχ = kuikenWeight (2 / α) ((Δχ - b) ^ 2) := by
  unfold edTransitionWeight edEntropicAction kuikenWeight
  congr 1
  field_simp

end Physlib.QuantumMechanics.ComplexAction.EntropicTime.EntropicDynamicsTransitionProbability

end
