/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.EntropicTime.HamiltonKillingComplexStructureSchrodinger
public import Physlib.QuantumMechanics.ComplexAction.EntropicTime.EntropicDynamicsCanonicalRepresentation

/-!
# The normalization constraint and the information geometry of e-phase space (Caticha 2107.08502 §§3–4)

Continues `HamiltonKillingComplexStructureSchrodinger` with the normalization constraint (§3, Eqs. 20–25) and the
information geometry of the e-phase space up to the metric induced on `T*S` (§4, Eqs. 26–32) of Caticha
(arXiv:2107.08502).

* the **normalization constraint** `Ñ = 1 − |ρ|` with `|ρ| = ∑ρⁱ` (their Eq. 20) is zero exactly when the
 probabilities are normalized (`normalized_iff`); the flow generated by `Ñ` shifts all momenta `π → π + ν`
 (their Eq. 24), which on the wave function is a **phase multiplication** `ψ ↦ e^{iν}ψ`
 (`hamiltonKilling_phaseShift_gauge`) — the gauge symmetry that makes quantum states **rays**, not vectors;
* the **information metric of the simplex** is the Fisher–Rao metric `g = B/(2ρ) = 1/(2ρ)` (their Eq. 26,
 `fisherRaoMetric`), and its `δρ` line element is exactly the entropic-dynamics **quantum potential / Fisher
 information** `(δρ)²/ρ = 2 g (δρ)²` (`quantumPotential_is_fisherRao_lineElement`);
* the **metric induced on the e-phase space `T*S`** — the distance between rays — is the **Fubini–Study metric**
 `δs² = (1/2ρ)(δρ)² + 2ρ(δπ − ⟨δπ⟩)²` (their Eq. 32, `fubiniStudyMetric`), non-negative
 (`fubiniStudyMetric_nonneg`), fully determined by information geometry.

So the normalization constraint is the phase gauge that makes states rays, and the metric on those rays is the
Fubini–Study metric, whose `δρ` part is the Fisher information (the entropic-dynamics quantum potential) — the
information geometry that grounds the Hamilton–Killing derivation of quantum mechanics.

* **§A — the normalization constraint** (`normalizationConstraint`, `normalized_iff`).
* **§B — the phase-shift gauge: states are rays** (`hamiltonKilling_phaseShift_gauge`).
* **§C — the Fisher–Rao metric = the quantum potential** (`fisherRaoMetric`,
 `quantumPotential_is_fisherRao_lineElement`).
* **§D — the Fubini–Study metric on `T*S`** (`fubiniStudyMetric`, `fubiniStudyMetric_nonneg`).
* **§E — the phase-shift gauge is a Killing flow** (`phaseShift_add` one-parameter group; `phaseShift_born_isometry`
 the Born-rule/Fubini–Study isometry; `edWaveFunction_normSq` the Born rule `|ψ|²=ρ`) — the ray-space translation
 Killing flow, the projective-Hilbert analog of the CDF-translation Killing flow of
 `ProbabilityMetricTranslationKillingFlow`.

The normalization constraint, the phase-shift gauge on `ψ`, the Fisher–Rao / quantum-potential
identity, and the Fubini–Study line element are exact algebra. The full derivation of the metric from the minimal
information-geometry assumptions (Eqs. 26–31), the `A/B` scalar functions, and the ray-distance minimization are
the paper's programme, captured at the metric-density level. No new axioms.

## References

* A. Caticha, arXiv:2107.08502, §§3–4 (Eqs. 20, 24, 26, 32; normalization, phase gauge, Fisher–Rao / Fubini–Study
 metric). Repo dependencies: `EntropicTime.HamiltonKillingComplexStructureSchrodinger`,
 `EntropicTime.EntropicDynamicsCanonicalRepresentation`.

No new axioms.
-/

set_option autoImplicit false

open Physlib.QuantumMechanics.ComplexAction.EntropicTime.EntropicDynamicsWaveFunctionReconstruction
open Physlib.QuantumMechanics.ComplexAction.EntropicTime.EntropicDynamicsCanonicalRepresentation

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.EntropicTime.HamiltonKillingNormalizationInformationMetric

/-! ## §A — the normalization constraint -/

/-- **The normalization constraint** `Ñ = 1 − |ρ|`, `|ρ| = ∑ρⁱ` (Caticha Eq. 20) — the Hamiltonian generator whose
vanishing enforces normalized probabilities. -/
def normalizationConstraint (rhoSum : ℝ) : ℝ := 1 - rhoSum

/-- **[The constraint vanishes iff normalized] `Ñ = 0 ⟺ ∑ρⁱ = 1`.** -/
theorem normalized_iff (rhoSum : ℝ) : normalizationConstraint rhoSum = 0 ↔ rhoSum = 1 := by
  unfold normalizationConstraint
  constructor <;> intro h <;> linarith

/-! ## §B — the phase-shift gauge: states are rays -/

/-- **[The normalization gauge is a phase multiplication] `ψ(Φ + ν) = e^{iν}ψ(Φ)`.** The flow generated by the
normalization constraint `Ñ` shifts all momenta `π → π + ν` (Caticha Eq. 24), which on the wave function
`ψ = √ρ e^{iΦ}` is multiplication by the phase `e^{iν}` — the global gauge symmetry that makes quantum states
**rays** (equivalence classes under phase), not vectors, in the Hilbert space. -/
theorem hamiltonKilling_phaseShift_gauge (ρ Φ ν : ℝ) :
    edWaveFunction ρ (Φ + ν) = Complex.exp ((ν : ℂ) * Complex.I) * edWaveFunction ρ Φ := by
  unfold edWaveFunction
  rw [show ((Φ + ν : ℝ) : ℂ) * Complex.I = (Φ : ℂ) * Complex.I + (ν : ℂ) * Complex.I by
        push_cast; ring, Complex.exp_add]
  ring

/-! ## §C — the Fisher–Rao metric is the quantum potential -/

/-- **The Fisher–Rao information metric** `g = 1/(2ρ)` (Caticha Eq. 26 with `B = 1`) — the intrinsic metric of the
simplex `S` from information geometry, the diagonal component of the Fisher–Rao metric tensor. -/
noncomputable def fisherRaoMetric (ρ : ℝ) : ℝ := 1 / (2 * ρ)

/-- **[The Fisher–Rao line element is the entropic-dynamics quantum potential] `(δρ)²/ρ = 2g(δρ)²`.** The `δρ`
line element of the Fisher–Rao metric is exactly the entropic-dynamics quantum-potential density
`edQuantumPotential 1 ρ (δρ) = (δρ)²/ρ` — the Fisher information — so the information metric of Caticha's
statistical manifold *is* the quantum potential of the entropic-dynamics reconstruction. -/
theorem quantumPotential_is_fisherRao_lineElement (ρ dρ : ℝ) (hρ : ρ ≠ 0) :
    edQuantumPotential 1 ρ dρ = 2 * fisherRaoMetric ρ * dρ ^ 2 := by
  unfold edQuantumPotential fisherRaoMetric
  field_simp

/-! ## §D — the Fubini–Study metric on `T*S` -/

/-- **The Fubini–Study metric induced on the e-phase space `T*S`** `δs² = (1/2ρ)(δρ)² + 2ρ(δπ − ⟨δπ⟩)²`
(Caticha Eq. 32, `B(1) = 1`) — the distance between rays, fully determined by the information geometry of the
simplex, with `⟨δπ⟩ = ∑ρⁱδπ_i` the mean momentum shift (the minimizing gauge `ν = −⟨δπ⟩`). -/
noncomputable def fubiniStudyMetric (ρ dρ dπ meanDπ : ℝ) : ℝ :=
  fisherRaoMetric ρ * dρ ^ 2 + 2 * ρ * (dπ - meanDπ) ^ 2

/-- **[The Fubini–Study metric is non-negative] `δs² ≥ 0`.** For a positive probability the induced ray metric is
a genuine (non-negative) squared distance — a bona-fide Riemannian metric on the space of quantum states. -/
theorem fubiniStudyMetric_nonneg (ρ dρ dπ meanDπ : ℝ) (hρ : 0 < ρ) :
    0 ≤ fubiniStudyMetric ρ dρ dπ meanDπ := by
  unfold fubiniStudyMetric fisherRaoMetric
  positivity

/-! ## §E — the phase-shift gauge is a Killing flow (the ray-space translation isometry) -/

/-- **[The phase gauge is a one-parameter group] `ψ(Φ + (ν₁+ν₂)) = e^{iν₂} ψ(Φ + ν₁)`.** Successive momentum/phase
shifts `π → π + ν` compose additively — the `U(1)` one-parameter group generated by the normalization constraint
`Ñ`. This is the projective-ray-space counterpart of the CDF-translation one-parameter group `cdfTranslate_add`
(`EntropicTime.ProbabilityMetricTranslationKillingFlow`). -/
theorem phaseShift_add (ρ Φ ν₁ ν₂ : ℝ) :
    edWaveFunction ρ (Φ + (ν₁ + ν₂))
      = Complex.exp ((ν₂ : ℂ) * Complex.I) * edWaveFunction ρ (Φ + ν₁) := by
  rw [← add_assoc]
  exact hamiltonKilling_phaseShift_gauge ρ (Φ + ν₁) ν₂

/-- **[The phase gauge is a Born-rule isometry — a Killing flow] `|ψ(Φ+ν)|² = |ψ(Φ)|²`.** The phase shift
`π → π + ν` preserves the modulus `|ψ|²`, hence the Fubini–Study metric (`fubiniStudyMetric`, which depends only on
`ρ, δρ, δπ`): the normalization/phase flow is an **isometry** — a Killing flow of the information metric, the very
property Caticha's Hamilton–Killing construction demands. It is the projective-Hilbert-ray-space analog of the
CDF-translation Killing flow `cramerDistance_translation_invariant` (a translation isometry of the Cramér /
1-Wasserstein probability metric): both are translation Killing flows of a statistical metric. -/
theorem phaseShift_born_isometry (ρ Φ ν : ℝ) :
    Complex.normSq (edWaveFunction ρ (Φ + ν)) = Complex.normSq (edWaveFunction ρ Φ) := by
  rw [hamiltonKilling_phaseShift_gauge, map_mul]
  have h1 : Complex.normSq (Complex.exp ((ν : ℂ) * Complex.I)) = 1 := by
    rw [Complex.normSq_eq_norm_sq, Complex.norm_exp_ofReal_mul_I]; norm_num
  rw [h1, one_mul]

/-- **[The Born rule from the polar form] `|ψ|² = ρ`.** For `ρ ≥ 0` the entropic-dynamics wave function
`ψ = √ρ e^{iΦ}` has modulus-squared equal to the probability `ρ` — the Born rule, phase-invariant
(`phaseShift_born_isometry`), which is why the phase gauge leaves the physical probabilities untouched (states are
rays). -/
theorem edWaveFunction_normSq (ρ Φ : ℝ) (hρ : 0 ≤ ρ) : Complex.normSq (edWaveFunction ρ Φ) = ρ := by
  unfold edWaveFunction
  rw [map_mul, Complex.normSq_ofReal, Real.mul_self_sqrt hρ, Complex.normSq_eq_norm_sq,
    Complex.norm_exp_ofReal_mul_I]
  norm_num

end Physlib.QuantumMechanics.ComplexAction.EntropicTime.HamiltonKillingNormalizationInformationMetric

end
