/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.AlgebraicQFT.SymplecticAdjointHadamard
public import Mathlib.Analysis.SpecialFunctions.Complex.Circle

/-!
# The Weyl/CCR algebra and the Bogoliubov automorphism (Verch 1996, §2.5/§3)

Formalizes the **Weyl (CCR) algebra** of the curved-spacetime Klein–Gordon field of *R. Verch,
arXiv:funct-an/9609004*, §2.5/§3 — the `C*`-algebra `𝒜[S,σ]` generated by unitaries `W(φ)` over the symplectic
Cauchy-data space `(S, σ)`, satisfying the exponentiated canonical commutation relations (Eq. 2.5)

  `W(φ)·W(ψ) = e^{−iσ(φ,ψ)/2}·W(φ+ψ)`.

The temporal evolution of the classical field is by **symplectomorphisms** of `(S,σ)`
(`AlgebraicQFT.SymplecticAdjointHadamard.Symplectomorphism`), and each induces an **automorphism** of the Weyl algebra
`W(φ) ↦ W(Tφ)` — because a symplectomorphism preserves `σ`, it preserves the CCR. The boson/fermion Bogoliubov
transformations (which are symplectomorphisms, `det=1`) thus act as Weyl automorphisms — the quasifree/thermal
Bogoliubov automorphisms of TFD. (The GNS/von Neumann-algebra and Hadamard-state analysis is the
`C*`-functional-analytic layer, out of scope; the CCR-algebra kernel is formalized here.)

* **§A — the symplectic pairing** (`symplecticPairing`, `_antisymm`, `_self`, `_symplecto`). `σ(φ,ψ)=φᵀJψ`
  built on `sympForm`; anti-symmetric; preserved by symplectomorphisms.
* **§B — the Weyl/CCR algebra** (`WeylSystem`, `weyl_inv`, `weyl_commutation`). Eq. 2.5 and its consequences:
  `W(φ)W(−φ)=1`, and the CCR `W(φ)W(ψ) = e^{−iσ(φ,ψ)}W(ψ)W(φ)`.
* **§C — the Bogoliubov automorphism** (`weyl_bogoliubov_automorphism`, `thermoBogoliubov_weyl_automorphism`,
  `fermiBogoliubov_weyl_automorphism`). A symplectomorphism `M` gives `φ ↦ W(Mφ)` a Weyl system; the boson and
  fermion Bogoliubov are such automorphisms.
* **§D — the quasifree state** (`quasifreeWeight`, `quasifreeWeight_zero`). Eq. 2.6 `ω_μ(W(φ)) = e^{−μ(φ,φ)/2}`;
  the state is *pure* iff its polarizator is a complex structure `R²=−1` (`sympForm_sq`).

## References

* R. Verch, arXiv:funct-an/9609004 (the Weyl algebra `𝒜[S,σ]` Eq. 2.5, quasifree states Eq. 2.6, the
  symplectomorphism automorphisms `α_t(W(φ))=W(T_tφ)`).
* Repo dependencies: `AlgebraicQFT.SymplecticAdjointHadamard` (`sympForm`, `Symplectomorphism`,
  `thermoBogoliubov_symplectomorphism`, `fermiBogoliubov_symplectomorphism`, `sympForm_sq` = the pure-state
  `R²=−1`).

No new axioms.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.OperatorAlgebra.WeylCCRSpacetime

open Matrix
open Physlib.QuantumMechanics.ComplexAction.AlgebraicQFT.SymplecticAdjointHadamard
open Physlib.QuantumMechanics.ComplexAction.ThermoFieldDynamics.TFDImaginaryPart
open Physlib.QuantumMechanics.ComplexAction.ThermoFieldDynamics.TFDBogoliubovHopf

/-! ## §A — the symplectic pairing on the Cauchy-data space -/

/-- **The symplectic form** `σ(φ,ψ) = φ·(Jψ)` on the `2`-dim Cauchy-data space, built on `sympForm`. -/
def symplecticPairing (φ ψ : Fin 2 → ℝ) : ℝ := φ ⬝ᵥ (sympForm *ᵥ ψ)

/-- **`σ` is anti-symmetric** `σ(ψ,φ) = −σ(φ,ψ)`. -/
theorem symplecticPairing_antisymm (φ ψ : Fin 2 → ℝ) :
    symplecticPairing ψ φ = -symplecticPairing φ ψ := by
  simp [symplecticPairing, sympForm, mulVec, dotProduct, Fin.sum_univ_two]; ring

/-- **`σ(φ,φ) = 0`** — the symplectic form is alternating. -/
theorem symplecticPairing_self (φ : Fin 2 → ℝ) : symplecticPairing φ φ = 0 := by
  have := symplecticPairing_antisymm φ φ; linarith

/-- **[Verch's symplectomorphisms preserve `σ`] `σ(Mφ,Mψ) = σ(φ,ψ)`** for a symplectomorphism `M`
(`MᵀJM=J`) — the classical temporal evolution preserves the symplectic structure. -/
theorem symplecticPairing_symplecto (M : Matrix (Fin 2) (Fin 2) ℝ) (h : Symplectomorphism M)
    (φ ψ : Fin 2 → ℝ) : symplecticPairing (M *ᵥ φ) (M *ᵥ ψ) = symplecticPairing φ ψ := by
  unfold symplecticPairing Symplectomorphism at *
  rw [mulVec_mulVec, dotProduct_mulVec, dotProduct_mulVec]
  congr 1
  rw [(Matrix.vecMul_transpose M φ).symm, vecMul_vecMul, ← Matrix.mul_assoc, h]

/-! ## §B — the Weyl/CCR algebra (Eq. 2.5) -/

/-- **[Eq. 2.5] A Weyl (CCR) system** over `(S,σ)` in a unital `ℂ`-algebra `A`: unitaries `W(φ)` with
`W(0)=1` and `W(φ)W(ψ) = e^{−iσ(φ,ψ)/2}W(φ+ψ)`. -/
structure WeylSystem {A : Type*} [Ring A] [Algebra ℂ A]
    (σ : (Fin 2 → ℝ) → (Fin 2 → ℝ) → ℝ) where
  /-- The Weyl unitaries. -/
  W : (Fin 2 → ℝ) → A
  /-- `W(0) = 1`. -/
  zero : W 0 = 1
  /-- The Weyl relation (Eq. 2.5). -/
  mul : ∀ φ ψ, W φ * W ψ = Complex.exp (-(Complex.I * (σ φ ψ : ℂ)) / 2) • W (φ + ψ)

variable {A : Type*} [Ring A] [Algebra ℂ A]

/-- **`W(φ)W(−φ) = 1`** — `W(−φ)` is the inverse (the Weyl unitaries are invertible). -/
theorem weyl_inv (w : WeylSystem (A := A) symplecticPairing) (φ : Fin 2 → ℝ) :
    w.W φ * w.W (-φ) = 1 := by
  rw [w.mul, add_neg_cancel, w.zero]
  have hσ : symplecticPairing φ (-φ) = 0 := by
    unfold symplecticPairing
    rw [Matrix.mulVec_neg, dotProduct_neg]
    have h0 : symplecticPairing φ φ = 0 := symplecticPairing_self φ
    unfold symplecticPairing at h0; linarith
  rw [hσ]; simp

/-- **[CCR] The Weyl commutation relation** `W(φ)W(ψ) = e^{−iσ(φ,ψ)}W(ψ)W(φ)` — the exponentiated canonical
commutation relations, from the Weyl product law and the anti-symmetry of `σ`. -/
theorem weyl_commutation (w : WeylSystem (A := A) symplecticPairing) (φ ψ : Fin 2 → ℝ) :
    w.W φ * w.W ψ
      = Complex.exp (-(Complex.I * (symplecticPairing φ ψ : ℂ))) • (w.W ψ * w.W φ) := by
  rw [w.mul φ ψ, w.mul ψ φ, smul_smul, add_comm ψ φ]
  congr 1
  rw [← Complex.exp_add, symplecticPairing_antisymm]
  push_cast; ring

/-! ## §C — the Bogoliubov automorphism -/

/-- **[Verch's symplectomorphism automorphism] A symplectomorphism induces a Weyl automorphism.** For `M` a
symplectomorphism, the shifted map `φ ↦ W(Mφ)` satisfies the same Weyl relation — `M` preserves `σ`, hence the
CCR. This is the quasifree/Bogoliubov automorphism `α(W(φ)) = W(Mφ)` of `𝒜[S,σ]`. -/
theorem weyl_bogoliubov_automorphism (w : WeylSystem (A := A) symplecticPairing)
    (M : Matrix (Fin 2) (Fin 2) ℝ) (hM : Symplectomorphism M) (φ ψ : Fin 2 → ℝ) :
    w.W (M *ᵥ φ) * w.W (M *ᵥ ψ)
      = Complex.exp (-(Complex.I * (symplecticPairing φ ψ : ℂ)) / 2) • w.W (M *ᵥ (φ + ψ)) := by
  rw [w.mul, symplecticPairing_symplecto M hM, ← Matrix.mulVec_add]

/-- **The boson Bogoliubov is a Weyl automorphism** — `U_B(θ)` (a symplectomorphism) implements the thermal
automorphism `W(φ) ↦ W(U_B(θ)φ)`. -/
theorem thermoBogoliubov_weyl_automorphism (w : WeylSystem (A := A) symplecticPairing) (θ : ℝ)
    (φ ψ : Fin 2 → ℝ) :
    w.W (thermoBogoliubov θ *ᵥ φ) * w.W (thermoBogoliubov θ *ᵥ ψ)
      = Complex.exp (-(Complex.I * (symplecticPairing φ ψ : ℂ)) / 2)
          • w.W (thermoBogoliubov θ *ᵥ (φ + ψ)) :=
  weyl_bogoliubov_automorphism w _ (thermoBogoliubov_symplectomorphism θ) φ ψ

/-- **The fermion Bogoliubov is a Weyl automorphism** — `R(θ)` implements `W(φ) ↦ W(R(θ)φ)`. -/
theorem fermiBogoliubov_weyl_automorphism (w : WeylSystem (A := A) symplecticPairing) (θ : ℝ)
    (φ ψ : Fin 2 → ℝ) :
    w.W (fermiBogoliubov θ *ᵥ φ) * w.W (fermiBogoliubov θ *ᵥ ψ)
      = Complex.exp (-(Complex.I * (symplecticPairing φ ψ : ℂ)) / 2)
          • w.W (fermiBogoliubov θ *ᵥ (φ + ψ)) :=
  weyl_bogoliubov_automorphism w _ (fermiBogoliubov_symplectomorphism θ) φ ψ

/-! ## §D — the quasifree state (Eq. 2.6) -/

/-- **[Eq. 2.6] The quasifree state weight** `ω_μ(W(φ)) = e^{−μ(φ,φ)/2}` — the Gaussian functional on the Weyl
algebra determined by a dominating scalar product `μ`. The state is *pure* iff `μ`'s polarizator is a complex
structure `R²=−1` (`AlgebraicQFT.SymplecticAdjointHadamard.sympForm_sq`). -/
noncomputable def quasifreeWeight (μ : (Fin 2 → ℝ) → (Fin 2 → ℝ) → ℝ) (φ : Fin 2 → ℝ) : ℝ :=
  Real.exp (-(μ φ φ) / 2)

/-- **The quasifree state is normalized** `ω_μ(W(0)) = 1` when `μ(0,0)=0`. -/
theorem quasifreeWeight_zero (μ : (Fin 2 → ℝ) → (Fin 2 → ℝ) → ℝ) (h : μ 0 0 = 0) :
    quasifreeWeight μ 0 = 1 := by
  rw [quasifreeWeight, h]; simp

end Physlib.QuantumMechanics.ComplexAction.OperatorAlgebra.WeylCCRSpacetime

end
