/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.ChernSimons.BraidRelationTrefoilTorus
public import Physlib.QuantumMechanics.ComplexAction.Hopf.ChargeConjugationRibbonTwist
public import Mathlib.LinearAlgebra.Matrix.Permutation
public import Mathlib.RingTheory.Coalgebra.Convolution

/-!
# Yang-Baxter algebras as convolution algebras

This file formalizes the algebraic core used in Gorbounov--Korff--Stroppel,
*Yang-Baxter algebras as convolution algebras: the Grassmannian case*
(arXiv:1802.09497).  The paper's full Grassmannian construction uses equivariant
cohomology, Chern classes, fixed-point localization, and push-pull correspondences.
Those geometric ingredients are not formalized here.  What is formalized is the
checked algebraic layer that the geometric construction lands in:

* Mathlib's convolution product on `WithConv (C ->ₗ[R] A)` for a coalgebra `C`
  and algebra `A`;
* the fact that a generated Yang-Baxter operator algebra is a genuine subsemiring
  of that convolution algebra and is closed under the half/full braid twists;
* the braid-form Yang-Baxter relation inside the convolution algebra;
* evaluation of convolution products on group-like elements, linked to the
  existing Hopf charge-state formalization;
* the exact sixteen five-vertex RTT relations from Proposition 2.1 as a Lean
  predicate, with the three geometric relations of Proposition 4.7 extracted
  from them;
* the operator-generation layer of Definition 4.3: `B = bA`, `C = Ac`,
  `D = bAc` and the primed version generate subalgebras contained in the basic
  convolution algebra generated by `A`, `b`, and `c`;
* a concrete symmetric-group braid solution represented by permutation matrices
  and lifted into the scalar-coalgebra convolution algebra.

This gives the repo a reusable formal target for later Grassmannian fixed-point
operators: once the geometric push-pull operators are constructed as linear maps
`C ->ₗ[R] A`, their Yang-Baxter closure and braid consequences can use the
lemmas in this file.
-/

set_option autoImplicit false

open Coalgebra WithConv
open scoped RingTheory.LinearMap

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.OperatorAlgebra.YangBaxterConvolutionAlgebra

open Physlib.QuantumMechanics.ComplexAction.ChernSimons.BraidRelationTrefoilTorus
open Physlib.QuantumMechanics.ComplexAction.Hopf.ChargeConjugationRibbonTwist

variable {R A C : Type*}

/-! ## The five-vertex RTT relation package from Proposition 2.1 -/

section RTTRelations

variable {S : Type*} [Ring S]

/-- The sixteen relations obtained from the five-vertex RTT equation in Proposition 2.1.

Here `A₁` means `A(x₁)`, `A₂` means `A(x₂)`, and similarly for `B,C,D`.  The spectral
parameters `x₁,x₂` are represented as elements of the same (possibly noncommutative) ring,
matching the paper's convention that the displayed equations are identities in the operator
algebra with central polynomial parameters. -/
structure FiveVertexRTTRelations
    (x₁ x₂ A₁ A₂ B₁ B₂ C₁ C₂ D₁ D₂ : S) : Prop where
  A_mul_A : A₁ * A₂ = A₂ * A₁
  B_mul_B : B₁ * B₂ = B₂ * B₁
  B₁_mul_A₂ : B₁ * A₂ = B₂ * A₁
  A₁_mul_C₂ : A₁ * C₂ = A₂ * C₁
  C_mul_C : C₁ * C₂ = C₂ * C₁
  D_mul_D : D₁ * D₂ = D₂ * D₁
  B₂_mul_D₁ : B₂ * D₁ = B₁ * D₂
  D₂_mul_C₁ : D₂ * C₁ = D₁ * C₂
  B₁_mul_C₂ : B₁ * C₂ = B₂ * C₁
  B₁_mul_A₂_duplicate : B₁ * A₂ = B₂ * A₁
  A₂B₁_sub_A₁B₂ : A₂ * B₁ - A₁ * B₂ = (x₂ - x₁) * (B₂ * A₁)
  C₂A₁_sub_C₁A₂ : C₂ * A₁ - C₁ * A₂ = (x₁ - x₂) * (A₁ * C₂)
  A₁D₂_sub_A₂D₁ : A₁ * D₂ - A₂ * D₁ = (x₁ - x₂) * (B₂ * C₁)
  D₂B₁_sub_D₁B₂ : D₂ * B₁ - D₁ * B₂ = (x₁ - x₂) * (B₁ * D₂)
  C₁D₂_sub_C₂D₁ : C₁ * D₂ - C₂ * D₁ = (x₁ - x₂) * (D₂ * C₁)
  C₂B₁_sub_C₁B₂ :
    C₂ * B₁ - C₁ * B₂ = (x₁ - x₂) * (A₁ * D₂ - D₂ * A₁)

/-- The three geometric relations checked in Proposition 4.7. -/
structure GeometricThreeRelations
    (x₁ x₂ A₁ A₂ B₁ B₂ C₁ C₂ D₁ D₂ : S) : Prop where
  C₂B₁_sub_C₁B₂ :
    C₂ * B₁ - C₁ * B₂ = (x₁ - x₂) * (A₁ * D₂ - D₂ * A₁)
  D₁_mul_C₂ : D₁ * C₂ = D₂ * C₁
  C₁D₂_sub_C₂D₁ : C₁ * D₂ - C₂ * D₁ = (x₁ - x₂) * (D₂ * C₁)

/-- The full RTT relation package contains the three geometric relations used in the convolution proof. -/
theorem geometricThreeRelations_of_fiveVertexRTT
    {x₁ x₂ A₁ A₂ B₁ B₂ C₁ C₂ D₁ D₂ : S}
    (h : FiveVertexRTTRelations x₁ x₂ A₁ A₂ B₁ B₂ C₁ C₂ D₁ D₂) :
    GeometricThreeRelations x₁ x₂ A₁ A₂ B₁ B₂ C₁ C₂ D₁ D₂ where
  C₂B₁_sub_C₁B₂ := h.C₂B₁_sub_C₁B₂
  D₁_mul_C₂ := h.D₂_mul_C₁.symm
  C₁D₂_sub_C₂D₁ := h.C₁D₂_sub_C₂D₁

end RTTRelations

section GeneratedConvolutionAlgebra

variable [CommSemiring R] [Semiring A] [Algebra R A]
variable [AddCommMonoid C] [Module R C] [Coalgebra R C]

/-- The convolution algebra of linear maps from a coalgebra `C` to an algebra `A`. -/
abbrev ConvolutionAlgebra := WithConv (C →ₗ[R] A)

/-- The Yang-Baxter/convolution algebra generated by a chosen family of convolution operators. -/
noncomputable def generatedConvolutionAlgebra
    (S : Set (ConvolutionAlgebra (R := R) (A := A) (C := C))) :
    Subsemiring (ConvolutionAlgebra (R := R) (A := A) (C := C)) :=
  Subsemiring.closure S

/-- A declared generator belongs to the generated convolution algebra. -/
theorem generator_mem_generatedConvolutionAlgebra
    {S : Set (ConvolutionAlgebra (R := R) (A := A) (C := C))}
    {T : ConvolutionAlgebra (R := R) (A := A) (C := C)} (hT : T ∈ S) :
    T ∈ generatedConvolutionAlgebra (R := R) (A := A) (C := C) S :=
  Subsemiring.subset_closure hT

/-- The generated convolution algebra is closed under the braid half-twist `R₁R₂R₁`. -/
theorem halfTwist_mem_generatedConvolutionAlgebra
    {S : Set (ConvolutionAlgebra (R := R) (A := A) (C := C))}
    {R₁ R₂ : ConvolutionAlgebra (R := R) (A := A) (C := C)}
    (h₁ : R₁ ∈ generatedConvolutionAlgebra (R := R) (A := A) (C := C) S)
    (h₂ : R₂ ∈ generatedConvolutionAlgebra (R := R) (A := A) (C := C) S) :
    halfTwist R₁ R₂ ∈ generatedConvolutionAlgebra (R := R) (A := A) (C := C) S :=
  (generatedConvolutionAlgebra (R := R) (A := A) (C := C) S).mul_mem
    ((generatedConvolutionAlgebra (R := R) (A := A) (C := C) S).mul_mem h₁ h₂) h₁

/-- The generated convolution algebra is closed under the braid full-twist `(R₁R₂)^3`. -/
theorem fullTwist_mem_generatedConvolutionAlgebra
    {S : Set (ConvolutionAlgebra (R := R) (A := A) (C := C))}
    {R₁ R₂ : ConvolutionAlgebra (R := R) (A := A) (C := C)}
    (h₁ : R₁ ∈ generatedConvolutionAlgebra (R := R) (A := A) (C := C) S)
    (h₂ : R₂ ∈ generatedConvolutionAlgebra (R := R) (A := A) (C := C) S) :
    fullTwist R₁ R₂ ∈ generatedConvolutionAlgebra (R := R) (A := A) (C := C) S :=
  (generatedConvolutionAlgebra (R := R) (A := A) (C := C) S).pow_mem
    ((generatedConvolutionAlgebra (R := R) (A := A) (C := C) S).mul_mem h₁ h₂) 3

/-! ## Definition 4.3 as operator generation inside a convolution algebra -/

section GeometricGenerators

variable {ι : Type*}

/-- The unprimed operator `B = bA` from Definition 4.3. -/
noncomputable def unprimedB
    (Aop bop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) (i : ι) :
    ConvolutionAlgebra (R := R) (A := A) (C := C) :=
  bop i * Aop i

/-- The unprimed operator `C = Ac` from Definition 4.3. -/
noncomputable def unprimedC
    (Aop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) (i : ι) :
    ConvolutionAlgebra (R := R) (A := A) (C := C) :=
  Aop i * cop i

/-- The unprimed operator `D = bAc` from Definition 4.3. -/
noncomputable def unprimedD
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) (i : ι) :
    ConvolutionAlgebra (R := R) (A := A) (C := C) :=
  bop i * Aop i * cop i

/-- The primed operator `B' = A'b` from Definition 4.3. -/
noncomputable def primedB
    (Aop bop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) (i : ι) :
    ConvolutionAlgebra (R := R) (A := A) (C := C) :=
  Aop i * bop i

/-- The primed operator `C' = cA'` from Definition 4.3. -/
noncomputable def primedC
    (Aop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) (i : ι) :
    ConvolutionAlgebra (R := R) (A := A) (C := C) :=
  cop i * Aop i

/-- The primed operator `D' = cA'b` from Definition 4.3. -/
noncomputable def primedD
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) (i : ι) :
    ConvolutionAlgebra (R := R) (A := A) (C := C) :=
  cop i * Aop i * bop i

theorem unprimedD_eq_B_mul_c
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) (i : ι) :
    unprimedD Aop bop cop i = unprimedB Aop bop i * cop i :=
  rfl

theorem unprimedD_eq_b_mul_C
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) (i : ι) :
    unprimedD Aop bop cop i = bop i * unprimedC Aop cop i := by
  simp [unprimedD, unprimedC, mul_assoc]

theorem primedD_eq_C_mul_b
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) (i : ι) :
    primedD Aop bop cop i = primedC Aop cop i * bop i :=
  rfl

theorem primedD_eq_c_mul_B
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) (i : ι) :
    primedD Aop bop cop i = cop i * primedB Aop bop i := by
  simp [primedD, primedB, mul_assoc]

/-- The basic convolution generators: diagonal/Chern operators `A`, and push-pull operators `b,c`. -/
def basicGeometricGenerators
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    Set (ConvolutionAlgebra (R := R) (A := A) (C := C)) :=
  fun T => ∃ i, T = Aop i ∨ T = bop i ∨ T = cop i

/-- The unprimed Yang-Baxter generators `A,B,C,D` from Definition 4.3. -/
def unprimedYangBaxterGenerators
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    Set (ConvolutionAlgebra (R := R) (A := A) (C := C)) :=
  fun T => ∃ i,
    T = Aop i ∨ T = unprimedB Aop bop i ∨
      T = unprimedC Aop cop i ∨ T = unprimedD Aop bop cop i

/-- The primed Yang-Baxter generators `A',B',C',D'` from Definition 4.3. -/
def primedYangBaxterGenerators
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    Set (ConvolutionAlgebra (R := R) (A := A) (C := C)) :=
  fun T => ∃ i,
    T = Aop i ∨ T = primedB Aop bop i ∨
      T = primedC Aop cop i ∨ T = primedD Aop bop cop i

/-- Every unprimed generator lies in the convolution algebra generated by `A,b,c`. -/
theorem unprimedYangBaxterGenerators_subset_basicClosure
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    unprimedYangBaxterGenerators (R := R) (A := A) (C := C) Aop bop cop ⊆
      generatedConvolutionAlgebra (R := R) (A := A) (C := C)
        (basicGeometricGenerators (R := R) (A := A) (C := C) Aop bop cop) := by
  intro T hT
  let S := generatedConvolutionAlgebra (R := R) (A := A) (C := C)
    (basicGeometricGenerators (R := R) (A := A) (C := C) Aop bop cop)
  rcases hT with ⟨i, hA | hB | hC | hD⟩
  · rw [hA]
    exact Subsemiring.subset_closure ⟨i, Or.inl rfl⟩
  · rw [hB, unprimedB]
    exact S.mul_mem
      (Subsemiring.subset_closure ⟨i, Or.inr (Or.inl rfl)⟩)
      (Subsemiring.subset_closure ⟨i, Or.inl rfl⟩)
  · rw [hC, unprimedC]
    exact S.mul_mem
      (Subsemiring.subset_closure ⟨i, Or.inl rfl⟩)
      (Subsemiring.subset_closure ⟨i, Or.inr (Or.inr rfl)⟩)
  · rw [hD, unprimedD]
    exact S.mul_mem
      (S.mul_mem
        (Subsemiring.subset_closure ⟨i, Or.inr (Or.inl rfl)⟩)
        (Subsemiring.subset_closure ⟨i, Or.inl rfl⟩))
      (Subsemiring.subset_closure ⟨i, Or.inr (Or.inr rfl)⟩)

/-- The unprimed geometric Yang-Baxter algebra is a subalgebra of the basic convolution algebra. -/
theorem unprimedYangBaxterAlgebra_le_basicConvolutionAlgebra
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    Subsemiring.closure
      (unprimedYangBaxterGenerators (R := R) (A := A) (C := C) Aop bop cop) ≤
      generatedConvolutionAlgebra (R := R) (A := A) (C := C)
        (basicGeometricGenerators (R := R) (A := A) (C := C) Aop bop cop) :=
  Subsemiring.closure_le.2
    (unprimedYangBaxterGenerators_subset_basicClosure (R := R) (A := A) (C := C) Aop bop cop)

/-- Every primed generator lies in the convolution algebra generated by `A',b,c`. -/
theorem primedYangBaxterGenerators_subset_basicClosure
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    primedYangBaxterGenerators (R := R) (A := A) (C := C) Aop bop cop ⊆
      generatedConvolutionAlgebra (R := R) (A := A) (C := C)
        (basicGeometricGenerators (R := R) (A := A) (C := C) Aop bop cop) := by
  intro T hT
  let S := generatedConvolutionAlgebra (R := R) (A := A) (C := C)
    (basicGeometricGenerators (R := R) (A := A) (C := C) Aop bop cop)
  rcases hT with ⟨i, hA | hB | hC | hD⟩
  · rw [hA]
    exact Subsemiring.subset_closure ⟨i, Or.inl rfl⟩
  · rw [hB, primedB]
    exact S.mul_mem
      (Subsemiring.subset_closure ⟨i, Or.inl rfl⟩)
      (Subsemiring.subset_closure ⟨i, Or.inr (Or.inl rfl)⟩)
  · rw [hC, primedC]
    exact S.mul_mem
      (Subsemiring.subset_closure ⟨i, Or.inr (Or.inr rfl)⟩)
      (Subsemiring.subset_closure ⟨i, Or.inl rfl⟩)
  · rw [hD, primedD]
    exact S.mul_mem
      (S.mul_mem
        (Subsemiring.subset_closure ⟨i, Or.inr (Or.inr rfl)⟩)
        (Subsemiring.subset_closure ⟨i, Or.inl rfl⟩))
      (Subsemiring.subset_closure ⟨i, Or.inr (Or.inl rfl)⟩)

/-- The primed geometric Yang-Baxter algebra is a subalgebra of the basic convolution algebra. -/
theorem primedYangBaxterAlgebra_le_basicConvolutionAlgebra
    (Aop bop cop : ι → ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    Subsemiring.closure
      (primedYangBaxterGenerators (R := R) (A := A) (C := C) Aop bop cop) ≤
      generatedConvolutionAlgebra (R := R) (A := A) (C := C)
        (basicGeometricGenerators (R := R) (A := A) (C := C) Aop bop cop) :=
  Subsemiring.closure_le.2
    (primedYangBaxterGenerators_subset_basicClosure (R := R) (A := A) (C := C) Aop bop cop)

end GeometricGenerators

/-! ## Convolution and braid-form Yang-Baxter -/

/-- The convolution product, in Mathlib's `WithConv` structure. -/
theorem convolution_mul_apply
    (F G : ConvolutionAlgebra (R := R) (A := A) (C := C)) (c : C) :
    (F * G) c =
      LinearMap.mul' R A (TensorProduct.map F.ofConv G.ofConv (Coalgebra.comul c)) :=
  rfl

/-- The convolution unit, in Mathlib's `WithConv` structure. -/
theorem convolution_one_apply (c : C) :
    (1 : ConvolutionAlgebra (R := R) (A := A) (C := C)) c =
      algebraMap R A (Coalgebra.counit (R := R) c) :=
  rfl

/-- Coassociativity of the coalgebra and associativity of `A` give associativity of convolution. -/
theorem convolution_assoc
    (F G H : ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    (F * G) * H = F * (G * H) :=
  mul_assoc F G H

/-- The braid-form Yang-Baxter equation can be read directly in the convolution monoid. -/
theorem convolution_yangBaxter_iff
    (R₁ R₂ : ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    YangBaxter R₁ R₂ ↔ R₁ * R₂ * R₁ = R₂ * R₁ * R₂ :=
  Iff.rfl

/-- Pointwise form of the convolution Yang-Baxter relation. -/
theorem convolution_yangBaxter_iff_apply
    (R₁ R₂ : ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    YangBaxter R₁ R₂ ↔
      ∀ c : C, (R₁ * R₂ * R₁) c = (R₂ * R₁ * R₂) c := by
  constructor
  · intro h c
    rw [h]
  · intro h
    unfold YangBaxter
    apply WithConv.ext
    ext c
    exact h c

/-- A convolution Yang-Baxter solution has equal triple products after evaluation at any coalgebra element. -/
theorem convolution_yangBaxter_apply
    {R₁ R₂ : ConvolutionAlgebra (R := R) (A := A) (C := C)}
    (h : YangBaxter R₁ R₂) (c : C) :
    (R₁ * R₂ * R₁) c = (R₂ * R₁ * R₂) c :=
  (convolution_yangBaxter_iff_apply (R := R) (A := A) (C := C) R₁ R₂).mp h c

/-- The full braid twist of a convolution Yang-Baxter solution commutes with the first generator. -/
theorem convolution_fullTwist_central_left
    {R₁ R₂ : ConvolutionAlgebra (R := R) (A := A) (C := C)}
    (h : YangBaxter R₁ R₂) :
    fullTwist R₁ R₂ * R₁ = R₁ * fullTwist R₁ R₂ :=
  fullTwist_central_a h

/-- The full braid twist of a convolution Yang-Baxter solution commutes with the second generator. -/
theorem convolution_fullTwist_central_right
    {R₁ R₂ : ConvolutionAlgebra (R := R) (A := A) (C := C)}
    (h : YangBaxter R₁ R₂) :
    fullTwist R₁ R₂ * R₂ = R₂ * fullTwist R₁ R₂ :=
  fullTwist_central_b h

/-! ## Group-like evaluation -/

/-- On a group-like coalgebra element, convolution is ordinary multiplication of evaluations. -/
theorem groupLike_convolution_apply {c : C} (hc : IsGroupLikeElem R c)
    (F G : ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    (F * G) c = F c * G c := by
  rw [convolution_mul_apply, hc.comul_eq_tmul_self, TensorProduct.map_tmul,
    LinearMap.mul'_apply]

/-- Triple convolution at a group-like element is the corresponding triple product in the target algebra. -/
theorem groupLike_triple_convolution_apply {c : C} (hc : IsGroupLikeElem R c)
    (F G H : ConvolutionAlgebra (R := R) (A := A) (C := C)) :
    (F * G * H) c = (F c * G c) * H c := by
  rw [groupLike_convolution_apply (R := R) (A := A) (C := C) hc (F * G) H,
    groupLike_convolution_apply (R := R) (A := A) (C := C) hc F G]

/-- At a group-like element, the convolution Yang-Baxter relation becomes a target-algebra braid relation. -/
theorem groupLike_yangBaxter_apply
    {R₁ R₂ : ConvolutionAlgebra (R := R) (A := A) (C := C)}
    (h : YangBaxter R₁ R₂) {c : C} (hc : IsGroupLikeElem R c) :
    (R₁ c * R₂ c) * R₁ c = (R₂ c * R₁ c) * R₂ c := by
  simpa [groupLike_triple_convolution_apply (R := R) (A := A) (C := C) hc]
    using convolution_yangBaxter_apply (R := R) (A := A) (C := C) h c

end GeneratedConvolutionAlgebra

/-! ## Link to the existing Hopf charge-state file -/

open scoped MonoidAlgebra

/-- The concrete charge Hopf algebra already used elsewhere in the repo. -/
abbrev ChargeHopfAlgebra := MonoidAlgebra ℂ (Multiplicative ℤ)

/-- On the group-like charge states `t^q`, convolution evaluates as ordinary multiplication. -/
theorem chargeState_convolution_apply (q : ℤ)
    (F G : ConvolutionAlgebra (R := ℂ) (A := ChargeHopfAlgebra) (C := ChargeHopfAlgebra)) :
    (F * G) (chargeState q) = F (chargeState q) * G (chargeState q) :=
  groupLike_convolution_apply (R := ℂ) (A := ChargeHopfAlgebra) (C := ChargeHopfAlgebra)
    (chargeState_isGroupLike q) F G

/-- A convolution Yang-Baxter solution restricts to an ordinary braid relation on every charge state. -/
theorem chargeState_yangBaxter_evaluation
    {R₁ R₂ : ConvolutionAlgebra (R := ℂ) (A := ChargeHopfAlgebra) (C := ChargeHopfAlgebra)}
    (h : YangBaxter R₁ R₂) (q : ℤ) :
    (R₁ (chargeState q) * R₂ (chargeState q)) * R₁ (chargeState q) =
      (R₂ (chargeState q) * R₁ (chargeState q)) * R₂ (chargeState q) :=
  groupLike_yangBaxter_apply (R := ℂ) (A := ChargeHopfAlgebra) (C := ChargeHopfAlgebra) h
    (chargeState_isGroupLike q)

/-! ## A concrete symmetric braid solution lifted to a scalar convolution algebra -/

section ScalarConvolution

variable {K B : Type*} [CommSemiring K] [Semiring B] [Algebra K B]

/-- Embed an algebra element as a linear map from the scalar coalgebra and then use convolution. -/
def scalarConvolutionMap (b : B) : ConvolutionAlgebra (R := K) (A := B) (C := K) :=
  WithConv.toConv (LinearMap.toSpanSingleton K B b)

/-- Scalar-coalgebra convolution of embedded elements is ordinary multiplication. -/
@[simp]
theorem scalarConvolutionMap_mul (b₁ b₂ : B) :
    scalarConvolutionMap (K := K) b₁ * scalarConvolutionMap (K := K) b₂ =
      scalarConvolutionMap (K := K) (b₁ * b₂) :=
  LinearMap.toSpanSingleton_convMul_toSpanSingleton b₁ b₂

/-- Any target-algebra braid solution lifts to a scalar-coalgebra convolution braid solution. -/
theorem scalarConvolutionMap_yangBaxter {b₁ b₂ : B} (h : YangBaxter b₁ b₂) :
    YangBaxter (scalarConvolutionMap (K := K) b₁) (scalarConvolutionMap (K := K) b₂) := by
  unfold YangBaxter
  rw [scalarConvolutionMap_mul, scalarConvolutionMap_mul, scalarConvolutionMap_mul,
    scalarConvolutionMap_mul, h]

end ScalarConvolution

/-- The first adjacent transposition of `S₃`, represented as a permutation matrix. -/
noncomputable def symmetricMatrixBraid1 : Matrix (Fin 3) (Fin 3) ℂ :=
  Matrix.permMatrixHom (R := ℂ) (Equiv.swap (0 : Fin 3) 1)

/-- The second adjacent transposition of `S₃`, represented as a permutation matrix. -/
noncomputable def symmetricMatrixBraid2 : Matrix (Fin 3) (Fin 3) ℂ :=
  Matrix.permMatrixHom (R := ℂ) (Equiv.swap 1 2)

/-- The symmetric braid solution persists under the permutation-matrix representation. -/
theorem symmetric_permutation_matrix_yangBaxter :
    YangBaxter symmetricMatrixBraid1 symmetricMatrixBraid2 := by
  exact
    (show YangBaxter
        (Matrix.permMatrixHom (R := ℂ) (Equiv.swap (0 : Fin 3) 1))
        (Matrix.permMatrixHom (R := ℂ) (Equiv.swap 1 2)) from
      by
        unfold YangBaxter
        simpa only [map_mul] using
          congrArg (Matrix.permMatrixHom (R := ℂ)) symmetric_braid_relation)

/-- The same symmetric braid solution, now as an element of a convolution algebra. -/
theorem symmetric_permutation_matrix_scalar_convolution_yangBaxter :
    YangBaxter
      (scalarConvolutionMap (K := ℂ) symmetricMatrixBraid1)
      (scalarConvolutionMap (K := ℂ) symmetricMatrixBraid2) :=
  scalarConvolutionMap_yangBaxter symmetric_permutation_matrix_yangBaxter

end Physlib.QuantumMechanics.ComplexAction.OperatorAlgebra.YangBaxterConvolutionAlgebra

end
