/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Mathlib.Analysis.InnerProductSpace.LinearMap
public import Physlib.QuantumMechanics.ComplexAction.BoseFermiOperatorAlgebra.BoseBilinearRealization

/-!
# The Bogoliubov *-automorphism of the smeared CAR algebra over a continuum

`Bogoliubov.ContinuumCAR` settled the **one-particle** criterion: the Nambu Bogoliubov map is unitary on the
continuum one-particle space `H = L²(ℝ³)` iff `u² + v² = 1`, which is the condition for it to be a *canonical*
(CAR-preserving) transformation. This file takes the **next layer**: the canonical anticommutation relations
on the `*`-algebra **generators** `B(f)` themselves, and the Bogoliubov transformation as a
**`*`-automorphism** of the CAR algebra that preserves them.

For a continuum one-particle Hilbert space `K` (instantiable by `L²(ℝ³)`, or by the doubled Nambu space
`H ⊕ H̄` of particle ⊕ antiparticle), the **smeared field** is the (antilinear) creation/annihilation map
`B : K → A` into a `*`-algebra `A`, with the **canonical anticommutation relations** (`IsCAR`)

 `{B(f), B(g)*} = B(f) B(g)* + B(g)* B(f) = ⟨f, g⟩·1`, `{B(f), B(g)} = 0`.

This is the rigorous, distribution-free form of `ψ(x) = ∫d³k [aₖ uₖ e^{−ikx} + b†ₖ vₖ e^{ikx}]`: the field
smeared against a test function `f ∈ K` is `B(f)`, and the continuum `δ³(k − k')` is the inner product
`⟨f, g⟩` on `K`.

**The Bogoliubov automorphism.** A Bogoliubov transformation is a **unitary** `U` on the one-particle space
`K` (when `K = H ⊕ H̄` this is the full particle/antiparticle mixing `aₖ uₖ + b†ₖ vₖ` of the field above). It
acts on the generators by `B ↦ B ∘ U`. The main result is that this **preserves the CAR**:

 `IsCAR B → IsCAR (B ∘ U)` (`bogoliubov_preserves_CAR`),

because `⟨Uf, Ug⟩ = ⟨f, g⟩` (`U` isometric). So `B ↦ B ∘ U` includes the defining relations of the CAR algebra
to themselves, hence extends to a `*`-automorphism of the `*`-algebra generated by the smeared field — the
Bogoliubov automorphism, now over the genuine (continuum) one-particle Hilbert space.

**Non-vacuity.** The CAR is realizable: the single-mode field `B(c) = c̄ · f` built from the concrete fermion
mode `f = boseBilinear` of `BoseFermiOperatorAlgebra.BoseBilinearRealization` satisfies `IsCAR` over `K = ℂ`
(`caroneMode_isCAR`), so `bogoliubov_preserves_CAR` is not a vacuous implication.

**scope (still the frontier).** This is the `*`-**algebra** level: the CAR relations on generators and
their Bogoliubov-invariance. Still unbuilt (no Mathlib CAR-`C*`-algebra / Fock functor): the `C*`-norm and
completion, the Fock/GNS representation `K ↦ Λ(K)`, and the **Shale–Stinespring** unitary-implementability
criterion (the off-diagonal block Hilbert–Schmidt). So the operator-algebra layer over a continuum remains
the open problem; this supplies its exact algebraic skeleton.

* **§A — the smeared CAR and its Bogoliubov invariance** (`IsCAR`, `bogoliubov_preserves_CAR`).
* **§B — a concrete realization** (`caroneMode`, `caroneMode_isCAR`).

## References

* The self-dual CAR algebra and Bogoliubov automorphisms (Araki; Shale–Stinespring). This development:
 `Bogoliubov.ContinuumCAR` (one-particle criterion), `Bogoliubov.FermionicBogoliubovCAR`,
 `BoseFermiOperatorAlgebra.BoseBilinearRealization` (`boseBilinear`).

No new axioms.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.Bogoliubov.CARAlgebraAutomorphism

open Physlib.QuantumMechanics.ComplexAction.BoseFermiOperatorAlgebra.BoseBilinearRealization

/-! ## §A — the smeared CAR and its Bogoliubov invariance -/

variable {K : Type*} [NormedAddCommGroup K] [InnerProductSpace ℂ K]
  {A : Type*} [Ring A] [StarRing A] [Module ℂ A]

/-- **The canonical anticommutation relations for a smeared field** `B : K → A`:
`{B(f), B(g)*} = ⟨f, g⟩·1` and `{B(f), B(g)} = 0`. The field smeared against a test function `f ∈ K` is
`B(f)`; the continuum `δ³(k − k')` is the inner product on `K = L²(ℝ³)`. -/
def IsCAR (B : K → A) : Prop :=
  (∀ f g, B f * star (B g) + star (B g) * B f = inner ℂ f g • (1 : A))
    ∧ (∀ f g, B f * B g + B g * B f = 0)

/-- **[The Bogoliubov transformation preserves the CAR] `IsCAR B → IsCAR (B ∘ U)`.** A unitary `U` on the
continuum one-particle space `K` includes the smeared field `B` to `B ∘ U`, and the canonical anticommutation
relations are preserved because `⟨Uf, Ug⟩ = ⟨f, g⟩`. Hence `B ↦ B ∘ U` extends to a `*`-automorphism of the
CAR algebra — the Bogoliubov automorphism over the continuum. -/
theorem bogoliubov_preserves_CAR {B : K → A} (hB : IsCAR B) (U : K ≃ₗᵢ[ℂ] K) :
    IsCAR (fun f => B (U f)) := by
  refine ⟨fun f g => ?_, fun f g => ?_⟩
  · rw [hB.1 (U f) (U g), U.inner_map_map]
  · exact hB.2 (U f) (U g)

/-! ## §B — a concrete realization -/

/-- **The single-mode smeared field** `B(c) = c̄ · f`, built from the concrete fermion mode `f = boseBilinear`
of `BoseFermiOperatorAlgebra.BoseBilinearRealization`. Antilinear in the test scalar `c ∈ K = ℂ`. -/
noncomputable def caroneMode (c : ℂ) : Matrix (Fin 2) (Fin 2) ℂ := star c • boseBilinear

/-- **[The single-mode field satisfies the CAR] `IsCAR caroneMode`.** A concrete witness over `K = ℂ`: the
canonical anticommutation relations hold with `{B(c), B(d)*} = ⟨c, d⟩·1 = c̄d·1` and `{B(c), B(d)} = 0` (from
`boseBilinear`'s `f² = 0` and `f f† + f† f = 1`). So `IsCAR` is realizable and `bogoliubov_preserves_CAR` is
non-vacuous. -/
theorem caroneMode_isCAR : IsCAR (A := Matrix (Fin 2) (Fin 2) ℂ) caroneMode := by
  refine ⟨fun c d => ?_, fun c d => ?_⟩
  · simp only [caroneMode, star_smul, star_star]
    rw [smul_mul_smul_comm, smul_mul_smul_comm, mul_comm d (star c), ← smul_add,
      boseBilinear_isFermionMode.2, RCLike.inner_apply', starRingEnd_apply]
  · simp only [caroneMode, smul_mul_smul_comm, boseBilinear_mul_self, smul_zero, add_zero]

end Physlib.QuantumMechanics.ComplexAction.Bogoliubov.CARAlgebraAutomorphism

end
