/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.GeometricAction
public import Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.ChargeConjugation
public import Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.PTTensorDynamics

/-!
# Greaves–Thomas §4.1: the Classical PT Theorem for Tensors

Formalizes §4.1 of *H. Greaves, T. Thomas, "The CPT Theorem"* (arXiv:1204.4674) — the **Classical PT
Theorem for Tensors** (stated in §4, proved in §5) and **Example 5** (Maxwell). For *tensorial* theories the
relevant group is the proper Lorentz group `L₊ = L↑₊ ∪ L↓₊` (orthochronous part `L↑₊`, the
proper-non-orthochronous PT part `L↓₊`). The theorem asserts that every geometric action of `L↑₊` extends
*universally* to one of `L₊` such that, on `K^form`:

  (1) every `L↑₊`-invariant formal field theory is `L₊`-invariant;
  (2) if `L↑₊` is charge-preserving, then so is `L↓₊`.

The deep "universal extension exists" claim is §5's construction; here we formalize the **group-theoretic
skeleton** of the two conclusions, taking as hypothesis exactly what §5 supplies (that the PT generator `r`
acts as a symmetry / charge-preservingly). Both conclusions are *closure* statements that follow because
symmetries form a subgroup and charge-preserving maps form a submonoid.

* **§A — Part (1): invariance closure** (`classicalPT_invariance_closure`, `classicalPT_invariance`).
  If `L↑₊ ≤ symmetrySubgroup D` and the PT generator `r` is a symmetry, then the whole subgroup
  `⟨L↑₊ ∪ {r}⟩` consists of symmetries; if that subgroup is all of `L₊`, then `D` is `L₊`-invariant — `L↑₊`
  invariance ⟹ `L₊` invariance. Consumes `PTSymmetricQFT.GeometricAction.symmetrySubgroup` /
  `gInvariant_iff_symmetrySubgroup_top`.
* **§B — Part (2): charge-preservation closure** (`chargePreserving_comp`, `chargePreserving_id`,
  `classicalPT_chargePreserving`). Charge-preserving formula automorphisms compose to charge-preserving ones
  and contain the identity, so once `L↑₊` and the PT generator `r` are charge-preserving, every element of
  the coset `L↓₊ = r · L↑₊` is charge-preserving — Part (2). Consumes `IsChargePreserving` of
  `PTSymmetricQFT.ChargeConjugation`.
* **§C — Example 5: Maxwell** (`maxwell_pseudovector_not_pt`). With `F` a rank-2 tensor and `J` a **vector**,
  the Maxwell system is `L↓₊`-invariant — this is exactly `PTSymmetricQFT.PTTensorDynamics.pt_maxwell_invariant`
  (`maxwellOp F (−k) = −J`, the PT image solves it). With `J` a **pseudo-vector** (stipulated to transform
  *without* the sign flip), PT-invariance **fails**: the actual PT image of the left side is `−J`, not `J`,
  so a nonzero current obstructs `L↓₊`-invariance.

## References

* H. Greaves, T. Thomas, *The CPT Theorem*, arXiv:1204.4674, §4.1 (Classical PT Theorem for Tensors,
  Example 5).
* Repo dependencies: `PTSymmetricQFT.GeometricAction` (`symmetrySubgroup`, `IsSymmetry`,
  `gInvariant_iff_symmetrySubgroup_top`); `PTSymmetricQFT.ChargeConjugation` (`IsChargePreserving`);
  `PTSymmetricQFT.PTTensorDynamics` (`maxwellOp`, `maxwellOp_pt`, `pt_maxwell_invariant`).

No additional assumptions.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.ClassicalPTTheorem

open Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.GeometricAction
open Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.ChargeConjugation
open Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.PTTensorDynamics

/-! ## §A — Part (1): `L↑₊`-invariance extends to `L₊`-invariance -/

variable {G : Type*} [Group G] {M V : Type*} [MulAction G M] [MulAction G V]

/-- **[Classical PT Theorem, Part (1) — closure step] Symmetries generated by `L↑₊` and the PT element.**
If the orthochronous subgroup `H = L↑₊` consists of symmetries of `D` and the universal extension's PT
generator `r ∈ L↓₊` is a symmetry, then the whole generated subgroup `⟨H ∪ {r}⟩` consists of symmetries —
because the symmetries of `D` form a subgroup (`symmetrySubgroup`). -/
theorem classicalPT_invariance_closure (D : Set (M → V)) (H : Subgroup G) (r : G)
    (hH : H ≤ symmetrySubgroup D) (hr : IsSymmetry r D) :
    Subgroup.closure (↑H ∪ {r}) ≤ symmetrySubgroup D := by
  rw [Subgroup.closure_le]
  rintro g (hg | hg)
  · exact hH hg
  · rw [Set.mem_singleton_iff] at hg; subst hg; exact hr

/-- **[Classical PT Theorem, Part (1)] `L↑₊`-invariance ⟹ `L₊`-invariance.** If `H = L↑₊` consists of
symmetries, the PT generator `r` is a symmetry, and `L₊ = ⟨L↑₊ ∪ {r}⟩`, then *every* `g ∈ L₊` is a
symmetry — the theory is `L₊`-invariant. This is the existence of classical PT symmetries for any
`L↑₊`-invariant formal field theory. -/
theorem classicalPT_invariance (D : Set (M → V)) (H : Subgroup G) (r : G)
    (hH : H ≤ symmetrySubgroup D) (hr : IsSymmetry r D)
    (hgen : Subgroup.closure (↑H ∪ {r}) = (⊤ : Subgroup G)) :
    ∀ g : G, IsSymmetry g D := by
  rw [gInvariant_iff_symmetrySubgroup_top]
  refine eq_top_iff.mpr ?_
  rw [← hgen]
  exact classicalPT_invariance_closure D H r hH hr

/-! ## §B — Part (2): charge-preservation extends from `L↑₊` to `L↓₊` -/

variable {U : Type*} [AddCommGroup U] [Module ℂ U]

/-- **[Charge-preserving maps compose]** The composite of two charge-preserving formula automorphisms is
charge-preserving (the maps commuting with the charge grading `γ` form a submonoid under composition). -/
theorem chargePreserving_comp (γ σ₁ σ₂ : U →ₗ[ℂ] U)
    (h₁ : IsChargePreserving γ σ₁) (h₂ : IsChargePreserving γ σ₂) :
    IsChargePreserving γ (σ₁.comp σ₂) := by
  unfold IsChargePreserving at *
  rw [LinearMap.comp_assoc, h₂, ← LinearMap.comp_assoc, h₁, LinearMap.comp_assoc]

/-- **[The identity is charge-preserving]** `id` commutes with the charge grading — `1 ∈ L↑₊` acts
charge-preservingly. -/
theorem chargePreserving_id (γ : U →ₗ[ℂ] U) : IsChargePreserving γ LinearMap.id := by
  unfold IsChargePreserving
  rw [LinearMap.id_comp, LinearMap.comp_id]

/-- **[Classical PT Theorem, Part (2)] If `L↑₊` is charge-preserving, so is `L↓₊`.** Every element of the
coset `L↓₊ = r · L↑₊` is the composite of the (charge-preserving) PT generator `r` with an orthochronous
element `σ ∈ L↑₊`; charge-preservation is closed under composition, so the whole of `L↓₊` is
charge-preserving. -/
theorem classicalPT_chargePreserving (γ r σ : U →ₗ[ℂ] U)
    (hr : IsChargePreserving γ r) (hσ : IsChargePreserving γ σ) :
    IsChargePreserving γ (r.comp σ) :=
  chargePreserving_comp γ r σ hr hσ

/-! ## §C — Example 5: Maxwell's equations, vector vs. pseudo-vector current -/

/-- **[Example 5(b)] With a pseudo-vector current, Maxwell is *not* `L↓₊`-invariant.** If `(F, J)` solves
Maxwell at momentum `k` (`maxwellOp F k = J`) with `J ≠ 0`, then the genuine PT image of the left side is
`maxwellOp F (−k) = −J` (rank-2 `F` invariant, derivative `k ↦ −k`). A **pseudo-vector** current is
stipulated to transform *without* the sign flip (`J ↦ J`), so the PT-transformed equation would demand
`maxwellOp F (−k) = J`; since `−J ≠ J` for nonzero `J`, PT-invariance fails. Contrast Example 5(a) — `J` a
genuine **vector**, where `pt_maxwell_invariant` gives `maxwellOp F (−k) = −J` and the system *is*
`L↓₊`-invariant. -/
theorem maxwell_pseudovector_not_pt (F : Matrix (Fin 4) (Fin 4) ℝ) (k J : Fin 4 → ℝ)
    (h : maxwellOp F k = J) (hJ : J ≠ 0) : maxwellOp F (-k) ≠ J := by
  rw [maxwellOp_pt, h]
  intro hc
  apply hJ
  funext α
  have h2 := congrFun hc α
  simp only [Pi.neg_apply, Pi.zero_apply] at h2 ⊢
  linarith

end Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.ClassicalPTTheorem

end
