/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.LindbladSuperoperator
public import Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.QuantumSpacetimeSymmetry
public import Physlib.QuantumMechanics.ComplexAction.CausalDiamond.AdSComplexMomentum

/-!
# Superoperators meet spacetime: the modular flow and the AdS/CFT causal diamond

Links the open-system superoperators of `PTSymmetricQFT.LindbladSuperoperator` and the temporal-orientation
time reversal of `PTSymmetricQFT.QuantumSpacetimeSymmetry` to the **AdS/CFT modular flow** of the causal
diamond (`CausalDiamond.AdSComplexMomentum`).

The **modular Hamiltonian** `K` of a ball-shaped CFT region is the **boost** generating the bulk
causal-diamond / AdS–Rindler wedge (Casini–Huerta–Myers); the **modular flow** (Tomita–Takesaki / Connes–
Rovelli thermal time) is its one-parameter group, generated by `−i[K, ·]` — exactly the
`heisenbergGenerator` of `PTSymmetricQFT.LindbladSuperoperator`. In `CausalDiamond.AdSComplexMomentum` the flow
is the complex coordinate `adSComplexCoord W θ = W·e^{iθ}` (AdS: **imaginary** rapidity ⇒ a *rotation*,
compact and KMS-thermal at the Unruh/Hawking temperature) or `dSComplexCoord w η = w cosh η + i w sinh η`
(dS: **real** rapidity ⇒ a *boost*). Its modular invariant `W²` (resp. `w²`) is the horizon area / the
Minkowski mass shell — the entanglement (Ryu–Takayanagi) entropy.

* **§A — the AdS modular flow** (`timeReversal_adSModularFlow`, `adS_area_timeReversal_invariant`,
  `adSModularFlow_timeReversal_area`). The antiunitary time reversal `conjFactor true` **reverses** the
  modular flow `θ ↦ −θ`, while the **horizon area `W²`** is invariant; the modular round trip
  `(flow) · (time-reversed flow) = W²` is the horizon area — the KMS/thermal structure.
* **§B — the dS boost / lapse mass shell** (`timeReversal_dSBoost`,
  `dS_lorentzianForm_timeReversal_invariant`). Time reversal reverses the boost rapidity `η ↦ −η`, while
  the Minkowski interval `lorentzianForm = w²` (the lapse / Jacobson-diamond mass shell) is invariant —
  the same `θ ↦ −θ` reflection as the lapse/boost/diamond triangle of `PTSymmetricQFT.QuantumSpacetimeSymmetry`.
* **§C — the modular generator is a `*`-automorphism** (`adsModular_generator_star`). The AdS–Rindler
  modular flow generator `−i[K, ·]` with a self-adjoint modular Hamiltonian `K` is `*`-compatible — the
  Tomita–Takesaki modular automorphism preserves observables (`heisenbergGenerator_star`). Its open-system
  completion is the GKSL generator (`gksGenerator`), whose KMS fixed point is the diamond's Unruh/Hawking
  thermal equilibrium.

So the superoperator side closes on spacetime: the unitary modular generator `−i[K,·]` is the AdS/CFT
causal-diamond boost flow, antiunitary time reversal reflects it `θ ↦ −θ` while preserving the horizon
area / mass shell, and the GKSL dissipator dresses it into the open-system (thermal) dynamics.

## References

* H. Casini, M. Huerta, R. Myers, *Towards a derivation of holographic entanglement entropy*, JHEP 05
  (2011) 036 — the modular Hamiltonian of a ball is the boost. M. Tomita, M. Takesaki (1970); A. Connes,
  C. Rovelli, *Von Neumann algebra automorphisms and time–thermodynamics relation*, Class. Quantum Grav.
  11 (1994) 2899 — modular flow as thermal time.
* Repo dependencies: `PTSymmetricQFT.LindbladSuperoperator` (`heisenbergGenerator`, `gksGenerator`);
  `PTSymmetricQFT.QuantumSpacetimeSymmetry` (`conjFactor`, `lorentzianForm_timeReversal`);
  `CausalDiamond.AdSComplexMomentum` (`adSComplexCoord`, `dSComplexCoord`, the imaginary-rapidity AdS flow).

No new axioms.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.ModularAdS

open Complex
open Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.TemporalOrientation
open Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.QuantumSpacetimeSymmetry
open Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.LindbladSuperoperator
open Physlib.QuantumMechanics.ComplexAction.CausalDiamond.AdSComplexMomentum
open Physlib.QuantumMechanics.ComplexAction.ComplexDelta.Convergence

/-! ## §A — the AdS modular flow (rotation = imaginary rapidity) -/

/-- **[Modular flow] Time reversal reverses the AdS modular flow** `θ ↦ −θ`. The AdS–Rindler modular flow is
the rotation `adSComplexCoord W θ = W·e^{iθ}` (imaginary rapidity); the antiunitary time reversal
`conjFactor true` conjugates it to the reverse flow `adSComplexCoord W (−θ)`. -/
theorem timeReversal_adSModularFlow (W θ : ℝ) :
    conjFactor true (adSComplexCoord W θ) = adSComplexCoord W (-θ) := by
  simp only [conjFactor_true, adSComplexCoord, map_mul, ← Complex.exp_conj, Complex.conj_ofReal,
    Complex.conj_I]
  push_cast; ring_nf

/-- **[Holographic entropy] The AdS horizon area `W²` is time-reversal invariant.** The modular invariant
(the Ryu–Takayanagi area / entanglement entropy `W²`) is unchanged by the time-reversing conjugation. -/
theorem adS_area_timeReversal_invariant (W θ : ℝ) :
    Complex.normSq (conjFactor true (adSComplexCoord W θ)) = W ^ 2 := by
  rw [timeReversal_adSModularFlow]; exact adSComplexCoord_normSq W (-θ)

/-- **[KMS structure] The modular round trip is the horizon area.** The modular flow composed with its
time-reverse, `adSComplexCoord W θ · conj(adSComplexCoord W θ) = W²`, returns the horizon area — the
thermal (KMS) closure of the modular automorphism. -/
theorem adSModularFlow_timeReversal_area (W θ : ℝ) :
    adSComplexCoord W θ * conjFactor true (adSComplexCoord W θ) = (W ^ 2 : ℝ) := by
  rw [conjFactor_true, Complex.mul_conj, adSComplexCoord_normSq]

/-! ## §B — the dS boost / lapse mass shell (real rapidity) -/

/-- **[Boost flow] Time reversal reverses the dS boost** `η ↦ −η`. The dS modular/boost flow is
`dSComplexCoord w η = w cosh η + i w sinh η` (the lapse form); time reversal conjugates it to
`dSComplexCoord w (−η)`. -/
theorem timeReversal_dSBoost (w η : ℝ) :
    conjFactor true (dSComplexCoord w η) = dSComplexCoord w (-η) := by
  simp only [conjFactor_true, dSComplexCoord, map_add, map_mul, Complex.conj_ofReal, Complex.conj_I,
    Real.cosh_neg, Real.sinh_neg]
  push_cast; ring_nf

/-- **[Mass shell] The dS lapse interval `w²` is time-reversal invariant.** The Minkowski interval
`lorentzianForm = w²` (the lapse / Jacobson-diamond mass shell) is unchanged under time reversal — the same
reflection as the lapse/boost/diamond triangle of `PTSymmetricQFT.QuantumSpacetimeSymmetry`. -/
theorem dS_lorentzianForm_timeReversal_invariant (w η : ℝ) :
    lorentzianForm (conjFactor true (dSComplexCoord w η)) = w ^ 2 := by
  rw [lorentzianForm_timeReversal]; exact dSComplexCoord_lorentzianForm w η

/-! ## §C — the modular generator is a `*`-automorphism -/

/-- **[Tomita–Takesaki] The AdS–Rindler modular flow generator is a `*`-automorphism.** For a self-adjoint
modular Hamiltonian `K` the generator `−i[K, ·]` (`PTSymmetricQFT.LindbladSuperoperator.heisenbergGenerator`)
preserves self-adjointness — the modular automorphism maps observables to observables. Its open-system
completion is the GKSL generator `gksGenerator K L`, whose KMS fixed point is the diamond's Unruh/Hawking
thermal state. -/
theorem adsModular_generator_star {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A] [StarModule ℂ A]
    (K Y : A) (hK : star K = K) :
    star (heisenbergGenerator K Y) = heisenbergGenerator K (star Y) :=
  heisenbergGenerator_star K Y hK

end Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.ModularAdS

end
