/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic

/-!
# The Deser–Jackiw–Templeton topological mass

The exact algebraic core of the **topological mass** of `2+1`-dimensional topologically massive gauge theory
(S. Deser, R. Jackiw, S. Templeton, *Ann. Phys.* **140** (1982) 372). Adding a **Chern–Simons** term at
integer level `k` to a `U(1)` gauge theory with coupling `e` gives the gauge boson (photon) a **topological
mass**

  `m_CS = e²·|k| / (2π)`   (`topologicalMass`),

without breaking gauge invariance — the mass is generated by the topological CS term, with `k ∈ ℤ`
quantised. The exact consequences:

* the mass is **non-negative** (`topologicalMass_nonneg`);
* at non-zero coupling it **vanishes iff the CS level is zero** (`topologicalMass_eq_zero_iff_level_zero`) —
  no Chern–Simons term, no topological mass;
* at fixed coupling it is **linear in the level** `|k|` (`topologicalMass_ratio_level`).

This is a distinct mechanism for a gauge boson to acquire mass — topological, not from confinement
(`Dirac.SaitoConfinedPhotonMass`) nor a Higgs/Landau vacuum. The formalization is the exact `ℝ`-algebra core.

* **§A — DJT data and the topological mass** (`DJTData`, `topologicalMass`, `topologicalMass_nonneg`,
  `topologicalMass_eq_zero_iff_level_zero`, `topologicalMass_ratio_level`).

## References

* S. Deser, R. Jackiw, S. Templeton, *Topologically Massive Gauge Theories* (1982). structures: `Mathlib`
  (`Real.pi`); cf. `Dirac.SaitoConfinedPhotonMass` (the confinement photon-mass mechanism).

No new axioms.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.ChernSimons.TopologicalMassDJT

/-! ## §A — DJT data and the topological mass -/

/-- **DJT data**: a `U(1)` coupling `e ∈ ℝ` and a Chern–Simons level `k ∈ ℤ` (the level is an integer by
topological quantisation; no positivity is imposed). -/
structure DJTData where
  /-- `U(1)` coupling constant. -/
  e : ℝ
  /-- Chern–Simons level (integer). -/
  level : ℤ

/-- **The DJT topological mass** `m_CS = e²·|k| / (2π)` — the mass the Chern–Simons term gives the gauge
boson. -/
noncomputable def topologicalMass (dj : DJTData) : ℝ :=
  dj.e ^ 2 * |(dj.level : ℝ)| / (2 * Real.pi)

private lemma two_pi_pos : (0 : ℝ) < 2 * Real.pi := mul_pos (by norm_num) Real.pi_pos

/-- **[Non-negativity] `0 ≤ m_CS`.** -/
theorem topologicalMass_nonneg (dj : DJTData) : 0 ≤ topologicalMass dj := by
  rw [topologicalMass]
  exact div_nonneg (mul_nonneg (sq_nonneg _) (abs_nonneg _)) two_pi_pos.le

/-- **[The mass vanishes iff the level is zero] (at non-zero coupling).** No Chern–Simons term (`k = 0`), no
topological mass. -/
theorem topologicalMass_eq_zero_iff_level_zero {dj : DJTData} (he : dj.e ≠ 0) :
    topologicalMass dj = 0 ↔ dj.level = 0 := by
  rw [topologicalMass, div_eq_zero_iff]
  have hsq : dj.e ^ 2 ≠ 0 := pow_ne_zero 2 he
  constructor
  · rintro (hnum | hpi)
    · rcases mul_eq_zero.mp hnum with h1 | h2
      · exact absurd h1 hsq
      · exact_mod_cast abs_eq_zero.mp h2
    · exact absurd hpi two_pi_pos.ne'
  · intro h; left; rw [h]; simp

/-- **[Linear in the level] at fixed coupling** `m₁·|k₂| = m₂·|k₁|`: the topological masses are in the ratio
of the Chern–Simons levels. -/
theorem topologicalMass_ratio_level {dj₁ dj₂ : DJTData} (he : dj₁.e = dj₂.e) :
    topologicalMass dj₁ * |(dj₂.level : ℝ)| = topologicalMass dj₂ * |(dj₁.level : ℝ)| := by
  rw [topologicalMass, topologicalMass, he]; ring

end Physlib.QuantumMechanics.ComplexAction.ChernSimons.TopologicalMassDJT

end
