/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Mathlib.Analysis.SpecialFunctions.Complex.Circle
public import Mathlib.Analysis.SpecialFunctions.Sqrt

/-!
# The entropic-dynamics wave function, the Born rule, and the phase-shift Killing flow

The bridge from the statistical manifold to quantum mechanics. The entropic-dynamics wave function assembles a
probability `ρ` and a phase `Φ` (the current potential) into a single complex amplitude,

`ψ(ρ, Φ) = √ρ · e^{iΦ}`,

whose modulus-squared recovers the probability — the **Born rule** `|ψ|² = ρ` — and whose overall phase is a
gauge freedom: the flow `ψ ↦ e^{iν}ψ` generated by the normalization constraint is a one-parameter group of
isometries (a **Killing flow**) that leaves the Born probabilities invariant, so quantum states are **rays**, not
vectors.

References: A. Caticha, arXiv:2107.08502 (§§5–6). No new axioms.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.WaveFunction

/-- **The entropic-dynamics wave function** `ψ(ρ, Φ) = √ρ · e^{iΦ}` — the polar (Madelung) assembly of a
probability `ρ` and a phase `Φ` into a complex amplitude. -/
noncomputable def edWaveFunction (ρ Φ : ℝ) : ℂ := (Real.sqrt ρ : ℂ) * Complex.exp ((Φ : ℂ) * Complex.I)

/-- **The Born rule** `|ψ|² = ρ`. For `ρ ≥ 0` the modulus-squared of `ψ = √ρ e^{iΦ}` is exactly the probability
`ρ`, independent of the phase. -/
theorem edWaveFunction_normSq (ρ Φ : ℝ) (hρ : 0 ≤ ρ) : Complex.normSq (edWaveFunction ρ Φ) = ρ := by
  unfold edWaveFunction
  rw [map_mul, Complex.normSq_ofReal, Real.mul_self_sqrt hρ, Complex.normSq_eq_norm_sq,
    Complex.norm_exp_ofReal_mul_I]
  norm_num

/-- **The normalization gauge is a phase multiplication** `ψ(ρ, Φ + ν) = e^{iν} ψ(ρ, Φ)`. The flow generated by the
normalization constraint shifts the phase `Φ → Φ + ν`, which on the wave function is multiplication by `e^{iν}` —
the global gauge symmetry that makes quantum states rays. -/
theorem phaseShift_gauge (ρ Φ ν : ℝ) :
    edWaveFunction ρ (Φ + ν) = Complex.exp ((ν : ℂ) * Complex.I) * edWaveFunction ρ Φ := by
  unfold edWaveFunction
  rw [show ((Φ + ν : ℝ) : ℂ) * Complex.I = (Φ : ℂ) * Complex.I + (ν : ℂ) * Complex.I by
        push_cast; ring, Complex.exp_add]
  ring

/-- **The phase gauge is a one-parameter group** `ψ(ρ, Φ + (ν₁+ν₂)) = e^{iν₂} ψ(ρ, Φ + ν₁)` — successive phase
shifts compose additively (the `U(1)` group). -/
theorem phaseShift_add (ρ Φ ν₁ ν₂ : ℝ) :
    edWaveFunction ρ (Φ + (ν₁ + ν₂)) = Complex.exp ((ν₂ : ℂ) * Complex.I) * edWaveFunction ρ (Φ + ν₁) := by
  rw [← add_assoc]
  exact phaseShift_gauge ρ (Φ + ν₁) ν₂

/-- **The phase gauge is a Born-rule isometry — a Killing flow** `|ψ(Φ+ν)|² = |ψ(Φ)|²`. The phase shift preserves
the modulus, hence the Fubini–Study metric: the normalization/phase flow is an isometry (a Killing flow), the
property the Hamilton–Killing construction demands, and the reason the physical Born probabilities are
gauge-invariant. -/
theorem phaseShift_born_isometry (ρ Φ ν : ℝ) :
    Complex.normSq (edWaveFunction ρ (Φ + ν)) = Complex.normSq (edWaveFunction ρ Φ) := by
  rw [phaseShift_gauge, map_mul]
  have h1 : Complex.normSq (Complex.exp ((ν : ℂ) * Complex.I)) = 1 := by
    rw [Complex.normSq_eq_norm_sq, Complex.norm_exp_ofReal_mul_I]; norm_num
  rw [h1, one_mul]

end Physlib.QuantumMechanics.WaveFunction

end
