/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Mathlib.Analysis.SpecialFunctions.Complex.Analytic
public import Mathlib.MeasureTheory.Integral.IntegralEqImproper
public import Mathlib.Analysis.Calculus.MeanValue

/-!
# Contour rotation is generated by an exact derivative (Nagao–Nielsen §2.5)

`ComplexDelta.Contour` proved the complex-action delta's normalization is the same along every
permitted ray (the `f ≡ 1` contour identity). The general statement — that
`∫_γ f(q) δ_c(q) dq` is independent of the permitted contour `γ` for holomorphic `f` —
is the contour-deformation / principal-value content. The usual proof is a 2D Cauchy
argument on the wedge between two rays, with an arc-at-infinity estimate.

This file establishes the **1D analytic heart** of that deformation, avoiding the wedge.
Write the contour integrand along the ray `q = e^{iθ}·s` as `Φ(θ,s) = h(e^{iθ}s)·e^{iθ}`
(with `h` holomorphic — for complex-action, `h = f·δ_c^ε`). Then the rate of change of the contour
integral with the contour angle `θ` is governed by an **exact `s`-derivative**:

 `∂_θ Φ(θ,s) = ∂_s [ i·e^{iθ}·s·h(e^{iθ}s) ]`.

This is the Cauchy–Riemann structure (holomorphy of `h`) written as a total derivative.
Consequently, whenever the primitive and the derivative are integrable, the
fundamental theorem of calculus on `ℝ` (boundary terms vanish) gives

 `∫_ℝ ∂_θ Φ(θ,s) ds = 0` — **infinitesimal contour independence**.

* `hasDerivAt_contourIntegrand_theta` — `∂_θ Φ(θ,s) = contourDeriv θ s` (`θ`-derivative).
* `hasDerivAt_contourPrimitive_s` — `∂_s (i·e^{iθ}·s·h(e^{iθ}s)) = contourDeriv θ s`
 (the *same* value): the exact-derivative identity.
* `integral_contourDeriv_eq_zero` — `∫_ℝ contourDeriv θ s ds = 0`, i.e. the
 derivative-in-`θ` of the contour integral integrand integrates to `0`: rotating a
 permitted contour does not change the integral, to first order.
* `contourIntegral_const_of_dui` — **the finite statement**: the contour integral
 `∫ Φ(θ,·)` is *constant* in `θ` across the permitted cone (an open interval `(a,b)`),
 because its `θ`-derivative is `0` on a connected set.
* `contourIntegral_eq_real` — **`∫_γ f·δ_c = ∫_ℝ f·δ_c`** (Eq. 2.30, finite form): the
 contour integral along any permitted ray equals the real-axis integral (`θ = 0`).

scope: the finite identity is proven *conditional on differentiation under the
integral sign* (`hdui`) — moving `d/dθ` past `∫`. That step is the standard technical
fact, provable from Mathlib's `hasDerivAt_integral_of_dominated_loc_of_deriv_le`
given, for a concrete `f`, the uniform Gaussian domination of `contourDeriv` on a
neighbourhood (a polynomial × Gaussian bound, finite since `cos 2θ` is bounded below on a
sub-cone). The genuinely new content here — that a zero derivative on the *connected*
cone forces constancy, hence `∫_γ = ∫_ℝ` — is proven outright via
`IsOpen.is_const_of_deriv_eq_zero`. Proving `hdui` for a specific `f` is the remaining
bookkeeping.

Reference: K. Nagao, H. B. Nielsen, *Formulation of Complex Action Theory*, Prog. Theor.
Phys. **126**(6) (2011) 1021–1049, §2.5, Eqs. (2.28)–(2.30), doi:10.1143/PTP.126.1021.
-/

set_option autoImplicit false

open Complex MeasureTheory

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.ComplexDelta.ContourShift

variable {h h' : ℂ → ℂ}

/-- The contour integrand along the ray `q = e^{iθ}·s`: `Φ(θ,s) = h(e^{iθ}s)·e^{iθ}`
(the `e^{iθ}` is the Jacobian `dq/ds`). -/
noncomputable def contourIntegrand (h : ℂ → ℂ) (θ s : ℝ) : ℂ :=
  h (Complex.exp (θ * Complex.I) * s) * Complex.exp (θ * Complex.I)

/-- The `s`-primitive whose derivative is `∂_θ Φ`: `i·e^{iθ}·s·h(e^{iθ}s)`. -/
noncomputable def contourPrimitive (h : ℂ → ℂ) (θ s : ℝ) : ℂ :=
  Complex.I * Complex.exp (θ * Complex.I) * (s * h (Complex.exp (θ * Complex.I) * s))

/-- The common derivative value `∂_θ Φ = ∂_s (contourPrimitive)`:
`i·e^{iθ}·(h(e^{iθ}s) + s·e^{iθ}·h'(e^{iθ}s))`. -/
noncomputable def contourDeriv (h h' : ℂ → ℂ) (θ s : ℝ) : ℂ :=
  Complex.I * Complex.exp (θ * Complex.I) *
    (h (Complex.exp (θ * Complex.I) * s) +
      s * Complex.exp (θ * Complex.I) * h' (Complex.exp (θ * Complex.I) * s))

/-- `d/dθ e^{iθ} = i·e^{iθ}`. -/
theorem hasDerivAt_rayDir (θ : ℝ) :
    HasDerivAt (fun θ : ℝ => Complex.exp (θ * Complex.I)) (Complex.exp (θ * Complex.I) * Complex.I) θ := by
  have h1 : HasDerivAt (fun θ : ℝ => (θ : ℂ) * Complex.I) Complex.I θ := by
    simpa using (Complex.ofRealCLM.hasDerivAt (x := θ)).mul_const Complex.I
  simpa using h1.cexp

/-- **The `θ`-derivative of the contour integrand**: `∂_θ Φ(θ,s) = contourDeriv θ s`. -/
theorem hasDerivAt_contourIntegrand_theta (hh : ∀ z, HasDerivAt h (h' z) z) (θ s : ℝ) :
    HasDerivAt (fun θ : ℝ => contourIntegrand h θ s) (contourDeriv h h' θ s) θ := by
  simp only [contourIntegrand]
  have he := hasDerivAt_rayDir θ
  have hu : HasDerivAt (fun θ : ℝ => Complex.exp (θ * Complex.I) * (s : ℂ))
      (Complex.exp (θ * Complex.I) * Complex.I * s) θ := he.mul_const _
  have hcomp := (hh (Complex.exp (θ * Complex.I) * s)).comp θ hu
  have raw := hcomp.mul he
  exact raw.congr_deriv (by simp only [contourDeriv, Function.comp_apply]; ring)

/-- **The exact-derivative identity**: `∂_s (i·e^{iθ}·s·h(e^{iθ}s)) = contourDeriv θ s` —
the *same* value as `∂_θ Φ`. This is the Cauchy–Riemann structure that makes rotating the
contour an exact differential. -/
theorem hasDerivAt_contourPrimitive_s (hh : ∀ z, HasDerivAt h (h' z) z) (θ s : ℝ) :
    HasDerivAt (fun s : ℝ => contourPrimitive h θ s) (contourDeriv h h' θ s) s := by
  simp only [contourPrimitive]
  have hs : HasDerivAt (fun s : ℝ => Complex.exp (θ * Complex.I) * (s : ℂ))
      (Complex.exp (θ * Complex.I)) s := by
    exact ((Complex.ofRealCLM.hasDerivAt (x := s)).const_mul (Complex.exp (θ * Complex.I))).congr_deriv (by simp)
  have hsid : HasDerivAt (fun s : ℝ => (s : ℂ)) 1 s := by
    exact (Complex.ofRealCLM.hasDerivAt (x := s)).congr_deriv (by simp)
  have hcomp := (hh (Complex.exp (θ * Complex.I) * s)).comp s hs
  have raw := (hsid.mul hcomp).const_mul (Complex.I * Complex.exp (θ * Complex.I))
  exact raw.congr_deriv (by simp only [contourDeriv, Function.comp_apply]; ring)

/-- **Infinitesimal contour independence**: `∫_ℝ contourDeriv θ s ds = 0`. The
derivative-in-`θ` of the contour-integral integrand integrates to zero (the boundary
terms of the exact `s`-primitive vanish), so rotating a permitted contour does not change
the integral to first order. Requires the primitive and the derivative to be integrable
(automatic for `h = f·δ_c^ε` with `f` polynomially bounded: a polynomial × Gaussian). -/
theorem integral_contourDeriv_eq_zero (hh : ∀ z, HasDerivAt h (h' z) z) (θ : ℝ)
    (hP : Integrable (fun s : ℝ => contourPrimitive h θ s))
    (hD : Integrable (fun s : ℝ => contourDeriv h h' θ s)) :
    ∫ s : ℝ, contourDeriv h h' θ s = 0 :=
  integral_eq_zero_of_hasDerivAt_of_integrable
    (fun s => hasDerivAt_contourPrimitive_s hh θ s) hD hP

/-! ## The finite identity: the contour integral is independent of the permitted angle

Upgrading the infinitesimal statement to the finite `∫_γ = ∫_ℝ`. Moving `d/dθ` outside the
integral is differentiation under the integral sign (`hdui` below) — the standard
technical step, provable from Mathlib's
`hasDerivAt_integral_of_dominated_loc_of_deriv_le` once one supplies, for a concrete `f`,
the uniform Gaussian domination of `contourDeriv` on a neighbourhood (a
polynomial × Gaussian bound, finite because `cos 2θ` is bounded below on a sub-cone). We
take that as a hypothesis and prove the genuinely new content: a vanishing derivative on
the **connected** permitted cone forces the contour integral to be constant. -/

/-- **The contour integral is constant in the permitted angle.** If differentiation under
the integral holds on an open interval `(a,b)` of angles (`hdui`), then the contour
integral `∫ Φ(θ,·)` takes the same value at every `θ` there: by `integral_contourDeriv_eq_zero`
its `θ`-derivative is `0`, and a zero derivative on the connected `(a,b)` is constant. -/
theorem contourIntegral_const_of_dui (hh : ∀ z, HasDerivAt h (h' z) z) {a b : ℝ}
    (hdui : ∀ θ ∈ Set.Ioo a b,
      HasDerivAt (fun θ => ∫ s, contourIntegrand h θ s) (∫ s, contourDeriv h h' θ s) θ)
    (hP : ∀ θ ∈ Set.Ioo a b, Integrable (fun s : ℝ => contourPrimitive h θ s))
    (hD : ∀ θ ∈ Set.Ioo a b, Integrable (fun s : ℝ => contourDeriv h h' θ s))
    {θ₀ θ₁ : ℝ} (h0 : θ₀ ∈ Set.Ioo a b) (h1 : θ₁ ∈ Set.Ioo a b) :
    (∫ s, contourIntegrand h θ₀ s) = (∫ s, contourIntegrand h θ₁ s) := by
  have hzero : ∀ θ ∈ Set.Ioo a b,
      HasDerivAt (fun θ => ∫ s, contourIntegrand h θ s) 0 θ := by
    intro θ hθ
    have hd := hdui θ hθ
    rwa [integral_contourDeriv_eq_zero hh θ (hP θ hθ) (hD θ hθ)] at hd
  exact isOpen_Ioo.is_const_of_deriv_eq_zero (convex_Ioo a b).isPreconnected
    (fun θ hθ => (hzero θ hθ).differentiableAt.differentiableWithinAt)
    (fun θ hθ => (hzero θ hθ).deriv) h0 h1

/-- **`∫_γ f·δ_c = ∫_ℝ f·δ_c`** (Nagao–Nielsen Eq. 2.30, finite form). Under the same
hypotheses, the contour integral along any permitted ray `θ ∈ (a,b) ∋ 0` equals the
real-axis integral `∫_ℝ h(s) ds` (the `θ = 0` value). Composing with the real-axis limit
`tendsto_integral_deltaEps_smul` then gives `→ f(0)`. -/
theorem contourIntegral_eq_real (hh : ∀ z, HasDerivAt h (h' z) z) {a b : ℝ}
    (hdui : ∀ θ ∈ Set.Ioo a b,
      HasDerivAt (fun θ => ∫ s, contourIntegrand h θ s) (∫ s, contourDeriv h h' θ s) θ)
    (hP : ∀ θ ∈ Set.Ioo a b, Integrable (fun s : ℝ => contourPrimitive h θ s))
    (hD : ∀ θ ∈ Set.Ioo a b, Integrable (fun s : ℝ => contourDeriv h h' θ s))
    (hmem0 : (0 : ℝ) ∈ Set.Ioo a b) {θ : ℝ} (hθ : θ ∈ Set.Ioo a b) :
    (∫ s, contourIntegrand h θ s) = ∫ s : ℝ, h (s : ℂ) := by
  rw [contourIntegral_const_of_dui hh hdui hP hD hθ hmem0]
  simp only [contourIntegrand, Complex.ofReal_zero, zero_mul, Complex.exp_zero, mul_one,
    one_mul]

end Physlib.QuantumMechanics.ComplexAction.ComplexDelta.ContourShift

end
