/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.AlgebraicQFTQuasifree.CausalOrthogonalityQuasiLocalNet

/-!
# Additivity of the quasi-local net and partitions of unity (Labuschagne–Majewski §10)

Formalizes §10 of Labuschagne–Majewski (arXiv:2503.14107): the **additivity** property of the net of local von
Neumann algebras — a local algebra `𝓜(𝒪)` is generated by the algebras of any countable open cover `{𝒱_n}` of
`𝒪`, `𝓜(𝒪) = (⋃_n 𝓜(𝒱_n))''` (their Theorem 10.4) — proved via a **partition of unity** (their Def. 10.2).

* the **partition of unity** `∑_γ x_γ = 1` (`IsPartitionOfUnity`) decomposes any observable `f = ∑_γ x_γ f`
 (`partition_decompose`) — the tool that splits a global field into pieces supported in the cover charts;
* the **easy inclusion** of additivity `(⋃ 𝓜(𝒱_n))'' ⊆ 𝓜(𝒪)` (`additivity_double_commutant_subset`) holds for a
 von Neumann `𝓜(𝒪)` containing the union, by antitonicity of the commutant and `𝓜(𝒪)'' = 𝓜(𝒪)`;
* combined with the additivity inclusion, the net is **additive** `𝓜(𝒪) = (⋃ 𝓜(𝒱_n))''` (`net_additive`), and
 for a quasi-local net whose regions cover `𝒪` this is exact isotony-plus-additivity
 (`quasiLocalNet_additive`).

So a partition of unity subordinate to a cover lets one build the local algebra of a region from the algebras of
the cover — additivity, the last structural property of the covariant, isotonic, additive net.

* **§A — partitions of unity** (`IsPartitionOfUnity`, `partition_decompose`).
* **§B — additivity of a von Neumann local algebra** (`additivity_double_commutant_subset`, `net_additive`).
* **§C — additivity of the quasi-local net** (`quasiLocalNet_additive`).

The partition-of-unity decomposition and the additivity double-commutant inclusions are
exact algebra (reusing `commutant`, `commutant_antitone`, `IsVonNeumann`). The *existence* of a smooth partition
of unity subordinate to a cover (Thm 10.3) and the reverse additivity inclusion (the `σ`-strong-limit argument of
Thm 10.4) are *recorded* — `net_additive` takes the additivity inclusion as a hypothesis. No new axioms.

## References

* L.E. Labuschagne, W.A. Majewski, arXiv:2503.14107, §10 (Def. 10.1–10.2, Thm. 10.3–10.4, additivity). Repo
 structures: `AlgebraicQFT.GNSVonNeumannHadamard` (`commutant`, `commutant_antitone`, `IsVonNeumann`),
 `AlgebraicQFTQuasifree.CausalOrthogonalityQuasiLocalNet` (`QuasiLocalNet`).

No new axioms.
-/

set_option autoImplicit false

open Physlib.QuantumMechanics.ComplexAction.AlgebraicQFT.GNSVonNeumannHadamard
open Physlib.QuantumMechanics.ComplexAction.AlgebraicQFTQuasifree.CausalOrthogonalityQuasiLocalNet

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.AlgebraicQFTQuasifree.NetAdditivityPartitionOfUnity

/-! ## §A — partitions of unity -/

/-- **A partition of unity** (Labuschagne–Majewski Def. 10.2): a finite family `x_γ` of non-negative functions
summing to `1`, `∑_γ x_γ = 1` (the local-finiteness / subordination to a cover is geometric and recorded). -/
def IsPartitionOfUnity {ι α : Type*} (s : Finset ι) (x : ι → α → ℝ) : Prop :=
  (∀ i p, 0 ≤ x i p) ∧ (∀ p, ∑ i ∈ s, x i p = 1)

/-- **[A partition of unity decomposes any observable] `∑_γ x_γ·f = f`.** Multiplying by a partition of unity and
summing recovers the original function — the decomposition `f = ∑_γ x_γ f` used to split a global field operator
into pieces supported in the cover charts (the heart of the additivity proof). -/
theorem partition_decompose {ι α : Type*} {s : Finset ι} {x : ι → α → ℝ}
    (h : IsPartitionOfUnity s x) (f : α → ℝ) (p : α) : ∑ i ∈ s, x i p * f p = f p := by
  rw [← Finset.sum_mul, h.2 p, one_mul]

/-! ## §B — additivity of a von Neumann local algebra -/

variable {R : Type*} [Monoid R]

/-- **[The easy inclusion of additivity] `(⋃ 𝓜(𝒱_n))'' ⊆ 𝓜(𝒪)`.** If a von Neumann algebra `M` contains the union
of a family `A_n` of subalgebras, then it contains the von Neumann algebra `(⋃ A_n)''` they generate — by
antitonicity of the commutant applied twice and `M'' = M`. -/
theorem additivity_double_commutant_subset {ι : Type*} {A : ι → Set R} {M : Set R}
    (hsub : (⋃ i, A i) ⊆ M) (hM : IsVonNeumann M) :
    commutant (commutant (⋃ i, A i)) ⊆ M := by
  have h2 : commutant (commutant (⋃ i, A i)) ⊆ commutant (commutant M) :=
    commutant_antitone (commutant_antitone hsub)
  rwa [hM] at h2

/-- **[Additivity] `𝓜(𝒪) = (⋃ 𝓜(𝒱_n))''`.** Given the isotony inclusion `⋃ A_n ⊆ M`, a von Neumann `M`, and the
additivity inclusion `M ⊆ (⋃ A_n)''`, the local algebra is exactly the von Neumann algebra generated by the
cover's subalgebras (Theorem 10.4). -/
theorem net_additive {ι : Type*} {A : ι → Set R} {M : Set R} (hsub : (⋃ i, A i) ⊆ M)
    (hM : IsVonNeumann M) (hadd : M ⊆ commutant (commutant (⋃ i, A i))) :
    M = commutant (commutant (⋃ i, A i)) :=
  Set.Subset.antisymm hadd (additivity_double_commutant_subset hsub hM)

/-! ## §C — additivity of the quasi-local net -/

/-- **[The quasi-local net is additive] `𝓜(𝒪) = (⋃ 𝓜(𝒱_j))''`.** If a family of regions `𝒱_j` covers `𝒪`
(`𝒱_j ≤ 𝒪`), the union of their local algebras sits in `𝓜(𝒪)` by isotony; with `𝓜(𝒪)` von Neumann and the
additivity inclusion, `𝓜(𝒪)` is exactly the von Neumann algebra they generate — additivity of the net
(Theorem 10.4). -/
theorem quasiLocalNet_additive {ι' : Type*} [Preorder ι'] (Q : QuasiLocalNet R ι') {J : Type*}
    {V : J → ι'} {O : ι'} (hcover : ∀ j, V j ≤ O) (hM : IsVonNeumann (Q.alg O))
    (hadd : Q.alg O ⊆ commutant (commutant (⋃ j, Q.alg (V j)))) :
    Q.alg O = commutant (commutant (⋃ j, Q.alg (V j))) := by
  refine net_additive ?_ hM hadd
  exact Set.iUnion_subset fun j => Q.isotony (hcover j)

end Physlib.QuantumMechanics.ComplexAction.AlgebraicQFTQuasifree.NetAdditivityPartitionOfUnity

end
