/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.CollisionOperatorSl2.CollisionModular
public import Physlib.QuantumMechanics.ComplexAction.AlgebraicQFTQuasifree.CausalOrthogonalityQuasiLocalNet

/-!
# Quantum Killing flows and Lie derivatives: lifting the isometric flow to the local algebra (Labuschagne–Majewski §§5–6)

Formalizes Part 1 of Labuschagne–Majewski (arXiv:2503.14107, §§5–6): flows for local quantum systems on a curved
spacetime are defined **directly from Killing vector fields**. A Killing field `Z` (geometric, `L_Z g = 0` —
`Curvature.DiffeomorphismMetricVariation.IsKillingVector`) has an isometric local flow `Ψ_s^Z`; this flow **lifts
to the algebra**: it canonically induces a one-parameter group of `*`-isomorphisms
`π_s^Z : 𝒜(𝒪) → 𝒜(Ψ_s^Z 𝒪)` (their Cor. 5.6, Thm. 5.3), and the infinitesimal generator is the **quantum Killing
Lie derivative** `δ_Z(a) = lim_{t→0} (π_t^Z(a) − a)/t`, a `*`-derivation (their Def. 6.1).

* the **quantum Killing Lie derivative** `δ_Z = [H_Z, ·]` is the inner derivation of the Killing generator
 (`quantumKillingLieDerivative`, reusing `collisionStar`), a derivation obeying the Leibniz rule
 (`quantumKillingLieDerivative_leibniz`) and annihilating its own generator
 (`quantumKillingLieDerivative_generator_invariant`) — the algebraic quantum Lie derivative of Def. 6.1;
* the **Killing flow** is a one-parameter group of ring `*`-automorphisms (`KillingFlow`): `π_0 = id`,
 `π_{s+t} = π_s ∘ π_t` (the local cocycle of Thm. 5.3), each `π_s` invertible (`killingFlow_inverse`) and a Lie
 bracket automorphism (`killingFlow_preserves_bracket`);
* the flow **commutes with its generator** when the Killing generator is flow-invariant
 (`killingFlow_commutes_generator`) — the algebraic conservation of the Killing "Hamiltonian";
* **covariance on the quasi-local net** (`CovariantKillingFlow`): the algebraic flow implements the geometric one
 (`π_s 𝒜(𝒪) ⊆ 𝒜(Ψ_s 𝒪)`) and, because the isometry preserves causal independence (their Lemma 4.9), maps
 causally-independent regions' observables to causally-independent ones
 (`covariantFlow_preserves_causalIndependence`).

So a Killing vector field of the spacetime supplies a one-parameter automorphism flow on the local observables,
generated by a `*`-derivation (the quantum Lie derivative), acting covariantly on the quasi-local net — the
curved-spacetime analogue of the Poincaré action.

* **§A — the quantum Killing Lie derivative** (`quantumKillingLieDerivative`, `_leibniz`).
* **§B — the Killing flow (one-parameter `*`-automorphism group)** (`KillingFlow`, `killingFlow_inverse`,
 `killingFlow_preserves_bracket`).
* **§C — the flow commutes with its generator** (`killingFlow_commutes_generator`).
* **§D — covariance on the quasi-local net** (`CovariantKillingFlow`, `covariantFlow_preserves_causalIndependence`).

The quantum Lie derivative is the exact inner derivation (`collisionStar`) with the Leibniz
rule; the Killing flow is the exact one-parameter `*`-automorphism group and its bracket-automorphism / inverse
consequences; covariance is the exact statement that the flow implements the geometric flow and preserves causal
independence. The *analytic* construction (`Ψ_s`, the strong-limit generator `δ_Z = lim(π_t−1)/t`, closability of
the derivation) is *not* built — the flow is taken as the algebraic object it induces. No new axioms.

## References

* L.E. Labuschagne, W.A. Majewski, arXiv:2503.14107, §§4–6 (Killing flows, Cor. 5.6, Thm. 5.3, Def. 6.1). Repo
 structures: `CollisionOperatorSl2.CollisionModular` (`collisionStar`), `AlgebraicQFTQuasifree.CausalOrthogonalityQuasiLocalNet`,
 `Curvature.DiffeomorphismMetricVariation` (`IsKillingVector`).

No new axioms.
-/

set_option autoImplicit false

open Physlib.QuantumMechanics.ComplexAction.CollisionOperatorSl2.CollisionModular
open Physlib.QuantumMechanics.ComplexAction.AlgebraicQFTQuasifree.CausalOrthogonalityQuasiLocalNet
open Physlib.QuantumMechanics.ComplexAction.AlgebraicQFT.GNSVonNeumannHadamard

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.AlgebraicQFTQuasifree.QuantumKillingFlowLieDerivative

variable {R : Type*} [Ring R]

/-! ## §A — the quantum Killing Lie derivative -/

/-- **The quantum Killing Lie derivative** `δ_Z(a) = [H_Z, a] = H_Z·a − a·H_Z` (Labuschagne–Majewski Def. 6.1) —
the infinitesimal generator of the quantum Killing flow, the inner derivation of the Killing generator `H_Z`. -/
def quantumKillingLieDerivative (H a : R) : R := collisionStar H a

/-- **[The quantum Killing Lie derivative is a derivation] `δ_Z(a·b) = δ_Z(a)·b + a·δ_Z(b)`.** The quantum Lie
derivative obeys the Leibniz rule — it is a `*`-derivation, the algebraic infinitesimal Killing symmetry of
Def. 6.1. -/
theorem quantumKillingLieDerivative_leibniz (H a b : R) :
    quantumKillingLieDerivative H (a * b)
      = quantumKillingLieDerivative H a * b + a * quantumKillingLieDerivative H b :=
  collisionStar_leibniz H a b

/-- **[The Killing generator is flow-invariant] `δ_Z(H_Z) = 0`.** The quantum Lie derivative annihilates its own
generator: the Killing "Hamiltonian" is conserved along the flow. -/
theorem quantumKillingLieDerivative_generator_invariant (H : R) :
    quantumKillingLieDerivative H H = 0 :=
  collisionStar_self H

/-! ## §B — the Killing flow: a one-parameter `*`-automorphism group -/

/-- **The quantum Killing flow** (Labuschagne–Majewski Cor. 5.6, Thm. 5.3): a one-parameter group of ring
`*`-automorphisms `π_s` of the local algebra implementing the isometric flow of a Killing field — `π_0 = id` and
the cocycle `π_{s+t} = π_s ∘ π_t`. -/
structure KillingFlow (R : Type*) [Ring R] where
  /-- the `*`-automorphism `π_s` at flow parameter `s`. -/
  π : ℝ → (R →+* R)
  /-- the flow at parameter `0` is the identity (`π_0 = id`). -/
  flow_zero : π 0 = RingHom.id R
  /-- the one-parameter group cocycle `π_{s+t} = π_s ∘ π_t` (Thm. 5.3). -/
  cocycle : ∀ s t : ℝ, π (s + t) = (π s).comp (π t)

/-- **[Each stage of the Killing flow is invertible] `π_s ∘ π_{−s} = id`.** The cocycle and `π_0 = id` make every
`π_s` a `*`-automorphism (a `*`-isomorphism of the algebra onto its image), with inverse `π_{−s}`. -/
theorem killingFlow_inverse (F : KillingFlow R) (s : ℝ) (a : R) : F.π s (F.π (-s) a) = a := by
  rw [← RingHom.comp_apply, ← F.cocycle, add_neg_cancel, F.flow_zero, RingHom.id_apply]

/-- **[The Killing flow is a Lie-bracket automorphism] `π_s([a,b]) = [π_s a, π_s b]`.** Being a ring
`*`-automorphism, each stage of the flow preserves the quantum Lie bracket (`collisionStar`) — the flow transports
the quantum Lie derivative structure. -/
theorem killingFlow_preserves_bracket (F : KillingFlow R) (s : ℝ) (a b : R) :
    F.π s (collisionStar a b) = collisionStar (F.π s a) (F.π s b) := by
  unfold collisionStar
  rw [map_sub, map_mul, map_mul]

/-! ## §C — the flow commutes with its generator -/

/-- **[The Killing flow commutes with its generator] `π_s(δ_Z a) = δ_Z(π_s a)`** when the Killing generator is
flow-invariant (`π_s H = H`). The algebraic statement that the Killing "Hamiltonian" is conserved: the flow
intertwines with the quantum Lie derivative it generates. -/
theorem killingFlow_commutes_generator (F : KillingFlow R) (H : R) (hH : ∀ s : ℝ, F.π s H = H)
    (s : ℝ) (a : R) :
    F.π s (quantumKillingLieDerivative H a) = quantumKillingLieDerivative H (F.π s a) := by
  unfold quantumKillingLieDerivative
  rw [killingFlow_preserves_bracket, hH]

/-! ## §D — covariance on the quasi-local net -/

/-- **A covariant Killing flow on a quasi-local net** (Labuschagne–Majewski Cor. 5.6(1), Lemma 4.9): the algebraic
Killing flow `F` together with the geometric flow `ψ` on regions, such that

* `implements` — `π_s` maps the local algebra `𝒜(𝒪)` into `𝒜(ψ_s 𝒪)` (the algebraic flow realizes the geometric
  isometric flow);
* `isometry` — the region flow preserves causal independence (the isometry maps spacelike pairs to spacelike
  pairs, Lemma 4.9). -/
structure CovariantKillingFlow (A : Type*) [Ring A] (ι : Type*) [Preorder ι] where
  /-- the quasi-local net of local algebras. -/
  net : QuasiLocalNet A ι
  /-- the algebraic Killing flow of `*`-automorphisms. -/
  flow : KillingFlow A
  /-- the geometric flow of isometries on regions `Ψ_s`. -/
  regionFlow : ℝ → ι → ι
  /-- the algebraic flow implements the geometric flow: `π_s 𝒜(𝒪) ⊆ 𝒜(ψ_s 𝒪)`. -/
  implements : ∀ (s : ℝ) (O : ι) (a : A), a ∈ net.alg O → flow.π s a ∈ net.alg (regionFlow s O)
  /-- the isometric region flow preserves causal independence (Lemma 4.9). -/
  isometry : ∀ (s : ℝ) (α β : ι), net.causal.orth α β → net.causal.orth (regionFlow s α) (regionFlow s β)

/-- **[The covariant Killing flow preserves microcausality].** The flow records causally-independent regions to
causally-independent regions (`isometry`), so the transported local algebras still have commuting observables
`𝒜(ψ_s α) ⊆ 𝒜(ψ_s β)'`: the quantum Killing flow is a symmetry of the causal net — the curved analogue of a
Poincaré transformation preserving Einstein causality. -/
theorem covariantFlow_preserves_causalIndependence {A : Type*} [Ring A] {ι : Type*} [Preorder ι]
    (C : CovariantKillingFlow A ι) (s : ℝ) {α β : ι} (h : C.net.causal.orth α β) :
    C.net.alg (C.regionFlow s α) ⊆ commutant (C.net.alg (C.regionFlow s β)) :=
  C.net.causalIndependence (C.isometry s α β h)

end Physlib.QuantumMechanics.ComplexAction.AlgebraicQFTQuasifree.QuantumKillingFlowLieDerivative

end
