/-
Copyright (c) 2026 Jorge A. Garcia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jorge A. Garcia
-/
module

public import Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.MaxwellFaraday
public import Physlib.QuantumMechanics.ComplexAction.CollisionOperatorSl2.LinearBoltzmannOperator
public import Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.LindbladSuperoperator

/-!
# A superoperator for the electromagnetic field

Constructs the **superoperator generated by the electromagnetic field strength** `F = dA`
(`PTSymmetricQFT.MaxwellFaraday.faraday`) — the adjoint (commutator) action `ad_F = [F, ·]` on the operator
algebra `Matrix (Fin 4) (Fin 4)`. Since `F^μ_ν` is antisymmetric (`faraday_antisymm`) it is a Lorentz
Lie-algebra element, and `ad_F` is the **infinitesimal Lorentz transformation the field generates** — the
electric part acting as boosts, the magnetic part as rotations.

The construction is identical in form to the Saveliev collision bracket `collisionStar = ad` of
`CollisionOperatorSl2.LinearBoltzmannOperator`, so the EM superoperator *inherits* its entire Lie structure (derivation /
Leibniz, the adjoint homomorphism `[ad_F, ad_G] = ad_{[F,G]}`, the Jacobi identity) from `collisionStar` —
and its Jacobi identity is the *same* one that serves as the BCJ **color** Jacobi
(`BCJDoubleCopy.SavelievLieColor`). The `ℂ`-Liouville generator `𝓛_F = −i[F, ·]` (Heisenberg time evolution) is
the `heisenbergGenerator` of `PTSymmetricQFT.LindbladSuperoperator` for the complexified field.

* **§A — the EM field adjoint superoperator** (`emFieldAdjoint`, `emFieldAdjoint_apply`,
  `emFieldAdjoint_eq_collisionStar`, `emFieldAdjoint_one`, `emFieldAdjoint_self`). `ad_F = mulLeft F −
  mulRight F`, `ad_F(X) = [F, X]`, `ad_F(1) = 0`, `ad_F(F) = 0`.
* **§B — the inherited Lie structure** (`emFieldAdjoint_leibniz`, `emFieldAdjoint_ad_hom`,
  `emFieldAdjoint_jacobi`). A derivation; the adjoint homomorphism `[ad_F, ad_G] = ad_{[F,G]}`; the Jacobi
  identity — all from `collisionStar`. The Jacobi is the BCJ color Jacobi.
* **§C — the field strength and the Heisenberg/Liouville generator** (`emFieldComplex`, `emLiouvillian`,
  `emLiouvillian_apply`, `faraday_emFieldAdjoint_self`). The actual `F = dA` generates the superoperator; the
  `ℂ` time-evolution generator `𝓛_F = −i[F, ·]` is `heisenbergGenerator` of the complexified field.

## References

* The electromagnetic field strength `F_{μν} = ∂_μ A_ν − ∂_ν A_μ` as a Lorentz Lie-algebra element; the
  adjoint (Liouville/Heisenberg) action of an operator on the operator algebra.
* Repo dependencies: `PTSymmetricQFT.MaxwellFaraday` (`faraday`, `faraday_antisymm`);
  `CollisionOperatorSl2.LinearBoltzmannOperator` / `CollisionOperatorSl2.CollisionModular` (`collisionStar`,
  `collisionStar_leibniz`, `collisionStar_ad_hom`, `collisionStar_jacobi`);
  `PTSymmetricQFT.LindbladSuperoperator` (`heisenbergGenerator`).

No new axioms.
-/

set_option autoImplicit false

@[expose] public section

namespace Physlib.QuantumMechanics.ComplexAction.Electromagnetic.EMFieldSuperoperator

open Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.MaxwellFaraday
open Physlib.QuantumMechanics.ComplexAction.CollisionOperatorSl2.CollisionModular
open Physlib.QuantumMechanics.ComplexAction.CollisionOperatorSl2.LinearBoltzmannOperator
open Physlib.QuantumMechanics.ComplexAction.PTSymmetricQFT.LindbladSuperoperator

/-- The operator algebra on which the EM field strength acts as a superoperator — real `4×4` matrices
(spacetime indices). -/
abbrev Mat := Matrix (Fin 4) (Fin 4) ℝ

/-! ## §A — the EM field adjoint superoperator -/

/-- **The superoperator of the electromagnetic field strength** `ad_F = [F, ·] = mulLeft F − mulRight F`.
With `F^μ_ν` antisymmetric (a Lorentz generator), `ad_F` is the infinitesimal Lorentz transformation the
field generates. -/
noncomputable def emFieldAdjoint (F : Mat) : Mat →ₗ[ℝ] Mat :=
  LinearMap.mulLeft ℝ F - LinearMap.mulRight ℝ F

/-- **`ad_F(X) = [F, X]`** — the commutator action. -/
@[simp] theorem emFieldAdjoint_apply (F X : Mat) : emFieldAdjoint F X = F * X - X * F := by
  simp [emFieldAdjoint]

/-- **`ad_F` is the Saveliev `collisionStar`** (`= ad`) of the field strength — the EM superoperator is the
adjoint bracket, identifying it with the collision/Lie bracket of `CollisionOperatorSl2.LinearBoltzmannOperator`. -/
theorem emFieldAdjoint_eq_collisionStar (F X : Mat) : emFieldAdjoint F X = collisionStar F X := by
  rw [emFieldAdjoint_apply, collisionStar]

/-- **`ad_F(1) = 0`** — the field commutes with the identity. -/
@[simp] theorem emFieldAdjoint_one (F : Mat) : emFieldAdjoint F 1 = 0 := by
  simp [emFieldAdjoint_apply]

/-- **`ad_F(F) = 0`** — the field commutes with itself. -/
@[simp] theorem emFieldAdjoint_self (F : Mat) : emFieldAdjoint F F = 0 := by
  rw [emFieldAdjoint_eq_collisionStar, collisionStar_self]

/-! ## §B — the inherited Lie structure -/

/-- **`ad_F` is a derivation** `ad_F(XY) = ad_F(X)·Y + X·ad_F(Y)` — from `collisionStar_leibniz`. -/
theorem emFieldAdjoint_leibniz (F X Y : Mat) :
    emFieldAdjoint F (X * Y) = emFieldAdjoint F X * Y + X * emFieldAdjoint F Y := by
  simp only [emFieldAdjoint_eq_collisionStar]; exact collisionStar_leibniz F X Y

/-- **The adjoint homomorphism `[ad_F, ad_G] = ad_{[F,G]}`** — the EM field adjoints close into a Lie
algebra (the Lorentz algebra). From `collisionStar_ad_hom`. -/
theorem emFieldAdjoint_ad_hom (F G X : Mat) :
    emFieldAdjoint F (emFieldAdjoint G X) - emFieldAdjoint G (emFieldAdjoint F X)
      = emFieldAdjoint (emFieldAdjoint F G) X := by
  simp only [emFieldAdjoint_eq_collisionStar]; exact collisionStar_ad_hom F G X

/-- **The Jacobi identity** `[F,[G,X]] + [G,[X,F]] + [X,[F,G]] = 0` — the EM field adjoint's Jacobi, *the
same* identity that serves as the BCJ color Jacobi (`BCJDoubleCopy.SavelievLieColor`). From
`collisionStar_jacobi`. -/
theorem emFieldAdjoint_jacobi (F G X : Mat) :
    emFieldAdjoint F (emFieldAdjoint G X) + emFieldAdjoint G (emFieldAdjoint X F)
      + emFieldAdjoint X (emFieldAdjoint F G) = 0 := by
  simp only [emFieldAdjoint_eq_collisionStar]; exact collisionStar_jacobi F G X

/-! ## §C — the field strength and the Heisenberg/Liouville generator -/

/-- **The complexified electromagnetic field strength** `F_ℂ = dA` (as a complex matrix, for the unitary
time evolution). -/
noncomputable def emFieldComplex (k A : Fin 4 → ℝ) : Matrix (Fin 4) (Fin 4) ℂ :=
  (faraday k A).map (Complex.ofReal)

/-- **The EM Liouville / Heisenberg generator** `𝓛_F = −i[F, ·]` — the unitary time-evolution superoperator
generated by the field, the `heisenbergGenerator` of `PTSymmetricQFT.LindbladSuperoperator`. -/
noncomputable def emLiouvillian (F : Matrix (Fin 4) (Fin 4) ℂ) :
    Matrix (Fin 4) (Fin 4) ℂ →ₗ[ℂ] Matrix (Fin 4) (Fin 4) ℂ :=
  heisenbergGenerator F

/-- **`𝓛_F(Y) = −i[F, Y]`** — the Heisenberg equation of motion under the field. -/
theorem emLiouvillian_apply (F Y : Matrix (Fin 4) (Fin 4) ℂ) :
    emLiouvillian F Y = -Complex.I • (F * Y - Y * F) := by
  rw [emLiouvillian, heisenbergGenerator_apply]

/-- **The field strength `F = dA` commutes with itself under its own adjoint** `ad_F(F) = 0` — the
electromagnetic field generates a superoperator that annihilates the field itself. -/
@[simp] theorem faraday_emFieldAdjoint_self (k A : Fin 4 → ℝ) :
    emFieldAdjoint (faraday k A) (faraday k A) = 0 :=
  emFieldAdjoint_self _

end Physlib.QuantumMechanics.ComplexAction.Electromagnetic.EMFieldSuperoperator

end
